// Spec 847 — finding the documents, and saying which ones declare themselves.
//
// Where they live was settled by counting rather than by asking. Wasteland_EF holds 148
// Markdown files, 108 of them "outside docs/" — and every one of those sits in a NESTED
// docs directory (`cart_EF/docs/engine`, `editor/docs`, `cart_EF/docs/port`). So the rule
// is any `docs/` directory in the tree, not the project's own.
//
// And the number that shapes the report: no document in any project carries frontmatter
// today. The only YAML headers in the whole corpus belong to `.claude/skills`. Every
// existing document is therefore undeclared on day one, which a check has to present as a
// BACKLOG — something to work through — and not as a hundred failures.

import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, basename } from "node:path";
import { parseFrontmatter, type Frontmatter } from "./frontmatter.js";

const SKIP_DIRS = new Set([".git", "node_modules", ".claude", ".cache", "_archive", "dist", "build"]);

/** Generated by render_docs — declared by us, not by a person. */
const GENERATED_NAMES = new Set(["FINDINGS.md", "ENTITIES.md", "OPEN_QUESTIONS.md", "ANTI_PATTERNS.md"]);

export interface ScannedDoc {
  /** Project-relative path — the id a citation uses. */
  path: string;
  /** Basename, which is what `amends:` normally names. */
  name: string;
  bytes: number;
  frontmatter?: Frontmatter;
  /** Set when a block exists but does not parse — different from undeclared. */
  error?: string;
  declared: boolean;
  generated: boolean;
}

export function scanDocs(projectDir: string): ScannedDoc[] {
  const out: ScannedDoc[] = [];
  for (const dir of findDocsDirs(projectDir)) {
    for (const file of walkMarkdown(dir)) {
      let text = "";
      try { text = readFileSync(file, "utf8"); } catch { continue; }
      const parsed = parseFrontmatter(text);
      const rel = relative(projectDir, file);
      out.push({
        path: rel,
        name: basename(file),
        bytes: text.length,
        ...(parsed.frontmatter ? { frontmatter: parsed.frontmatter } : {}),
        ...(parsed.error ? { error: parsed.error } : {}),
        declared: !!parsed.frontmatter,
        generated: GENERATED_NAMES.has(basename(file)) || parsed.frontmatter?.kind === "generated",
      });
    }
  }
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

/** Every `docs/` directory in the tree, at any depth. */
export function findDocsDirs(root: string, depth = 0): string[] {
  if (depth > 5 || !existsSync(root)) return [];
  const found: string[] = [];
  let entries: string[];
  try { entries = readdirSync(root); } catch { return []; }
  for (const e of entries) {
    if (SKIP_DIRS.has(e) || e.startsWith(".")) continue;
    const p = join(root, e);
    let isDir = false;
    try { isDir = statSync(p).isDirectory(); } catch { continue; }
    if (!isDir) continue;
    if (e === "docs") found.push(p);
    else found.push(...findDocsDirs(p, depth + 1));
  }
  return found;
}

function walkMarkdown(dir: string, depth = 0): string[] {
  if (depth > 4) return [];
  const out: string[] = [];
  let entries: string[];
  try { entries = readdirSync(dir); } catch { return []; }
  for (const e of entries) {
    if (SKIP_DIRS.has(e) || e.startsWith(".")) continue;
    const p = join(dir, e);
    let st;
    try { st = statSync(p); } catch { continue; }
    if (st.isDirectory()) out.push(...walkMarkdown(p, depth + 1));
    else if (e.toLowerCase().endsWith(".md")) out.push(p);
  }
  return out;
}

export interface DocLintReport {
  docs: ScannedDoc[];
  undeclared: ScannedDoc[];
  malformed: ScannedDoc[];
  /** `amends:` naming a document that is not in this project. 847 D5. */
  dangling: Array<{ from: string; names: string[] }>;
  declaredCount: number;
}

export function lintDocs(projectDir: string): DocLintReport {
  const docs = scanDocs(projectDir);
  const byName = new Set(docs.map((d) => d.name));
  const byPath = new Set(docs.map((d) => d.path));

  const dangling: Array<{ from: string; names: string[] }> = [];
  for (const d of docs) {
    const names = (d.frontmatter?.amends ?? []).filter((a) => !byName.has(a) && !byPath.has(a));
    if (names.length > 0) dangling.push({ from: d.path, names });
  }

  return {
    docs,
    undeclared: docs.filter((d) => !d.declared && !d.error),
    malformed: docs.filter((d) => !!d.error),
    dangling,
    declaredCount: docs.filter((d) => d.declared).length,
  };
}

export function formatDocLint(r: DocLintReport): string {
  const out: string[] = [];
  out.push(`Documents: ${r.docs.length} found, ${r.declaredCount} declared, ${r.undeclared.length} undeclared, ${r.malformed.length} malformed`);

  if (r.malformed.length > 0) {
    out.push("", "--- malformed (a block exists but does not parse) ---");
    for (const d of r.malformed) out.push(`  ${d.path}\n     ${d.error}`);
  }
  if (r.dangling.length > 0) {
    out.push("", "--- dangling citations (`amends:` names a document that is not here) ---");
    for (const d of r.dangling) out.push(`  ${d.from} -> ${d.names.join(", ")}`);
  }
  if (r.undeclared.length > 0) {
    out.push("", `--- undeclared (${r.undeclared.length}) — biggest first, they are the ones worth declaring ---`);
    for (const d of [...r.undeclared].sort((a, b) => b.bytes - a.bytes).slice(0, 20)) {
      out.push(`  ${(d.bytes / 1024).toFixed(0).padStart(4)} KB  ${d.path}${d.generated ? "  (generated)" : ""}`);
    }
    if (r.undeclared.length > 20) out.push(`  ... ${r.undeclared.length - 20} more`);
    out.push("", "`doc_register <path>` declares one. No project in the corpus had frontmatter before this,");
    out.push("so a full list here is a backlog, not a failure.");
  }
  return out.join("\n");
}
