// Spec 847 — finding the documents, and saying which ones declare themselves.
//
// Where they live was settled by counting rather than by asking. Wasteland_EF holds 148
// Markdown files, 108 of them "outside docs/" — and every one of those sits in a NESTED
// docs directory (`cart_EF/docs/engine`, `editor/docs`, `cart_EF/docs/port`). So the rule
// is any `docs/` directory in the tree, not the project's own.
//
// A document `doc_register` declared counts wherever it lives in the project; see
// `listDocFiles`.
//
// And the number that shapes the report: no document in any project carries frontmatter
// today. The only YAML headers in the whole corpus belong to `.claude/skills`. Every
// existing document is therefore undeclared on day one, which a check has to present as a
// BACKLOG — something to work through — and not as a hundred failures.

import { existsSync, readdirSync, readFileSync, statSync, type Dirent } from "node:fs";
import { join, relative, basename, resolve, isAbsolute, sep } from "node:path";
import { parseFrontmatter, type Frontmatter } from "./frontmatter.js";
import { projectSkipDirs } from "../project-knowledge/inventory-patterns.js";
import { GraphStore } from "../knowledge-graph/store.js";

const SKIP_DIRS = new Set([".git", "node_modules", ".claude", ".cache", "_archive", "dist", "build"]);

/** Generated by render_docs — declared by us, not by a person. */
const GENERATED_NAMES = new Set(["FINDINGS.md", "ENTITIES.md", "OPEN_QUESTIONS.md", "ANTI_PATTERNS.md"]);

export interface ScannedDoc {
  /** Project-relative path — the id a citation uses. */
  path: string;
  /** Basename, which is what `amends:` normally names. */
  name: string;
  bytes: number;
  frontmatter?: Frontmatter;
  /** Set when a block exists but does not parse — different from undeclared. */
  error?: string;
  declared: boolean;
  generated: boolean;
}

export function scanDocs(projectDir: string): ScannedDoc[] {
  const out: ScannedDoc[] = [];
  for (const file of listDocFiles(projectDir)) {
    let text = "";
    try { text = readFileSync(file, "utf8"); } catch { continue; }
    const parsed = parseFrontmatter(text);
    const rel = relative(projectDir, file);
    out.push({
      path: rel,
      name: basename(file),
      bytes: text.length,
      ...(parsed.frontmatter ? { frontmatter: parsed.frontmatter } : {}),
      ...(parsed.error ? { error: parsed.error } : {}),
      declared: !!parsed.frontmatter,
      generated: GENERATED_NAMES.has(basename(file)) || parsed.frontmatter?.kind === "generated",
    });
  }
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

/**
 * The document set, as absolute paths, without reading a byte of any of them.
 *
 * Two sources, one set: every `docs/` directory in the tree, plus every document
 * `doc_register` recorded wherever it lives inside the project (`port/v1/PATCHES.md`,
 * `analysis/port/*.md`). A registered document that only one reader could see answered
 * "Registered" and was then missing from the lint, the status and the contract check.
 *
 * `scanDocs` is built on this, and so is Spec 740.3's cache fingerprint: the search asks
 * "did any document change since I was built" against exactly the files the critic and
 * the index read, never against a second walk that could disagree about what a document is.
 */
export function listDocFiles(projectDir: string): string[] {
  const out = new Set<string>();
  for (const dir of findDocsDirs(projectDir, 0, projectSkipDirs(projectDir), projectDir)) {
    for (const f of walkMarkdown(dir)) out.add(f);
  }
  for (const f of registeredDocFiles(projectDir)) out.add(f);
  return [...out];
}

/** Is `abs` strictly inside `root`? */
export function insideProject(root: string, abs: string): boolean {
  const rel = relative(resolve(root), resolve(abs));
  return rel !== "" && rel !== ".." && !rel.startsWith(".." + sep) && !isAbsolute(rel);
}

/**
 * The files `doc_register` recorded: the graph's `document` nodes carry the path. A
 * placeholder (cited, never written), a file that is gone, and a path outside the project
 * root count for nothing.
 */
function registeredDocFiles(projectDir: string): string[] {
  let store: GraphStore;
  try { store = GraphStore.open(projectDir, { readOnly: true }); } catch { return []; }
  const out: string[] = [];
  try {
    const rows = store.db.prepare("SELECT attrs FROM nodes WHERE kind = 'document'").all() as Array<{ attrs: string }>;
    for (const r of rows) {
      let a: Record<string, unknown> = {};
      try { a = JSON.parse(r.attrs) as Record<string, unknown>; } catch { continue; }
      if (a.placeholder === true || typeof a.path !== "string") continue;
      const abs = resolve(projectDir, a.path);
      if (!insideProject(projectDir, abs) || !abs.toLowerCase().endsWith(".md") || !existsSync(abs)) continue;
      out.push(abs);
    }
  } catch { /* a graph without document nodes registers nothing */ } finally { store.close(); }
  return out;
}

/**
 * Is this entry a directory? The entry type from `readdir` answers it without a `stat`,
 * except for a symlink, which is followed as before. Spec 740.3 walks this tree on every
 * search to see whether a document changed: on Ultima VI (12 700 entries) a `stat` per
 * entry cost ~90 ms of every answer, the entry type costs next to nothing.
 */
function isDirEntry(parent: string, e: Dirent): boolean | undefined {
  if (!e.isSymbolicLink()) return e.isDirectory();
  try { return statSync(join(parent, e.name)).isDirectory(); } catch { return undefined; }
}

/** Every `docs/` directory in the tree, at any depth. */
export function findDocsDirs(root: string, depth = 0, skip: (relPath: string) => boolean = () => false, projectRoot: string = root): string[] {
  if (depth > 5 || !existsSync(root)) return [];
  const found: string[] = [];
  let entries: Dirent[];
  try { entries = readdirSync(root, { withFileTypes: true }); } catch { return []; }
  for (const e of entries) {
    if (SKIP_DIRS.has(e.name) || e.name.startsWith(".")) continue;
    if (!isDirEntry(root, e)) continue;
    const p = join(root, e.name);
    if (skip(relative(projectRoot, p))) continue;
    if (e.name === "docs") found.push(p);
    else found.push(...findDocsDirs(p, depth + 1, skip, projectRoot));
  }
  return found;
}

function walkMarkdown(dir: string, depth = 0): string[] {
  if (depth > 4) return [];
  const out: string[] = [];
  let entries: Dirent[];
  try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return []; }
  for (const e of entries) {
    if (SKIP_DIRS.has(e.name) || e.name.startsWith(".")) continue;
    const isDir = isDirEntry(dir, e);
    if (isDir === undefined) continue;
    const p = join(dir, e.name);
    if (isDir) out.push(...walkMarkdown(p, depth + 1));
    else if (e.name.toLowerCase().endsWith(".md")) out.push(p);
  }
  return out;
}

export interface DocLintReport {
  docs: ScannedDoc[];
  undeclared: ScannedDoc[];
  malformed: ScannedDoc[];
  /** `amends:` naming a document that is not in this project. 847 D5. */
  dangling: Array<{ from: string; names: string[] }>;
  declaredCount: number;
}

export function lintDocs(projectDir: string): DocLintReport {
  const docs = scanDocs(projectDir);
  const byName = new Set(docs.map((d) => d.name));
  const byPath = new Set(docs.map((d) => d.path));

  const dangling: Array<{ from: string; names: string[] }> = [];
  for (const d of docs) {
    const names = (d.frontmatter?.amends ?? []).filter((a) => !byName.has(a) && !byPath.has(a));
    if (names.length > 0) dangling.push({ from: d.path, names });
  }

  return {
    docs,
    undeclared: docs.filter((d) => !d.declared && !d.error),
    malformed: docs.filter((d) => !!d.error),
    dangling,
    declaredCount: docs.filter((d) => d.declared).length,
  };
}

export function formatDocLint(r: DocLintReport): string {
  const out: string[] = [];
  out.push(`Documents: ${r.docs.length} found, ${r.declaredCount} declared, ${r.undeclared.length} undeclared, ${r.malformed.length} malformed`);

  if (r.malformed.length > 0) {
    out.push("", "--- malformed (a block exists but does not parse) ---");
    for (const d of r.malformed) out.push(`  ${d.path}\n     ${d.error}`);
  }
  if (r.dangling.length > 0) {
    out.push("", "--- dangling citations (`amends:` names a document that is not here) ---");
    for (const d of r.dangling) out.push(`  ${d.from} -> ${d.names.join(", ")}`);
  }
  if (r.undeclared.length > 0) {
    out.push("", `--- undeclared (${r.undeclared.length}) — biggest first, they are the ones worth declaring ---`);
    for (const d of [...r.undeclared].sort((a, b) => b.bytes - a.bytes).slice(0, 20)) {
      out.push(`  ${(d.bytes / 1024).toFixed(0).padStart(4)} KB  ${d.path}${d.generated ? "  (generated)" : ""}`);
    }
    if (r.undeclared.length > 20) out.push(`  ... ${r.undeclared.length - 20} more`);
    out.push("", "`doc_register <path>` declares one. No project in the corpus had frontmatter before this,");
    out.push("so a full list here is a backlog, not a failure.");
  }
  return out.join("\n");
}
