// Spec 898 D3 -- vic20 names, address -> label rows taken from the published ROM source.
// Row = [address, symbol, name, description, source]. Generated once from the assembled
// listings; the source files themselves are not in this repo. A register the source never
// names has no row here; seeds/secondary.ts fills those from Commodore's own references, marked.
import type { SeedRegion, SeedRow } from "./types.js";

export const VIC20_ROWS: SeedRow[] = [
  [0x0000, "USRPOK", "USRPOK", "3 bytes", "vic20 basic.src: usrpok"],
  [0x0003, "ADRAY1", "ADRAY1", "convert float->integer; 2 bytes", "vic20 basic.src: adray1"],
  [0x0005, "ADRAY2", "ADRAY2", "convert integer->float; 2 bytes", "vic20 basic.src: adray2"],
  [0x0007, "CHARAC", "CHARAC", "also: INTEGR", "vic20 basic.src: charac"],
  [0x0008, "ENDCHR", "ENDCHR", null, "vic20 basic.src: endchr"],
  [0x0009, "TRMPOS", "TRMPOS", null, "vic20 basic.src: trmpos"],
  [0x000a, "VERCK", "VERCK", null, "vic20 basic.src: verck"],
  [0x000b, "COUNT", "COUNT", null, "vic20 basic.src: count"],
  [0x000c, "DIMFLG", "DIMFLG", null, "vic20 basic.src: dimflg"],
  [0x000d, "VALTYP", "VALTYP", null, "vic20 basic.src: valtyp"],
  [0x000e, "INTFLG", "INTFLG", null, "vic20 basic.src: intflg"],
  [0x000f, "DORES", "DORES", "also: GARBFL", "vic20 basic.src: dores"],
  [0x0010, "SUBFLG", "SUBFLG", null, "vic20 basic.src: subflg"],
  [0x0011, "INPFLG", "INPFLG", null, "vic20 basic.src: inpflg"],
  [0x0012, "TANSGN", "TANSGN", "also: DOMASK", "vic20 basic.src: tansgn"],
  [0x0013, "CHANNL", "CHANNL", null, "vic20 basic.src: channl"],
  [0x0014, "LINNUM", "LINNUM", "2 bytes; also: POKER", "vic20 basic.src: linnum"],
  [0x0016, "TEMPPT", "TEMPPT", null, "vic20 basic.src: temppt"],
  [0x0017, "LASTPT", "LASTPT", "2 bytes", "vic20 basic.src: lastpt"],
  [0x0019, "TEMPST", "TEMPST", "9 bytes", "vic20 basic.src: tempst"],
  [0x0022, "INDEX1", "INDEX1", "2 bytes; also: INDEX", "vic20 basic.src: index1"],
  [0x0024, "INDEX2", "INDEX2", "2 bytes", "vic20 basic.src: index2"],
  [0x0026, "RESHO", "RESHO", null, "vic20 basic.src: resho"],
  [0x0027, "RESMOH", "RESMOH", null, "vic20 basic.src: resmoh"],
  [0x0028, "RESMO", "RESMO", "also: ADDEND", "vic20 basic.src: resmo"],
  [0x0029, "RESLO", "RESLO", null, "vic20 basic.src: reslo"],
  [0x002b, "TXTTAB", "TXTTAB", "2 bytes", "vic20 basic.src: txttab"],
  [0x002d, "VARTAB", "VARTAB", "2 bytes", "vic20 basic.src: vartab"],
  [0x002f, "ARYTAB", "ARYTAB", "2 bytes", "vic20 basic.src: arytab"],
  [0x0031, "STREND", "STREND", "2 bytes", "vic20 basic.src: strend"],
  [0x0033, "FRETOP", "FRETOP", "2 bytes", "vic20 basic.src: fretop"],
  [0x0035, "FRESPC", "FRESPC", "2 bytes", "vic20 basic.src: frespc"],
  [0x0037, "MEMSIZ", "MEMSIZ", "2 bytes", "vic20 basic.src: memsiz"],
  [0x0039, "CURLIN", "CURLIN", "2 bytes", "vic20 basic.src: curlin"],
  [0x003b, "OLDLIN", "OLDLIN", "2 bytes", "vic20 basic.src: oldlin"],
  [0x003d, "OLDTXT", "OLDTXT", "2 bytes", "vic20 basic.src: oldtxt"],
  [0x003f, "DATLIN", "DATLIN", "2 bytes", "vic20 basic.src: datlin"],
  [0x0041, "DATPTR", "DATPTR", "2 bytes", "vic20 basic.src: datptr"],
  [0x0043, "INPPTR", "INPPTR", "2 bytes", "vic20 basic.src: inpptr"],
  [0x0045, "VARNAM", "VARNAM", "2 bytes", "vic20 basic.src: varnam"],
  [0x0047, "VARPNT", "VARPNT", "2 bytes; also: FDECPT", "vic20 basic.src: varpnt"],
  [0x0049, "FORPNT", "FORPNT", "2 bytes; also: LSTPNT, ANDMSK", "vic20 basic.src: forpnt"],
  [0x004a, "EORMSK", "EORMSK", null, "vic20 basic.src: eormsk"],
  [0x004b, "OPPTR", "OPPTR", "2 bytes; also: VARTXT", "vic20 basic.src: opptr"],
  [0x004d, "OPMASK", "OPMASK", null, "vic20 basic.src: opmask"],
  [0x004e, "DEFPNT", "DEFPNT", "2 bytes; also: GRBPNT, TEMPF3", "vic20 basic.src: defpnt"],
  [0x0050, "DSCPNT", "DSCPNT", "2 bytes", "vic20 basic.src: dscpnt"],
  [0x0053, "FOUR6", "FOUR6", null, "vic20 basic.src: four6"],
  [0x0054, "JMPER", "JMPER", null, "vic20 basic.src: jmper"],
  [0x0055, "SIZE", "SIZE", null, "vic20 basic.src: size"],
  [0x0056, "OLDOV", "OLDOV", null, "vic20 basic.src: oldov"],
  [0x0057, "TEMPF1", "TEMPF1", null, "vic20 basic.src: tempf1"],
  [0x0058, "HIGHDS", "HIGHDS", "2 bytes; also: ARYPNT", "vic20 basic.src: highds"],
  [0x005a, "HIGHTR", "HIGHTR", "2 bytes", "vic20 basic.src: hightr"],
  [0x005c, "TEMPF2", "TEMPF2", null, "vic20 basic.src: tempf2"],
  [0x005d, "LOWDS", "LOWDS", "2 bytes; also: DECCNT", "vic20 basic.src: lowds"],
  [0x005e, "TENEXP", "TENEXP", null, "vic20 basic.src: tenexp"],
  [0x005f, "LOWTR", "LOWTR", "also: GRBTOP, DPTFLG", "vic20 basic.src: lowtr"],
  [0x0060, "EXPSGN", "EXPSGN", null, "vic20 basic.src: expsgn"],
  [0x0061, "FACEXP", "FACEXP", "also: DSCTMP, FAC", "vic20 basic.src: facexp"],
  [0x0062, "FACHO", "FACHO", null, "vic20 basic.src: facho"],
  [0x0063, "FACMOH", "FACMOH", null, "vic20 basic.src: facmoh"],
  [0x0064, "FACMO", "FACMO", "also: INDICE", "vic20 basic.src: facmo"],
  [0x0065, "FACLO", "FACLO", null, "vic20 basic.src: faclo"],
  [0x0066, "FACSGN", "FACSGN", null, "vic20 basic.src: facsgn"],
  [0x0067, "SGNFLG", "SGNFLG", "also: DEGREE", "vic20 basic.src: sgnflg"],
  [0x0068, "BITS", "BITS", null, "vic20 basic.src: bits"],
  [0x0069, "ARGEXP", "ARGEXP", null, "vic20 basic.src: argexp"],
  [0x006a, "ARGHO", "ARGHO", null, "vic20 basic.src: argho"],
  [0x006b, "ARGMOH", "ARGMOH", null, "vic20 basic.src: argmoh"],
  [0x006c, "ARGMO", "ARGMO", null, "vic20 basic.src: argmo"],
  [0x006d, "ARGLO", "ARGLO", null, "vic20 basic.src: arglo"],
  [0x006e, "ARGSGN", "ARGSGN", null, "vic20 basic.src: argsgn"],
  [0x006f, "ARISGN", "ARISGN", null, "vic20 basic.src: arisgn"],
  [0x0070, "FACOV", "FACOV", null, "vic20 basic.src: facov"],
  [0x0071, "FBUFPT", "FBUFPT", "2 bytes; also: BUFPTR, STRNG2, POLYPT, CURTOL", "vic20 basic.src: fbufpt"],
  [0x0073, "CHRGET", "CHRGET", "6 bytes", "vic20 basic.src: chrget"],
  [0x0079, "CHRGOT", "CHRGOT", null, "vic20 basic.src: chrgot"],
  [0x007a, "TXTPTR", "TXTPTR", "6 bytes", "vic20 basic.src: txtptr"],
  [0x0080, "QNUM", "QNUM", "10 bytes", "vic20 basic.src: qnum"],
  [0x008a, "CHRRTS", "CHRRTS", null, "vic20 basic.src: chrrts"],
  [0x008b, "RNDX", "RNDX", "5 bytes", "vic20 basic.src: rndx"],
  [0x0090, "STATUS", "STATUS", "i/o operation status byte", "vic20 kernal.src: status"],
  [0x0091, "STKEY", "STKEY", "stop key flag", "vic20 kernal.src: stkey"],
  [0x0092, "SVXT", "SVXT", "temporary", "vic20 kernal.src: svxt"],
  [0x0093, "VERCK", "VERCK", "load or verify flag", "vic20 kernal.src: verck"],
  [0x0094, "C3P0", "C3P0", "ieee buffered char flag", "vic20 kernal.src: c3p0"],
  [0x0095, "BSOUR", "BSOUR", "char buffer for ieee", "vic20 kernal.src: bsour"],
  [0x0096, "SYNO", "SYNO", "cassette sync #", "vic20 kernal.src: syno"],
  [0x0097, "XSAV", "XSAV", "temp for basin", "vic20 kernal.src: xsav"],
  [0x0098, "LDTND", "LDTND", "index to logical file", "vic20 kernal.src: ldtnd"],
  [0x0099, "DFLTN", "DFLTN", "default input device #", "vic20 kernal.src: dfltn"],
  [0x009a, "DFLTO", "DFLTO", "default output device #", "vic20 kernal.src: dflto"],
  [0x009b, "PRTY", "PRTY", "cassette parity", "vic20 kernal.src: prty"],
  [0x009c, "DPSW", "DPSW", "cassette dipole switch", "vic20 kernal.src: dpsw"],
  [0x009d, "MSGFLG", "MSGFLG", "os message flag", "vic20 kernal.src: msgflg"],
  [0x009e, "T1", "T1", "temporary 1; also: PTR1", "vic20 kernal.src: t1"],
  [0x009f, "T2", "T2", "temporary 2; also: PTR2", "vic20 kernal.src: t2"],
  [0x00a0, "TIME", "TIME", "24 hour clock in 1/60th seconds; 3 bytes", "vic20 kernal.src: time"],
  [0x00a3, "PCNTR", "PCNTR", "cassette stuff; also: R2D2", "vic20 kernal.src: pcntr"],
  [0x00a4, "FIRT", "FIRT", "also: BSOUR1", "vic20 kernal.src: firt"],
  [0x00a5, "CNTDN", "CNTDN", "cassette sync countdown; also: COUNT", "vic20 kernal.src: cntdn"],
  [0x00a6, "BUFPT", "BUFPT", "cassette buffer pointer", "vic20 kernal.src: bufpt"],
  [0x00a7, "SHCNL", "SHCNL", "cassette short count; also: INBIT", "vic20 kernal.src: shcnl"],
  [0x00a8, "RER", "RER", "cassette read error; also: BITCI", "vic20 kernal.src: rer"],
  [0x00a9, "REZ", "REZ", "cassete reading zeroes; also: RINONE", "vic20 kernal.src: rez"],
  [0x00aa, "RDFLG", "RDFLG", "cassette read mode; also: RIDATA", "vic20 kernal.src: rdflg"],
  [0x00ab, "SHCNH", "SHCNH", "cassette short cnt; also: RIPRTY", "vic20 kernal.src: shcnh"],
  [0x00ac, "SAL", "SAL", null, "vic20 kernal.src: sal"],
  [0x00ad, "SAH", "SAH", null, "vic20 kernal.src: sah"],
  [0x00ae, "EAL", "EAL", null, "vic20 kernal.src: eal"],
  [0x00af, "EAH", "EAH", null, "vic20 kernal.src: eah"],
  [0x00b0, "CMP0", "CMP0", null, "vic20 kernal.src: cmp0"],
  [0x00b1, "TEMP", "TEMP", null, "vic20 kernal.src: temp"],
  [0x00b2, "TAPE1", "TAPE1", "address of tape buffer #1y.; 2 bytes", "vic20 kernal.src: tape1"],
  [0x00b4, "SNSW1", "SNSW1", "also: BITTS", "vic20 kernal.src: snsw1"],
  [0x00b5, "DIFF", "DIFF", "also: NXTBIT", "vic20 kernal.src: diff"],
  [0x00b6, "PRP", "PRP", "also: RODATA", "vic20 kernal.src: prp"],
  [0x00b7, "FNLEN", "FNLEN", "length current file n str", "vic20 kernal.src: fnlen"],
  [0x00b8, "LA", "LA", "current file logical addr", "vic20 kernal.src: la"],
  [0x00b9, "SA", "SA", "current file 2nd addr", "vic20 kernal.src: sa"],
  [0x00ba, "FA", "FA", "current file primary addr", "vic20 kernal.src: fa"],
  [0x00bb, "FNADR", "FNADR", "addr current file name str; 2 bytes", "vic20 kernal.src: fnadr"],
  [0x00bd, "OCHAR", "OCHAR", "also: ROPRTY", "vic20 kernal.src: ochar"],
  [0x00be, "FSBLK", "FSBLK", "cassette read block count", "vic20 kernal.src: fsblk"],
  [0x00bf, "MYCH", "MYCH", null, "vic20 kernal.src: mych"],
  [0x00c0, "CAS1", "CAS1", "cassette manual/controlled switch", "vic20 kernal.src: cas1"],
  [0x00c1, "STAL", "STAL", "also: TMP0", "vic20 kernal.src: stal"],
  [0x00c2, "STAH", "STAH", null, "vic20 kernal.src: stah"],
  [0x00c3, "TMP2", "TMP2", "2 bytes; also: MEMUSS", "vic20 kernal.src: tmp2"],
  [0x00c5, "LSTX", "LSTX", "key scan index", "vic20 kernal.src: lstx"],
  [0x00c6, "NDX", "NDX", "index to keyboard q", "vic20 kernal.src: ndx"],
  [0x00c7, "RVS", "RVS", "rvs field on flag", "vic20 kernal.src: rvs"],
  [0x00c8, "INDX", "INDX", null, "vic20 kernal.src: indx"],
  [0x00c9, "LSXP", "LSXP", "x pos at start", "vic20 kernal.src: lsxp"],
  [0x00ca, "LSTP", "LSTP", null, "vic20 kernal.src: lstp"],
  [0x00cb, "SFDX", "SFDX", "shift mode on print", "vic20 kernal.src: sfdx"],
  [0x00cc, "BLNSW", "BLNSW", "cursor blink enab", "vic20 kernal.src: blnsw"],
  [0x00cd, "BLNCT", "BLNCT", "count to toggle cur", "vic20 kernal.src: blnct"],
  [0x00ce, "GDBLN", "GDBLN", "char before cursor", "vic20 kernal.src: gdbln"],
  [0x00cf, "BLNON", "BLNON", "on/off blink flag", "vic20 kernal.src: blnon"],
  [0x00d0, "CRSW", "CRSW", "input vs get flag", "vic20 kernal.src: crsw"],
  [0x00d1, "PNT", "PNT", "pointer to row; 2 bytes", "vic20 kernal.src: pnt"],
  [0x00d3, "PNTR", "PNTR", "pointer to column", "vic20 kernal.src: pntr"],
  [0x00d4, "QTSW", "QTSW", "quote switch", "vic20 kernal.src: qtsw"],
  [0x00d5, "LNMX", "LNMX", "40/80 max positon", "vic20 kernal.src: lnmx"],
  [0x00d6, "TBLX", "TBLX", null, "vic20 kernal.src: tblx"],
  [0x00d7, "DATA", "DATA", null, "vic20 kernal.src: data"],
  [0x00d8, "INSRT", "INSRT", "insert mode flag", "vic20 kernal.src: insrt"],
  [0x00d9, "LDTB1", "LDTB1", "40/80 line flags; 25 bytes", "vic20 kernal.src: ldtb1"],
  [0x00f2, "LINTMP", "LINTMP", "temporary for line index", "vic20 kernal.src: lintmp"],
  [0x00f3, "USER", "USER", "screen editor color ip; 2 bytes", "vic20 kernal.src: user"],
  [0x00f5, "KEYTAB", "KEYTAB", "keyscan table indirect; 2 bytes", "vic20 kernal.src: keytab"],
  [0x00f7, "RIBUF", "RIBUF", "rs-232 input buffer pointer; 2 bytes", "vic20 kernal.src: ribuf"],
  [0x00f9, "ROBUF", "ROBUF", "rs-232 output buffer pointer; 2 bytes", "vic20 kernal.src: robuf"],
  [0x00fb, "FREKZP", "FREKZP", "free kernal zero page 9/24/80; 4 bytes", "vic20 kernal.src: frekzp"],
  [0x00ff, "LOFBUF", "LOFBUF", null, "vic20 basic.src: lofbuf"],
  [0x0100, "BAD", "BAD", "also: FBUFFR (basic.src)", "vic20 kernal.src: bad"],
  [0x0200, "BUF", "BUF", "basic/monitor buffer; 89 bytes", "vic20 kernal.src: buf"],
  [0x0259, "LAT", "LAT", "logical file numbers; 10 bytes", "vic20 kernal.src: lat"],
  [0x0263, "FAT", "FAT", "primary device numbers; 10 bytes", "vic20 kernal.src: fat"],
  [0x026d, "SAT", "SAT", "secondary addresses; 10 bytes", "vic20 kernal.src: sat"],
  [0x0277, "KEYD", "KEYD", "irq keyboard buffer; 10 bytes", "vic20 kernal.src: keyd"],
  [0x0281, "MEMSTR", "MEMSTR", "start of memory; 2 bytes", "vic20 kernal.src: memstr"],
  [0x0283, "MEMSIZ", "MEMSIZ", "top of memory; 2 bytes", "vic20 kernal.src: memsiz"],
  [0x0285, "TIMOUT", "TIMOUT", "ieee timeout flag", "vic20 kernal.src: timout"],
  [0x0286, "COLOR", "COLOR", "activ color nybble", "vic20 kernal.src: color"],
  [0x0287, "GDCOL", "GDCOL", "original color before cursor", "vic20 kernal.src: gdcol"],
  [0x0288, "HIBASE", "HIBASE", "base location of screen (top)", "vic20 kernal.src: hibase"],
  [0x0289, "XMAX", "XMAX", null, "vic20 kernal.src: xmax"],
  [0x028a, "RPTFLG", "RPTFLG", "key repeat flag", "vic20 kernal.src: rptflg"],
  [0x028b, "KOUNT", "KOUNT", null, "vic20 kernal.src: kount"],
  [0x028c, "DELAY", "DELAY", null, "vic20 kernal.src: delay"],
  [0x028d, "SHFLAG", "SHFLAG", "shift flag byte", "vic20 kernal.src: shflag"],
  [0x028e, "LSTSHF", "LSTSHF", "last shift pattern", "vic20 kernal.src: lstshf"],
  [0x028f, "KEYLOG", "KEYLOG", "indirect for keyboard table setup; 2 bytes", "vic20 kernal.src: keylog"],
  [0x0291, "MODE", "MODE", "0-pet mode, 1-cattacanna", "vic20 kernal.src: mode"],
  [0x0292, "AUTODN", "AUTODN", "auto scroll down flag(=0 on,<>0 off)", "vic20 kernal.src: autodn"],
  [0x0293, "M51CTR", "M51CTR", "6551 control register", "vic20 kernal.src: m51ctr"],
  [0x0294, "M51CDR", "M51CDR", "6551 command register", "vic20 kernal.src: m51cdr"],
  [0x0295, "M51AJB", "M51AJB", "non standard (bittime/2-100); 2 bytes", "vic20 kernal.src: m51ajb"],
  [0x0297, "RSSTAT", "RSSTAT", "rs-232 status register", "vic20 kernal.src: rsstat"],
  [0x0298, "BITNUM", "BITNUM", "number of bits to send (fast response)", "vic20 kernal.src: bitnum"],
  [0x0299, "BAUDOF", "BAUDOF", "baud rate full bit time (created by open); 2 bytes", "vic20 kernal.src: baudof"],
  [0x029b, "RIDBE", "RIDBE", "input buffer index to end", "vic20 kernal.src: ridbe"],
  [0x029c, "RIDBS", "RIDBS", "input buffer pointer to start", "vic20 kernal.src: ridbs"],
  [0x029d, "RODBS", "RODBS", "output buffer index to start", "vic20 kernal.src: rodbs"],
  [0x029e, "RODBE", "RODBE", "output buffer index to end", "vic20 kernal.src: rodbe"],
  [0x029f, "IRQTMP", "IRQTMP", "holds irq during tape ops; 2 bytes", "vic20 kernal.src: irqtmp"],
  [0x0300, "IERROR", "IERROR", "indirect error (output error in .x); 2 bytes", "vic20 basic.src: ierror"],
  [0x0302, "IMAIN", "IMAIN", "indirect main (system direct loop); 2 bytes", "vic20 basic.src: imain"],
  [0x0304, "ICRNCH", "ICRNCH", "indirect crunch (tokenization routine); 2 bytes", "vic20 basic.src: icrnch"],
  [0x0306, "IQPLOP", "IQPLOP", "indirect list (char list); 2 bytes", "vic20 basic.src: iqplop"],
  [0x0308, "IGONE", "IGONE", "indirect gone (char dispatch); 2 bytes", "vic20 basic.src: igone"],
  [0x030a, "IEVAL", "IEVAL", "indirect eval (symbol evaluation); 2 bytes", "vic20 basic.src: ieval"],
  [0x030c, "SAREG", "SAREG", ".a reg", "vic20 basic.src: sareg"],
  [0x030d, "SXREG", "SXREG", ".x reg", "vic20 basic.src: sxreg"],
  [0x030e, "SYREG", "SYREG", ".y reg", "vic20 basic.src: syreg"],
  [0x030f, "SPREG", "SPREG", ".p reg", "vic20 basic.src: spreg"],
  [0x0314, "CINV", "CINV", "irq ram vector; 2 bytes", "vic20 kernal.src: cinv"],
  [0x0316, "CBINV", "CBINV", "brk instr ram vector; 2 bytes", "vic20 kernal.src: cbinv"],
  [0x0318, "NMINV", "NMINV", "nmi ram vector; 2 bytes", "vic20 kernal.src: nminv"],
  [0x031a, "IOPEN", "IOPEN", "indirects for code; 2 bytes", "vic20 kernal.src: iopen"],
  [0x031c, "ICLOSE", "ICLOSE", "conforms to kernal spec 8/19/80; 2 bytes", "vic20 kernal.src: iclose"],
  [0x031e, "ICHKIN", "ICHKIN", "2 bytes", "vic20 kernal.src: ichkin"],
  [0x0320, "ICKOUT", "ICKOUT", "2 bytes", "vic20 kernal.src: ickout"],
  [0x0322, "ICLRCH", "ICLRCH", "2 bytes", "vic20 kernal.src: iclrch"],
  [0x0324, "IBASIN", "IBASIN", "2 bytes", "vic20 kernal.src: ibasin"],
  [0x0326, "IBSOUT", "IBSOUT", "2 bytes", "vic20 kernal.src: ibsout"],
  [0x0328, "ISTOP", "ISTOP", "2 bytes", "vic20 kernal.src: istop"],
  [0x032a, "IGETIN", "IGETIN", "2 bytes", "vic20 kernal.src: igetin"],
  [0x032c, "ICLALL", "ICLALL", "2 bytes", "vic20 kernal.src: iclall"],
  [0x032e, "USRCMD", "USRCMD", "2 bytes", "vic20 kernal.src: usrcmd"],
  [0x0330, "ILOAD", "ILOAD", "2 bytes", "vic20 kernal.src: iload"],
  [0x0332, "ISAVE", "ISAVE", "savesp; 2 bytes", "vic20 kernal.src: isave"],
  [0x033c, "TBUFFR", "TBUFFR", "cassette data buffer; 192 bytes", "vic20 kernal.src: tbuffr"],
  [0x1000, "VICSCN", "VICSCN", "vic screen; 512 bytes", "vic20 kernal.src: vicscn"],
  [0x9000, "VICREG", "VICREG", "vic registers; 16 bytes", "vic20 kernal.src: vicreg"],
  [0x9110, "D1ORB", "D1ORB", null, "vic20 kernal.src: d1orb"],
  [0x9111, "D1ORAH", "D1ORAH", null, "vic20 kernal.src: d1orah"],
  [0x9112, "D1DDRB", "D1DDRB", null, "vic20 kernal.src: d1ddrb"],
  [0x9113, "D1DDRA", "D1DDRA", null, "vic20 kernal.src: d1ddra"],
  [0x9114, "D1T1L", "D1T1L", null, "vic20 kernal.src: d1t1l"],
  [0x9115, "D1T1H", "D1T1H", null, "vic20 kernal.src: d1t1h"],
  [0x9116, "D1T1LL", "D1T1LL", null, "vic20 kernal.src: d1t1ll"],
  [0x9117, "D1T1LH", "D1T1LH", null, "vic20 kernal.src: d1t1lh"],
  [0x9118, "D1T2L", "D1T2L", null, "vic20 kernal.src: d1t2l"],
  [0x9119, "D1T2H", "D1T2H", null, "vic20 kernal.src: d1t2h"],
  [0x911a, "D1SR", "D1SR", null, "vic20 kernal.src: d1sr"],
  [0x911b, "D1ACR", "D1ACR", null, "vic20 kernal.src: d1acr"],
  [0x911c, "D1PCR", "D1PCR", null, "vic20 kernal.src: d1pcr"],
  [0x911d, "D1IFR", "D1IFR", null, "vic20 kernal.src: d1ifr"],
  [0x911e, "D1IER", "D1IER", null, "vic20 kernal.src: d1ier"],
  [0x911f, "D1ORA", "D1ORA", null, "vic20 kernal.src: d1ora"],
  [0x9120, "D2ORB", "D2ORB", "also: COLM", "vic20 kernal.src: d2orb"],
  [0x9121, "D2ORAH", "D2ORAH", "also: ROWS", "vic20 kernal.src: d2orah"],
  [0x9122, "D2DDRB", "D2DDRB", null, "vic20 kernal.src: d2ddrb"],
  [0x9123, "D2DDRA", "D2DDRA", null, "vic20 kernal.src: d2ddra"],
  [0x9124, "D2T1L", "D2T1L", null, "vic20 kernal.src: d2t1l"],
  [0x9125, "D2T1H", "D2T1H", null, "vic20 kernal.src: d2t1h"],
  [0x9126, "D2T1LL", "D2T1LL", null, "vic20 kernal.src: d2t1ll"],
  [0x9127, "D2T1LH", "D2T1LH", null, "vic20 kernal.src: d2t1lh"],
  [0x9128, "D2T2L", "D2T2L", null, "vic20 kernal.src: d2t2l"],
  [0x9129, "D2T2H", "D2T2H", null, "vic20 kernal.src: d2t2h"],
  [0x912a, "D2SR", "D2SR", null, "vic20 kernal.src: d2sr"],
  [0x912b, "D2ACR", "D2ACR", null, "vic20 kernal.src: d2acr"],
  [0x912c, "D2PCR", "D2PCR", null, "vic20 kernal.src: d2pcr"],
  [0x912d, "D2IFR", "D2IFR", null, "vic20 kernal.src: d2ifr"],
  [0x912e, "D2IER", "D2IER", null, "vic20 kernal.src: d2ier"],
  [0x912f, "D2ORA", "D2ORA", null, "vic20 kernal.src: d2ora"],
  [0x9400, "VICCOL", "VICCOL", "vic color nybbles; 512 bytes", "vic20 kernal.src: viccol"],
  [0xc00c, "STMDSP", "STMDSP", null, "vic20 basic.src: stmdsp"],
  [0xc052, "FUNDSP", "FUNDSP", null, "vic20 basic.src: fundsp"],
  [0xc058, "USRLOC", "USRLOC", null, "vic20 basic.src: usrloc"],
  [0xc080, "OPTAB", "OPTAB", null, "vic20 basic.src: optab"],
  [0xc095, "NEGTAB", "NEGTAB", null, "vic20 basic.src: negtab"],
  [0xc098, "NOTTAB", "NOTTAB", null, "vic20 basic.src: nottab"],
  [0xc09b, "PTDORL", "PTDORL", null, "vic20 basic.src: ptdorl"],
  [0xc09e, "RESLST", "RESLST", null, "vic20 basic.src: RESLST"],
  [0xc19e, "ERR01", "ERR01", null, "vic20 basic.src: ERR01"],
  [0xc1ac, "ERR02", "ERR02", null, "vic20 basic.src: ERR02"],
  [0xc1b5, "ERR03", "ERR03", null, "vic20 basic.src: ERR03"],
  [0xc1c2, "ERR04", "ERR04", null, "vic20 basic.src: ERR04"],
  [0xc1d0, "ERR05", "ERR05", null, "vic20 basic.src: ERR05"],
  [0xc1e2, "ERR06", "ERR06", null, "vic20 basic.src: ERR06"],
  [0xc1f0, "ERR07", "ERR07", null, "vic20 basic.src: ERR07"],
  [0xc1ff, "ERR08", "ERR08", null, "vic20 basic.src: ERR08"],
  [0xc210, "ERR09", "ERR09", null, "vic20 basic.src: ERR09"],
  [0xc225, "ERR10", "ERR10", null, "vic20 basic.src: ERR10"],
  [0xc235, "ERR11", "ERR11", null, "vic20 basic.src: ERR11"],
  [0xc23b, "ERR12", "ERR12", null, "vic20 basic.src: ERR12"],
  [0xc24f, "ERR13", "ERR13", null, "vic20 basic.src: ERR13"],
  [0xc25a, "ERR14", "ERR14", null, "vic20 basic.src: ERR14"],
  [0xc26a, "ERR15", "ERR15", null, "vic20 basic.src: ERR15"],
  [0xc272, "ERR16", "ERR16", null, "vic20 basic.src: ERR16"],
  [0xc27f, "ERR17", "ERR17", null, "vic20 basic.src: ERR17"],
  [0xc290, "ERR18", "ERR18", null, "vic20 basic.src: ERR18"],
  [0xc29d, "ERR19", "ERR19", null, "vic20 basic.src: ERR19"],
  [0xc2aa, "ERR20", "ERR20", null, "vic20 basic.src: ERR20"],
  [0xc2ba, "ERR21", "ERR21", null, "vic20 basic.src: ERR21"],
  [0xc2c8, "ERR22", "ERR22", null, "vic20 basic.src: ERR22"],
  [0xc2d5, "ERR23", "ERR23", null, "vic20 basic.src: ERR23"],
  [0xc2e4, "ERR24", "ERR24", null, "vic20 basic.src: ERR24"],
  [0xc2ed, "ERR25", "ERR25", null, "vic20 basic.src: ERR25"],
  [0xc300, "ERR26", "ERR26", null, "vic20 basic.src: ERR26"],
  [0xc30e, "ERR27", "ERR27", null, "vic20 basic.src: ERR27"],
  [0xc31e, "ERR28", "ERR28", null, "vic20 basic.src: ERR28"],
  [0xc324, "ERR29", "ERR29", null, "vic20 basic.src: ERR29"],
  [0xc328, "ERRTAB", "ERRTAB", null, "vic20 basic.src: errtab"],
  [0xc364, "OKMSG", "OKMSG", null, "vic20 basic.src: OKMSG"],
  [0xc369, "ERR", "ERR", "ADD A C/R FOR VIXEN SCREEN", "vic20 basic.src: ERR"],
  [0xc371, "INTXT", "INTXT", null, "vic20 basic.src: INTXT"],
  [0xc376, "REDDY", "REDDY", null, "vic20 basic.src: REDDY"],
  [0xc381, "BRKTXT", "BRKTXT", null, "vic20 basic.src: BRKTXT"],
  [0xc383, "ERR30", "ERR30", "SHIFTED SPACE", "vic20 basic.src: ERR30"],
  [0xc38a, "FNDFOR", "FNDFOR", null, "vic20 basic.src: fndfor"],
  [0xc3b8, "BLTU", "BLTU", null, "vic20 basic.src: bltu"],
  [0xc3bf, "BLTUC", "BLTUC", null, "vic20 basic.src: bltuc"],
  [0xc3fb, "GETSTK", "GETSTK", null, "vic20 basic.src: getstk"],
  [0xc408, "REASON", "REASON", null, "vic20 basic.src: reason"],
  [0xc435, "OMERR", "OMERR", null, "vic20 basic.src: omerr"],
  [0xc437, "ERROR", "ERROR", null, "vic20 basic.src: error"],
  [0xc43a, "NERROR", "NERROR", null, "vic20 basic.src: nerror"],
  [0xc44e, "ERRCRD", "ERRCRD", null, "vic20 basic.src: errcrd"],
  [0xc469, "ERRFIN", "ERRFIN", null, "vic20 basic.src: errfin"],
  [0xc474, "READY", "READY", null, "vic20 basic.src: ready"],
  [0xc480, "MAIN", "MAIN", null, "vic20 basic.src: main"],
  [0xc483, "NMAIN", "NMAIN", null, "vic20 basic.src: nmain"],
  [0xc52a, "FINI", "FINI", null, "vic20 basic.src: fini"],
  [0xc533, "LNKPRG", "LNKPRG", null, "vic20 basic.src: lnkprg"],
  [0xc560, "INLIN", "INLIN", null, "vic20 basic.src: inlin"],
  [0xc579, "CRUNCH", "CRUNCH", null, "vic20 basic.src: crunch"],
  [0xc57c, "NCRNCH", "NCRNCH", null, "vic20 basic.src: ncrnch"],
  [0xc5ee, "STRNG", "STRNG", null, "vic20 basic.src: strng"],
  [0xc613, "FNDLIN", "FNDLIN", null, "vic20 basic.src: fndlin"],
  [0xc617, "FNDLNC", "FNDLNC", null, "vic20 basic.src: fndlnc"],
  [0xc642, "SCRATH", "SCRATH", null, "vic20 basic.src: scrath"],
  [0xc644, "SCRTCH", "SCRTCH", null, "vic20 basic.src: scrtch"],
  [0xc659, "RUNC", "RUNC", null, "vic20 basic.src: runc"],
  [0xc65e, "CLEAR", "CLEAR", null, "vic20 basic.src: clear"],
  [0xc660, "CLEARC", "CLEARC", "moved for v2 orig for rs-232", "vic20 basic.src: clearc"],
  [0xc663, "CLEART", "CLEART", "entry for open & close memsiz changes", "vic20 basic.src: cleart"],
  [0xc677, "FLOAD", "FLOAD", null, "vic20 basic.src: fload"],
  [0xc67a, "STKINI", "STKINI", null, "vic20 basic.src: stkini"],
  [0xc68e, "STXTPT", "STXTPT", null, "vic20 basic.src: stxtpt"],
  [0xc69c, "LIST", "LIST", null, "vic20 basic.src: list"],
  [0xc71a, "NQPLOP", "NQPLOP", null, "vic20 basic.src: nqplop"],
  [0xc742, "FOR", "FOR", null, "vic20 basic.src: for"],
  [0xc78b, "LDFONE", "LDFONE", null, "vic20 basic.src: ldfone"],
  [0xc7ae, "NEWSTT", "NEWSTT", null, "vic20 basic.src: newstt"],
  [0xc7e1, "GONE", "GONE", null, "vic20 basic.src: gone"],
  [0xc7e4, "NGONE", "NGONE", null, "vic20 basic.src: ngone"],
  [0xc7e7, "NGONE1", "NGONE1", null, "vic20 basic.src: ngone1"],
  [0xc7ed, "GONE3", "GONE3", null, "vic20 basic.src: gone3"],
  [0xc7ef, "GONE2", "GONE2", null, "vic20 basic.src: gone2"],
  [0xc81d, "RESTOR", "RESTOR", null, "vic20 basic.src: restor"],
  [0xc827, "RESFIN", "RESFIN", null, "vic20 basic.src: resfin"],
  [0xc82c, "ISCNTC", "ISCNTC", null, "vic20 basic.src: iscntc"],
  [0xc82f, "STOP", "STOP", null, "vic20 basic.src: stop"],
  [0xc831, "END", "END", null, "vic20 basic.src: end"],
  [0xc841, "STPEND", "STPEND", null, "vic20 basic.src: stpend"],
  [0xc84b, "ENDCON", "ENDCON", null, "vic20 basic.src: endcon"],
  [0xc857, "CONT", "CONT", null, "vic20 basic.src: cont"],
  [0xc871, "RUN", "RUN", null, "vic20 basic.src: run"],
  [0xc883, "GOSUB", "GOSUB", null, "vic20 basic.src: gosub"],
  [0xc897, "RUNC2", "RUNC2", null, "vic20 basic.src: runc2"],
  [0xc8a0, "GOTO", "GOTO", null, "vic20 basic.src: goto"],
  [0xc8d2, "RETURN", "RETURN", null, "vic20 basic.src: return"],
  [0xc8f8, "DATA", "DATA", null, "vic20 basic.src: data"],
  [0xc8fb, "ADDON", "ADDON", null, "vic20 basic.src: addon"],
  [0xc906, "DATAN", "DATAN", null, "vic20 basic.src: datan"],
  [0xc909, "REMN", "REMN", null, "vic20 basic.src: remn"],
  [0xc928, "IF", "IF", null, "vic20 basic.src: if"],
  [0xc93b, "REM", "REM", null, "vic20 basic.src: rem"],
  [0xc94b, "ONGOTO", "ONGOTO", null, "vic20 basic.src: ongoto"],
  [0xc96b, "LINGET", "LINGET", null, "vic20 basic.src: linget"],
  [0xc971, "MORLIN", "MORLIN", null, "vic20 basic.src: morlin"],
  [0xc9a5, "LET", "LET", null, "vic20 basic.src: let"],
  [0xc9c2, "QINTGR", "QINTGR", null, "vic20 basic.src: qintgr"],
  [0xc9da, "INPCOM", "INPCOM", null, "vic20 basic.src: inpcom"],
  [0xca1d, "TIMNUM", "TIMNUM", null, "vic20 basic.src: timnum"],
  [0xca68, "COPYC", "COPYC", null, "vic20 basic.src: copyc"],
  [0xca80, "PRINTN", "PRINTN", null, "vic20 basic.src: printn"],
  [0xca86, "CMD", "CMD", null, "vic20 basic.src: cmd"],
  [0xcaa0, "PRINT", "PRINT", null, "vic20 basic.src: print"],
  [0xcaa2, "PRINTC", "PRINTC", null, "vic20 basic.src: printc"],
  [0xcaca, "FININL", "FININL", null, "vic20 basic.src: fininl"],
  [0xcad7, "CRDO", "CRDO", null, "vic20 basic.src: crdo"],
  [0xcae5, "CRFIN", "CRFIN", null, "vic20 basic.src: crfin"],
  [0xcb1e, "STROUT", "STROUT", null, "vic20 basic.src: strout"],
  [0xcb21, "STRPRT", "STRPRT", null, "vic20 basic.src: strprt"],
  [0xcb28, "STRPR2", "STRPR2", null, "vic20 basic.src: strpr2"],
  [0xcb3b, "OUTSPC", "OUTSPC", null, "vic20 basic.src: outspc"],
  [0xcb45, "OUTQST", "OUTQST", null, "vic20 basic.src: outqst"],
  [0xcb47, "OUTDO", "OUTDO", null, "vic20 basic.src: outdo"],
  [0xcb4a, "OUTRTS", "OUTRTS", null, "vic20 basic.src: outrts"],
  [0xcb4d, "TRMNOK", "TRMNOK", null, "vic20 basic.src: trmnok"],
  [0xcb7b, "GET", "GET", null, "vic20 basic.src: get"],
  [0xcba5, "INPUTN", "INPUTN", null, "vic20 basic.src: inputn"],
  [0xcbb5, "IODONE", "IODONE", null, "vic20 basic.src: iodone"],
  [0xcbbf, "INPUT", "INPUT", null, "vic20 basic.src: input"],
  [0xcbce, "NOTQTI", "NOTQTI", null, "vic20 basic.src: notqti"],
  [0xcbf9, "QINLIN", "QINLIN", null, "vic20 basic.src: qinlin"],
  [0xcc06, "READ", "READ", null, "vic20 basic.src: read"],
  [0xcc0f, "INPCO1", "INPCO1", null, "vic20 basic.src: inpco1"],
  [0xcc15, "INLOOP", "INLOOP", null, "vic20 basic.src: inloop"],
  [0xcc51, "DATBK1", "DATBK1", null, "vic20 basic.src: datbk1"],
  [0xcc91, "STRDN2", "STRDN2", null, "vic20 basic.src: strdn2"],
  [0xccfc, "EXIGNT", "EXIGNT", null, "vic20 basic.src: EXIGNT"],
  [0xcd0c, "TRYAGN", "TRYAGN", null, "vic20 basic.src: TRYAGN"],
  [0xcd1e, "NEXT", "NEXT", null, "vic20 basic.src: next"],
  [0xcd24, "GETFOR", "GETFOR", null, "vic20 basic.src: getfor"],
  [0xcd8a, "FRMNUM", "FRMNUM", null, "vic20 basic.src: frmnum"],
  [0xcd8d, "CHKNUM", "CHKNUM", null, "vic20 basic.src: chknum"],
  [0xcd8f, "CHKSTR", "CHKSTR", null, "vic20 basic.src: chkstr"],
  [0xcd90, "CHKVAL", "CHKVAL", null, "vic20 basic.src: chkval"],
  [0xcd9b, "ERRGO4", "ERRGO4", null, "vic20 basic.src: errgo4"],
  [0xcd9e, "FRMEVL", "FRMEVL", null, "vic20 basic.src: frmevl"],
  [0xcda9, "LPOPER", "LPOPER", null, "vic20 basic.src: lpoper"],
  [0xcdb8, "TSTOP", "TSTOP", null, "vic20 basic.src: tstop"],
  [0xcdbb, "LOPREL", "LOPREL", null, "vic20 basic.src: loprel"],
  [0xcdfa, "NEGPRC", "NEGPRC", null, "vic20 basic.src: negprc"],
  [0xce20, "DOPRE1", "DOPRE1", null, "vic20 basic.src: dopre1"],
  [0xce33, "PUSHF1", "PUSHF1", null, "vic20 basic.src: pushf1"],
  [0xce38, "PUSHF", "PUSHF", null, "vic20 basic.src: pushf"],
  [0xce43, "FORPSH", "FORPSH", null, "vic20 basic.src: forpsh"],
  [0xce82, "UNPRTS", "UNPRTS", null, "vic20 basic.src: unprts"],
  [0xce83, "EVAL", "EVAL", null, "vic20 basic.src: eval"],
  [0xce86, "NEVAL", "NEVAL", null, "vic20 basic.src: neval"],
  [0xcea8, "PIVAL", "PIVAL", null, "vic20 basic.src: pival"],
  [0xcebd, "STRTXT", "STRTXT", null, "vic20 basic.src: strtxt"],
  [0xced4, "NOTOP", "NOTOP", null, "vic20 basic.src: notop"],
  [0xcef1, "PARCHK", "PARCHK", null, "vic20 basic.src: parchk"],
  [0xcef7, "CHKCLS", "CHKCLS", null, "vic20 basic.src: chkcls"],
  [0xcefa, "CHKOPN", "CHKOPN", null, "vic20 basic.src: chkopn"],
  [0xcefd, "CHKCOM", "CHKCOM", null, "vic20 basic.src: chkcom"],
  [0xceff, "SYNCHR", "SYNCHR", null, "vic20 basic.src: synchr"],
  [0xcf08, "SNERR", "SNERR", null, "vic20 basic.src: snerr"],
  [0xcf14, "TSTROM", "TSTROM", null, "vic20 basic.src: tstrom"],
  [0xcf28, "ISVAR", "ISVAR", null, "vic20 basic.src: isvar"],
  [0xcf2b, "ISVRET", "ISVRET", null, "vic20 basic.src: isvret"],
  [0xcf84, "GETTIM", "GETTIM", null, "vic20 basic.src: gettim"],
  [0xcfa7, "ISFUN", "ISFUN", null, "vic20 basic.src: isfun"],
  [0xcfd6, "FINGO", "FINGO", null, "vic20 basic.src: fingo"],
  [0xcfe6, "OROP", "OROP", null, "vic20 basic.src: orop"],
  [0xcfe9, "ANDOP", "ANDOP", null, "vic20 basic.src: andop"],
  [0xd016, "DOREL", "DOREL", null, "vic20 basic.src: dorel"],
  [0xd061, "QCOMP", "QCOMP", null, "vic20 basic.src: qcomp"],
  [0xd081, "DIM", "DIM", null, "vic20 basic.src: dim"],
  [0xd08b, "PTRGET", "PTRGET", null, "vic20 basic.src: ptrget"],
  [0xd090, "PTRGT1", "PTRGT1", null, "vic20 basic.src: ptrgt1"],
  [0xd092, "PTRGT2", "PTRGT2", null, "vic20 basic.src: ptrgt2"],
  [0xd113, "ISLETC", "ISLETC", null, "vic20 basic.src: isletc"],
  [0xd194, "FMAPTR", "FMAPTR", null, "vic20 basic.src: fmaptr"],
  [0xd1a5, "N32768", "N32768", null, "vic20 basic.src: n32768"],
  [0xd1aa, "FLPINT", "FLPINT", null, "vic20 basic.src: flpint"],
  [0xd1b2, "INTIDX", "INTIDX", null, "vic20 basic.src: intidx"],
  [0xd1b8, "POSINT", "POSINT", null, "vic20 basic.src: posint"],
  [0xd1bf, "AYINT", "AYINT", null, "vic20 basic.src: ayint"],
  [0xd1d1, "ISARY", "ISARY", null, "vic20 basic.src: isary"],
  [0xd245, "BSERR", "BSERR", null, "vic20 basic.src: bserr"],
  [0xd248, "FCERR", "FCERR", null, "vic20 basic.src: fcerr"],
  [0xd2ea, "GETDEF", "GETDEF", null, "vic20 basic.src: getdef"],
  [0xd308, "BSERR7", "BSERR7", null, "vic20 basic.src: bserr7"],
  [0xd34c, "UMULT", "UMULT", null, "vic20 basic.src: umult"],
  [0xd355, "UMULTD", "UMULTD", null, "vic20 basic.src: umultd"],
  [0xd37c, "UMLRTS", "UMLRTS", null, "vic20 basic.src: umlrts"],
  [0xd37d, "FRE", "FRE", null, "vic20 basic.src: fre"],
  [0xd391, "GIVAYF", "GIVAYF", null, "vic20 basic.src: givayf"],
  [0xd39e, "POS", "POS", null, "vic20 basic.src: pos"],
  [0xd3a2, "SNGFLT", "SNGFLT", null, "vic20 basic.src: sngflt"],
  [0xd3a6, "ERRDIR", "ERRDIR", null, "vic20 basic.src: errdir"],
  [0xd3b3, "DEF", "DEF", null, "vic20 basic.src: def"],
  [0xd3e1, "GETFNM", "GETFNM", null, "vic20 basic.src: getfnm"],
  [0xd3f4, "FNDOER", "FNDOER", null, "vic20 basic.src: fndoer"],
  [0xd44f, "DEFFIN", "DEFFIN", null, "vic20 basic.src: deffin"],
  [0xd465, "STRD", "STRD", null, "vic20 basic.src: strd"],
  [0xd46f, "TIMSTR", "TIMSTR", null, "vic20 basic.src: timstr"],
  [0xd475, "STRINI", "STRINI", null, "vic20 basic.src: strini"],
  [0xd47d, "STRSPA", "STRSPA", null, "vic20 basic.src: strspa"],
  [0xd487, "STRLIT", "STRLIT", null, "vic20 basic.src: strlit"],
  [0xd48d, "STRLT2", "STRLT2", null, "vic20 basic.src: strlt2"],
  [0xd4ca, "PUTNEW", "PUTNEW", null, "vic20 basic.src: putnew"],
  [0xd4f4, "GETSPA", "GETSPA", null, "vic20 basic.src: getspa"],
  [0xd526, "GARBA2", "GARBA2", null, "vic20 basic.src: garba2"],
  [0xd52a, "FNDVAR", "FNDVAR", null, "vic20 basic.src: fndvar"],
  [0xd5bd, "DVARS", "DVARS", null, "vic20 basic.src: dvars"],
  [0xd5c7, "DVAR", "DVAR", null, "vic20 basic.src: dvar"],
  [0xd606, "GRBPAS", "GRBPAS", null, "vic20 basic.src: grbpas"],
  [0xd63d, "CAT", "CAT", null, "vic20 basic.src: cat"],
  [0xd67a, "MOVINS", "MOVINS", null, "vic20 basic.src: movins"],
  [0xd688, "MOVSTR", "MOVSTR", null, "vic20 basic.src: movstr"],
  [0xd68c, "MOVDO", "MOVDO", null, "vic20 basic.src: movdo"],
  [0xd6a3, "FRESTR", "FRESTR", null, "vic20 basic.src: frestr"],
  [0xd6a6, "FREFAC", "FREFAC", null, "vic20 basic.src: frefac"],
  [0xd6aa, "FRETMP", "FRETMP", null, "vic20 basic.src: fretmp"],
  [0xd6db, "FRETMS", "FRETMS", null, "vic20 basic.src: fretms"],
  [0xd6ec, "CHRD", "CHRD", null, "vic20 basic.src: chrd"],
  [0xd700, "LEFTD", "LEFTD", null, "vic20 basic.src: leftd"],
  [0xd706, "RLEFT", "RLEFT", null, "vic20 basic.src: rleft"],
  [0xd72c, "RIGHTD", "RIGHTD", null, "vic20 basic.src: rightd"],
  [0xd737, "MIDD", "MIDD", null, "vic20 basic.src: midd"],
  [0xd761, "PREAM", "PREAM", null, "vic20 basic.src: pream"],
  [0xd77c, "LEN", "LEN", null, "vic20 basic.src: len"],
  [0xd782, "LEN1", "LEN1", null, "vic20 basic.src: len1"],
  [0xd78b, "ASC", "ASC", null, "vic20 basic.src: asc"],
  [0xd79b, "GTBYTC", "GTBYTC", null, "vic20 basic.src: gtbytc"],
  [0xd79e, "GETBYT", "GETBYT", null, "vic20 basic.src: getbyt"],
  [0xd7a1, "CONINT", "CONINT", null, "vic20 basic.src: conint"],
  [0xd7ad, "VAL", "VAL", null, "vic20 basic.src: val"],
  [0xd7e2, "ST2TXT", "ST2TXT", null, "vic20 basic.src: st2txt"],
  [0xd7ea, "VALRTS", "VALRTS", null, "vic20 basic.src: valrts"],
  [0xd7eb, "GETNUM", "GETNUM", null, "vic20 basic.src: getnum"],
  [0xd7f1, "COMBYT", "COMBYT", null, "vic20 basic.src: combyt"],
  [0xd7f7, "GETADR", "GETADR", null, "vic20 basic.src: getadr"],
  [0xd80d, "PEEK", "PEEK", null, "vic20 basic.src: peek"],
  [0xd818, "GETCON", "GETCON", null, "vic20 basic.src: getcon"],
  [0xd81b, "DOSGFL", "DOSGFL", null, "vic20 basic.src: dosgfl"],
  [0xd824, "POKE", "POKE", null, "vic20 basic.src: poke"],
  [0xd82d, "FNWAIT", "FNWAIT", null, "vic20 basic.src: fnwait"],
  [0xd849, "FADDH", "FADDH", null, "vic20 basic.src: faddh"],
  [0xd850, "FSUB", "FSUB", null, "vic20 basic.src: fsub"],
  [0xd853, "FSUBT", "FSUBT", null, "vic20 basic.src: fsubt"],
  [0xd867, "FADD", "FADD", null, "vic20 basic.src: fadd"],
  [0xd86a, "FADDT", "FADDT", null, "vic20 basic.src: faddt"],
  [0xd877, "FADDC", "FADDC", null, "vic20 basic.src: faddc"],
  [0xd8d2, "FADFLT", "FADFLT", null, "vic20 basic.src: fadflt"],
  [0xd8d7, "NORMAL", "NORMAL", null, "vic20 basic.src: normal"],
  [0xd8f7, "ZEROFC", "ZEROFC", null, "vic20 basic.src: zerofc"],
  [0xd8f9, "ZEROF1", "ZEROF1", null, "vic20 basic.src: zerof1"],
  [0xd8fb, "ZEROML", "ZEROML", null, "vic20 basic.src: zeroml"],
  [0xd936, "SQUEEZ", "SQUEEZ", null, "vic20 basic.src: squeez"],
  [0xd938, "RNDSHF", "RNDSHF", null, "vic20 basic.src: rndshf"],
  [0xd947, "NEGFAC", "NEGFAC", null, "vic20 basic.src: negfac"],
  [0xd94d, "NEGFCH", "NEGFCH", null, "vic20 basic.src: negfch"],
  [0xd96f, "INCFAC", "INCFAC", null, "vic20 basic.src: incfac"],
  [0xd97e, "OVERR", "OVERR", null, "vic20 basic.src: overr"],
  [0xd983, "MULSHF", "MULSHF", null, "vic20 basic.src: mulshf"],
  [0xd999, "SHIFTR", "SHIFTR", null, "vic20 basic.src: shiftr"],
  [0xd9b0, "ROLSHF", "ROLSHF", null, "vic20 basic.src: rolshf"],
  [0xd9bc, "FONE", "FONE", null, "vic20 basic.src: fone"],
  [0xd9c1, "LOGCN2", "LOGCN2", null, "vic20 basic.src: logcn2"],
  [0xd9d6, "SQR05", "SQR05", null, "vic20 basic.src: sqr05"],
  [0xd9db, "SQR20", "SQR20", null, "vic20 basic.src: sqr20"],
  [0xd9e0, "NEGHLF", "NEGHLF", null, "vic20 basic.src: neghlf"],
  [0xd9e5, "LOG2", "LOG2", null, "vic20 basic.src: log2"],
  [0xd9ea, "LOG", "LOG", null, "vic20 basic.src: log"],
  [0xda28, "FMULT", "FMULT", null, "vic20 basic.src: fmult"],
  [0xda2b, "FMULTT", "FMULTT", null, "vic20 basic.src: fmultt"],
  [0xda59, "MLTPLY", "MLTPLY", null, "vic20 basic.src: mltply"],
  [0xda5e, "MLTPL1", "MLTPL1", null, "vic20 basic.src: mltpl1"],
  [0xda8b, "MULTRT", "MULTRT", null, "vic20 basic.src: multrt"],
  [0xda8c, "CONUPK", "CONUPK", null, "vic20 basic.src: conupk"],
  [0xdab7, "MULDIV", "MULDIV", null, "vic20 basic.src: muldiv"],
  [0xdab9, "MLDEXP", "MLDEXP", null, "vic20 basic.src: mldexp"],
  [0xdad4, "MLDVEX", "MLDVEX", null, "vic20 basic.src: mldvex"],
  [0xdae2, "MUL10", "MUL10", null, "vic20 basic.src: mul10"],
  [0xdaed, "FINML6", "FINML6", null, "vic20 basic.src: finml6"],
  [0xdaf9, "TENC", "TENC", null, "vic20 basic.src: tenc"],
  [0xdafe, "DIV10", "DIV10", null, "vic20 basic.src: div10"],
  [0xdb07, "FDIVF", "FDIVF", null, "vic20 basic.src: fdivf"],
  [0xdb0f, "FDIV", "FDIV", null, "vic20 basic.src: fdiv"],
  [0xdb12, "FDIVT", "FDIVT", null, "vic20 basic.src: fdivt"],
  [0xdb4f, "SHFARG", "SHFARG", null, "vic20 basic.src: shfarg"],
  [0xdb8f, "MOVFR", "MOVFR", null, "vic20 basic.src: movfr"],
  [0xdba2, "MOVFM", "MOVFM", null, "vic20 basic.src: movfm"],
  [0xdbc7, "MOV2F", "MOV2F", null, "vic20 basic.src: mov2f"],
  [0xdbca, "MOV1F", "MOV1F", null, "vic20 basic.src: mov1f"],
  [0xdbd0, "MOVVF", "MOVVF", null, "vic20 basic.src: movvf"],
  [0xdbd4, "MOVMF", "MOVMF", null, "vic20 basic.src: movmf"],
  [0xdbfc, "MOVFA", "MOVFA", null, "vic20 basic.src: movfa"],
  [0xdbfe, "MOVFA1", "MOVFA1", null, "vic20 basic.src: movfa1"],
  [0xdc0c, "MOVAF", "MOVAF", null, "vic20 basic.src: movaf"],
  [0xdc0f, "MOVEF", "MOVEF", null, "vic20 basic.src: movef"],
  [0xdc1b, "ROUND", "ROUND", null, "vic20 basic.src: round"],
  [0xdc23, "INCRND", "INCRND", null, "vic20 basic.src: incrnd"],
  [0xdc2b, "SIGN", "SIGN", null, "vic20 basic.src: sign"],
  [0xdc31, "FCOMPS", "FCOMPS", null, "vic20 basic.src: fcomps"],
  [0xdc39, "SGN", "SGN", null, "vic20 basic.src: sgn"],
  [0xdc3c, "FLOAT", "FLOAT", null, "vic20 basic.src: float"],
  [0xdc44, "FLOATS", "FLOATS", null, "vic20 basic.src: floats"],
  [0xdc49, "FLOATC", "FLOATC", null, "vic20 basic.src: floatc"],
  [0xdc4f, "FLOATB", "FLOATB", null, "vic20 basic.src: floatb"],
  [0xdc58, "ABS", "ABS", null, "vic20 basic.src: abs"],
  [0xdc5b, "FCOMP", "FCOMP", null, "vic20 basic.src: fcomp"],
  [0xdc5d, "FCOMPN", "FCOMPN", null, "vic20 basic.src: fcompn"],
  [0xdc9b, "QINT", "QINT", null, "vic20 basic.src: qint"],
  [0xdccc, "INT", "INT", null, "vic20 basic.src: int"],
  [0xdcf3, "FIN", "FIN", null, "vic20 basic.src: fin"],
  [0xdd0a, "FINC", "FINC", null, "vic20 basic.src: finc"],
  [0xdd30, "FINEC", "FINEC", null, "vic20 basic.src: finec"],
  [0xdd49, "FINE1", "FINE1", null, "vic20 basic.src: fine1"],
  [0xdd7e, "FINLOG", "FINLOG", null, "vic20 basic.src: finlog"],
  [0xddb3, "N0999", "N0999", null, "vic20 basic.src: n0999"],
  [0xddb8, "N9999", "N9999", null, "vic20 basic.src: n9999"],
  [0xddbd, "NMIL", "NMIL", null, "vic20 basic.src: nmil"],
  [0xddc2, "INPRT", "INPRT", null, "vic20 basic.src: inprt"],
  [0xddcd, "LINPRT", "LINPRT", null, "vic20 basic.src: linprt"],
  [0xddda, "STROU2", "STROU2", null, "vic20 basic.src: strou2"],
  [0xdddd, "FOUT", "FOUT", null, "vic20 basic.src: fout"],
  [0xdddf, "FOUTC", "FOUTC", null, "vic20 basic.src: foutc"],
  [0xde68, "FOUTIM", "FOUTIM", null, "vic20 basic.src: foutim"],
  [0xdf04, "FOUT19", "FOUT19", null, "vic20 basic.src: fout19"],
  [0xdf11, "FHALF", "FHALF", null, "vic20 basic.src: fhalf"],
  [0xdf13, "ZERO", "ZERO", null, "vic20 basic.src: zero"],
  [0xdf16, "FOUTBL", "FOUTBL", null, "vic20 basic.src: foutbl"],
  [0xdf3a, "FDCEND", "FDCEND", null, "vic20 basic.src: fdcend"],
  [0xdf52, "TIMEND", "TIMEND", null, "vic20 basic.src: timend"],
  [0xdf53, "PATCHS", "PATCHS", "patch area; 30 bytes", "vic20 basic.src: patchs"],
  [0xdf71, "SQR", "SQR", null, "vic20 basic.src: sqr"],
  [0xdf7b, "FPWRT", "FPWRT", null, "vic20 basic.src: fpwrt"],
  [0xdfb4, "NEGOP", "NEGOP", null, "vic20 basic.src: negop"],
  [0xdfbf, "LOGEB2", "LOGEB2", null, "vic20 basic.src: logeb2"],
  [0xdfc4, "EXPCON", "EXPCON", null, "vic20 basic.src: expcon"],
  [0xdfed, "EXP", "EXP", null, "vic20 basic.src: exp"],
  [0xe040, "POLYX", "POLYX", null, "vic20 basic.src: polyx"],
  [0xe056, "POLY", "POLY", null, "vic20 basic.src: poly"],
  [0xe05a, "POLY1", "POLY1", null, "vic20 basic.src: poly1"],
  [0xe08a, "RMULC", "RMULC", null, "vic20 basic.src: rmulc"],
  [0xe08f, "RADDC", "RADDC", null, "vic20 basic.src: raddc"],
  [0xe094, "RND", "RND", null, "vic20 basic.src: rnd"],
  [0xe0e0, "STRNEX", "STRNEX", null, "vic20 basic.src: strnex"],
  [0xe0f3, "GMOVMF", "GMOVMF", null, "vic20 basic.src: gmovmf"],
  [0xe0f6, "EREXIT", "EREXIT", "check for special case", "vic20 basic.src: erexit"],
  [0xe109, "OUTCH", "OUTCH", null, "vic20 basic.src: outch"],
  [0xe10f, "INCHR", "INCHR", null, "vic20 basic.src: inchr"],
  [0xe115, "COOUT", "COOUT", null, "vic20 basic.src: coout"],
  [0xe11b, "COIN", "COIN", null, "vic20 basic.src: coin"],
  [0xe121, "CGETL", "CGETL", null, "vic20 basic.src: cgetl"],
  [0xe127, "CSYS", "CSYS", "eval formula", "vic20 basic.src: csys"],
  [0xe153, "CSAVE", "CSAVE", "parse parms", "vic20 basic.src: csave"],
  [0xe162, "CVERF", "CVERF", "verify flag", "vic20 basic.src: cverf"],
  [0xe165, "CLOAD", "CLOAD", "load flag", "vic20 basic.src: cload"],
  [0xe16c, "CLD10", "CLD10", null, "vic20 basic.src: cld10"],
  [0xe1bb, "COPEN", "COPEN", "parse statement", "vic20 basic.src: copen"],
  [0xe1c4, "CCLOS", "CCLOS", "parse statement", "vic20 basic.src: cclos"],
  [0xe1d1, "PLSV", "PLSV", null, "vic20 basic.src: plsv"],
  [0xe1fd, "PLSV7", "PLSV7", null, "vic20 basic.src: plsv7"],
  [0xe203, "PAOC20", "PAOC20", null, "vic20 basic.src: paoc20"],
  [0xe20b, "PAOC30", "PAOC30", "check comma", "vic20 basic.src: paoc30"],
  [0xe20e, "PAOC32", "PAOC32", "get current", "vic20 basic.src: paoc32"],
  [0xe213, "PAOC40", "PAOC40", "bad...end of line", "vic20 basic.src: paoc40"],
  [0xe216, "PAOC", "PAOC", null, "vic20 basic.src: paoc"],
  [0xe24e, "PAOC7", "PAOC7", null, "vic20 basic.src: paoc7"],
  [0xe254, "PAOC15", "PAOC15", null, "vic20 basic.src: paoc15"],
  [0xe261, "COS", "COS", null, "vic20 basic.src: cos"],
  [0xe268, "SIN", "SIN", null, "vic20 basic.src: sin"],
  [0xe29a, "SIN1", "SIN1", null, "vic20 basic.src: sin1"],
  [0xe2b1, "TAN", "TAN", null, "vic20 basic.src: tan"],
  [0xe2d9, "COSC", "COSC", null, "vic20 basic.src: cosc"],
  [0xe2dd, "PI2", "PI2", null, "vic20 basic.src: pi2"],
  [0xe2e2, "TWOPI", "TWOPI", null, "vic20 basic.src: twopi"],
  [0xe2e7, "FR4", "FR4", null, "vic20 basic.src: fr4"],
  [0xe2ec, "SINCON", "SINCON", null, "vic20 basic.src: sincon"],
  [0xe30b, "ATN", "ATN", null, "vic20 basic.src: atn"],
  [0xe33b, "ATNCON", "ATNCON", null, "vic20 basic.src: atncon"],
  [0xe378, "INIT", "INIT", "go init vectors", "vic20 basic.src: init"],
  [0xe387, "INITAT", "INITAT", null, "vic20 basic.src: initat"],
  [0xe3a4, "INITCZ", "INITCZ", null, "vic20 basic.src: initcz"],
  [0xe3f0, "USEDEF", "USEDEF", null, "vic20 basic.src: usedef"],
  [0xe404, "INITMS", "INITMS", null, "vic20 basic.src: initms"],
  [0xe429, "WORDS", "WORDS", null, "vic20 basic.src: words"],
  [0xe436, "FREMES", "FREMES", null, "vic20 basic.src: fremes"],
  [0xe44f, "BVTRS", "BVTRS", null, "vic20 basic.src: bvtrs"],
  [0xe45b, "INITV", "INITV", "init vectors", "vic20 basic.src: initv"],
  [0xe467, "PANIC", "PANIC", "warm start basic...", "vic20 basic.src: panic"],
  [0xe475, "CHKE0", "CHKE0", null, "vic20 basic.src: chke0"],
  [0xe476, "PLINK", "PLINK", "go link the loaded program", "vic20 basic.src: plink"],
  [0xe4a0, "DATAHI", "DATAHI", "set data line high (inverted)", "vic20 kernal.src: datahi"],
  [0xe4a9, "DATALO", "DATALO", "set data line low (inverted)", "vic20 kernal.src: datalo"],
  [0xe4b2, "DEBPIA", "DEBPIA", "debpunce the pia", "vic20 kernal.src: debpia"],
  [0xe4bc, "PATCH2", "PATCH2", "save sa in .x", "vic20 kernal.src: patch2"],
  [0xe4c1, "PATCH3", "PATCH3", "find out how to load", "vic20 kernal.src: patch3"],
  [0xe4cf, "STPTCH", "STPTCH", null, "vic20 kernal.src: stptch"],
  [0xe500, "IOBASE", "IOBASE", null, "vic20 kernal.src: iobase"],
  [0xe505, "SCRORG", "SCRORG", null, "vic20 kernal.src: scrorg"],
  [0xe50a, "PLOT", "PLOT", null, "vic20 kernal.src: plot"],
  [0xe518, "CINT", "CINT", null, "vic20 kernal.src: cint"],
  [0xe55f, "CLSR", "CLSR", "fill hi byte ptr table", "vic20 kernal.src: clsr"],
  [0xe581, "NXTD", "NXTD", null, "vic20 kernal.src: nxtd"],
  [0xe587, "STUPT", "STUPT", null, "vic20 kernal.src: stupt"],
  [0xe5b5, "VPAN", "VPAN", "fix vic screen", "vic20 kernal.src: vpan"],
  [0xe5bb, "PANIC", "PANIC", "reset default i/o", "vic20 kernal.src: panic"],
  [0xe5c3, "INITV", "INITV", null, "vic20 kernal.src: initv"],
  [0xe5cf, "LP2", "LP2", null, "vic20 kernal.src: lp2"],
  [0xe64f, "LOOP5", "LOOP5", null, "vic20 kernal.src: loop5"],
  [0xe672, "NOTONE", "NOTONE", null, "vic20 kernal.src: notone"],
  [0xe674, "LOP51", "LOP51", null, "vic20 kernal.src: lop51"],
  [0xe6b8, "QTSWC", "QTSWC", null, "vic20 kernal.src: qtswc"],
  [0xe6c5, "NXT33", "NXT33", null, "vic20 kernal.src: nxt33"],
  [0xe6c7, "NXT3", "NXT3", null, "vic20 kernal.src: nxt3"],
  [0xe6cb, "NC3", "NC3", null, "vic20 kernal.src: nc3"],
  [0xe6dc, "LOOP2", "LOOP2", null, "vic20 kernal.src: loop2"],
  [0xe6ea, "WLOGIC", "WLOGIC", null, "vic20 kernal.src: wlogic"],
  [0xe70e, "WLOG30", "WLOG30", "wrap the line", "vic20 kernal.src: wlog30"],
  [0xe715, "PATOUT", "PATOUT", "patch re-entry point", "vic20 kernal.src: patout"],
  [0xe719, "FINDST", "FINDST", null, "vic20 kernal.src: findst"],
  [0xe72d, "BKLN", "BKLN", null, "vic20 kernal.src: bkln"],
  [0xe742, "PRT", "PRT", null, "vic20 kernal.src: prt"],
  [0xe78b, "BK1", "BK1", "fix color ptrs", "vic20 kernal.src: bk1"],
  [0xe79f, "BK2", "BK2", null, "vic20 kernal.src: bk2"],
  [0xe7ae, "CNC3", "CNC3", null, "vic20 kernal.src: cnc3"],
  [0xe800, "NXTX", "NXTX", null, "vic20 kernal.src: nxtx"],
  [0xe815, "KEEPIT", "KEEPIT", null, "vic20 kernal.src: keepit"],
  [0xe823, "NXTXA", "NXTXA", null, "vic20 kernal.src: nxtxa"],
  [0xe8c3, "NXLN", "NXLN", null, "vic20 kernal.src: nxln"],
  [0xe8d8, "NXT1", "NXT1", null, "vic20 kernal.src: nxt1"],
  [0xe8e5, "JPL5", "JPL5", null, "vic20 kernal.src: jpl5"],
  [0xe8e8, "CHKBAK", "CHKBAK", null, "vic20 kernal.src: chkbak"],
  [0xe8fa, "CHKDWN", "CHKDWN", null, "vic20 kernal.src: chkdwn"],
  [0xe912, "CHKCOL", "CHKCOL", null, "vic20 kernal.src: chkcol"],
  [0xe921, "COLTAB", "COLTAB", null, "vic20 kernal.src: coltab"],
  [0xe953, "UNKAT", "UNKAT", null, "vic20 kernal.src: unkat"],
  [0xe975, "SCROL", "SCROL", null, "vic20 kernal.src: scrol"],
  [0xe9ee, "NEWLIN", "NEWLIN", null, "vic20 kernal.src: newlin"],
  [0xe9f0, "BMT1", "BMT1", null, "vic20 kernal.src: bmt1"],
  [0xea56, "SCRLIN", "SCRLIN", null, "vic20 kernal.src: scrlin"],
  [0xea6e, "TOFROM", "TOFROM", null, "vic20 kernal.src: tofrom"],
  [0xea7e, "SETPNT", "SETPNT", null, "vic20 kernal.src: setpnt"],
  [0xea8d, "CLRLN", "CLRLN", null, "vic20 kernal.src: clrln"],
  [0xeaa1, "DSPP", "DSPP", "save char", "vic20 kernal.src: dspp"],
  [0xeaaa, "DSPP2", "DSPP2", "get column", "vic20 kernal.src: dspp2"],
  [0xeab2, "SCOLOR", "SCOLOR", "generate color ptr", "vic20 kernal.src: scolor"],
  [0xeabf, "KEY", "KEY", "update jiffy clock", "vic20 kernal.src: key"],
  [0xeacc, "REPDO", "REPDO", null, "vic20 kernal.src: repdo"],
  [0xeb15, "KPREND", "KPREND", "clear interupt flag", "vic20 kernal.src: kprend"],
  [0xeb1e, "SCNKEY", "SCNKEY", null, "vic20 kernal.src: scnkey"],
  [0xeb74, "REKEY", "REKEY", "get key index", "vic20 kernal.src: rekey"],
  [0xebc4, "CKIT3", "CKIT3", "a null key or no key ?", "vic20 kernal.src: ckit3"],
  [0xebd0, "PUTQUE", "PUTQUE", null, "vic20 kernal.src: putque"],
  [0xebdc, "SHFLOG", "SHFLOG", null, "vic20 kernal.src: shflog"],
  [0xec00, "SWITCH", "SWITCH", null, "vic20 kernal.src: switch"],
  [0xec33, "NOTKAT", "NOTKAT", null, "vic20 kernal.src: notkat"],
  [0xec43, "SHFOUT", "SHFOUT", null, "vic20 kernal.src: shfout"],
  [0xec46, "KEYCOD", "KEYCOD", "keyboard mode 'dispatch'", "vic20 kernal.src: keycod"],
  [0xec5e, "MODE1", "MODE1", null, "vic20 kernal.src: mode1"],
  [0xec9f, "MODE2", "MODE2", null, "vic20 kernal.src: mode2"],
  [0xece0, "MODE3", "MODE3", "left window grahpics", "vic20 kernal.src: mode3"],
  [0xed21, "CCTTA2", "CCTTA2", "was cctta2 in japanese version; also: LOWER", "vic20 kernal.src: cctta2"],
  [0xed30, "UPPER", "UPPER", null, "vic20 kernal.src: upper"],
  [0xed5b, "PATCHX", "PATCHX", null, "vic20 kernal.src: patchx"],
  [0xed69, "CCTTA3", "CCTTA3", null, "vic20 kernal.src: cctta3"],
  [0xeda3, "CONTRL", "CONTRL", null, "vic20 kernal.src: contrl"],
  [0xede4, "TVIC", "TVIC", null, "vic20 kernal.src: tvic"],
  [0xedf4, "RUNTB", "RUNTB", null, "vic20 kernal.src: runtb"],
  [0xedfd, "LDTB2", "LDTB2", null, "vic20 kernal.src: ldtb2"],
  [0xee14, "TALK", "TALK", "make a talk adr", "vic20 kernal.src: talk"],
  [0xee17, "LISTN", "LISTN", "make a listen adr", "vic20 kernal.src: listn"],
  [0xee1c, "LIST1", "LIST1", null, "vic20 kernal.src: list1"],
  [0xee40, "ISOURA", "ISOURA", null, "vic20 kernal.src: isoura"],
  [0xee49, "ISOUR", "ISOUR", "no irq's allowed", "vic20 kernal.src: isour"],
  [0xeeb9, "CSBERR", "CSBERR", "commodore serial buss error entry", "vic20 kernal.src: csberr"],
  [0xeec0, "SECND", "SECND", "buffer character", "vic20 kernal.src: secnd"],
  [0xeec5, "SCATN", "SCATN", null, "vic20 kernal.src: scatn"],
  [0xeece, "TKSA", "TKSA", "buffer character", "vic20 kernal.src: tksa"],
  [0xeed3, "TKATN", "TKATN", "shift over to listener", "vic20 kernal.src: tkatn"],
  [0xeee4, "CIOUT", "CIOUT", "buffered char?", "vic20 kernal.src: ciout"],
  [0xeef6, "UNTLK", "UNTLK", null, "vic20 kernal.src: untlk"],
  [0xef04, "UNLSN", "UNLSN", "unlisten command", "vic20 kernal.src: unlsn"],
  [0xef0c, "DLADLH", "DLADLH", "delay approx 60 us", "vic20 kernal.src: dladlh"],
  [0xef19, "ACPTR", "ACPTR", null, "vic20 kernal.src: acptr"],
  [0xef84, "CLKHI", "CLKHI", "set clock line high (inverted)", "vic20 kernal.src: clkhi"],
  [0xef8d, "CLKLO", "CLKLO", "set clock line low (inverted)", "vic20 kernal.src: clklo"],
  [0xef96, "W1MS", "W1MS", "delay 1ms using timer 2", "vic20 kernal.src: w1ms"],
  [0xefa3, "RSTRAB", "RSTRAB", "check for place in byte...", "vic20 kernal.src: rstrab"],
  [0xefee, "RSTBGN", "RSTBGN", "check for 3/x line", "vic20 kernal.src: rstbgn"],
  [0xf004, "RST070", "RST070", "bitts=#of bitts+1", "vic20 kernal.src: rst070"],
  [0xf006, "RST080", "RST080", "check buffer pointers", "vic20 kernal.src: rst080"],
  [0xf016, "DSRERR", "DSRERR", "dsr gone error", "vic20 kernal.src: dsrerr"],
  [0xf027, "BITCNT", "BITCNT", "calc word length", "vic20 kernal.src: bitcnt"],
  [0xf036, "RSRCVR", "RSRCVR", "check for start bit", "vic20 kernal.src: rsrcvr"],
  [0xf05b, "RSRABL", "RSRABL", "enable cb1 for next byte", "vic20 kernal.src: rsrabl"],
  [0xf062, "RSRSXT", "RSRSXT", "disable t2", "vic20 kernal.src: rsrsxt"],
  [0xf0aa, "ERR232", "ERR232", null, "vic20 kernal.src: err232"],
  [0xf0b9, "RS232", "RS232", "bad device number", "vic20 kernal.src: rs232"],
  [0xf0bc, "CKO232", "CKO232", "set default out ###temp code###", "vic20 kernal.src: cko232"],
  [0xf0ed, "BSO232", "BSO232", null, "vic20 kernal.src: bso232"],
  [0xf0fc, "BSO100", "BSO100", "check for a t1 nmi enable", "vic20 kernal.src: bso100"],
  [0xf116, "CKI232", "CKI232", "set default input", "vic20 kernal.src: cki232"],
  [0xf14f, "BSI232", "BSI232", "get last byte address", "vic20 kernal.src: bsi232"],
  [0xf160, "RSP232", "RSP232", "save .a", "vic20 kernal.src: rsp232"],
  [0xf174, "MS1", "MS1", null, "vic20 kernal.src: MS1"],
  [0xf180, "MS5", "MS5", null, "vic20 kernal.src: MS5"],
  [0xf18b, "MS6", "MS6", null, "vic20 kernal.src: MS6"],
  [0xf18f, "MS7", "MS7", null, "vic20 kernal.src: MS7"],
  [0xf1a2, "MS8", "MS8", null, "vic20 kernal.src: MS8"],
  [0xf1bd, "MS10", "MS10", null, "vic20 kernal.src: MS10"],
  [0xf1c5, "MS11", "MS11", null, "vic20 kernal.src: MS11"],
  [0xf1cd, "MS21", "MS21", null, "vic20 kernal.src: MS21"],
  [0xf1d7, "MS17", "MS17", null, "vic20 kernal.src: MS17"],
  [0xf1de, "MS18", "MS18", null, "vic20 kernal.src: MS18"],
  [0xf1e2, "SPMSG", "SPMSG", "printing messages?", "vic20 kernal.src: spmsg"],
  [0xf1e6, "MSG", "MSG", null, "vic20 kernal.src: msg"],
  [0xf1f5, "NGETIN", "NGETIN", "check device", "vic20 kernal.src: ngetin"],
  [0xf205, "GN232", "GN232", "save .y, used in rs232", "vic20 kernal.src: gn232"],
  [0xf20e, "NBASIN", "NBASIN", "check device", "vic20 kernal.src: nbasin"],
  [0xf250, "JTGET", "JTGET", "buffer pointer wrap?", "vic20 kernal.src: jtget"],
  [0xf27a, "NBSOUT", "NBSOUT", "preserve .a", "vic20 kernal.src: nbsout"],
  [0xf290, "CASOUT", "CASOUT", null, "vic20 kernal.src: casout"],
  [0xf2c7, "NCHKIN", "NCHKIN", "see if file known", "vic20 kernal.src: nchkin"],
  [0xf301, "JX350", "JX350", null, "vic20 kernal.src: jx350"],
  [0xf309, "NCKOUT", "NCKOUT", "is file in table?", "vic20 kernal.src: nckout"],
  [0xf34a, "NCLOSE", "NCLOSE", "look file up", "vic20 kernal.src: nclose"],
  [0xf3b1, "JX150", "JX150", "get table index off stack", "vic20 kernal.src: jx150"],
  [0xf3b2, "JXRMV", "JXRMV", null, "vic20 kernal.src: jxrmv"],
  [0xf3cf, "LOOKUP", "LOOKUP", null, "vic20 kernal.src: lookup"],
  [0xf3d4, "JLTLK", "JLTLK", null, "vic20 kernal.src: jltlk"],
  [0xf3df, "JZ100", "JZ100", null, "vic20 kernal.src: jz100"],
  [0xf3ef, "NCLALL", "NCLALL", null, "vic20 kernal.src: nclall"],
  [0xf3f3, "NCLRCH", "NCLRCH", null, "vic20 kernal.src: nclrch"],
  [0xf40a, "NOPEN", "NOPEN", "check file #", "vic20 kernal.src: nopen"],
  [0xf495, "OPENI", "OPENI", null, "vic20 kernal.src: openi"],
  [0xf4c7, "OPN232", "OPN232", null, "vic20 kernal.src: opn232"],
  [0xf50c, "OPN030", "OPN030", "bit 0 of m51cdr", "vic20 kernal.src: opn030"],
  [0xf527, "OPN055", "OPN055", "get memsiz", "vic20 kernal.src: opn055"],
  [0xf53c, "MEMTCF", "MEMTCF", "signal top of memory change", "vic20 kernal.src: memtcf"],
  [0xf542, "LOADSP", "LOADSP", ".x has low alt start", "vic20 kernal.src: loadsp"],
  [0xf546, "LOAD", "LOAD", "monitor load entry", "vic20 kernal.src: load"],
  [0xf549, "NLOAD", "NLOAD", "store verify flag", "vic20 kernal.src: nload"],
  [0xf647, "LUKING", "LUKING", "supposed to print?", "vic20 kernal.src: luking"],
  [0xf659, "OUTFN", "OUTFN", "is there a name?", "vic20 kernal.src: outfn"],
  [0xf66a, "LODING", "LODING", "assume 'loading'", "vic20 kernal.src: loding"],
  [0xf675, "SAVESP", "SAVESP", null, "vic20 kernal.src: savesp"],
  [0xf682, "SAVE", "SAVE", null, "vic20 kernal.src: save"],
  [0xf685, "NSAVE", "NSAVE", "monitor entry", "vic20 kernal.src: nsave"],
  [0xf6cb, "BREAK", "BREAK", null, "vic20 kernal.src: break"],
  [0xf6da, "CLSEI", "CLSEI", null, "vic20 kernal.src: clsei"],
  [0xf705, "SV105", "SV105", "decide type to save", "vic20 kernal.src: sv105"],
  [0xf728, "SAVING", "SAVING", null, "vic20 kernal.src: saving"],
  [0xf734, "UDTIM", "UDTIM", "pre-load for later", "vic20 kernal.src: udtim"],
  [0xf736, "UD20", "UD20", null, "vic20 kernal.src: ud20"],
  [0xf760, "RDTIM", "RDTIM", "keep time from rolling", "vic20 kernal.src: rdtim"],
  [0xf767, "SETTIM", "SETTIM", "keep time from changing", "vic20 kernal.src: settim"],
  [0xf770, "NSTOP", "NSTOP", "value of last row", "vic20 kernal.src: nstop"],
  [0xf77e, "ERROR1", "ERROR1", "too many files", "vic20 kernal.src: error1"],
  [0xf781, "ERROR2", "ERROR2", "file open", "vic20 kernal.src: error2"],
  [0xf784, "ERROR3", "ERROR3", "file not open", "vic20 kernal.src: error3"],
  [0xf787, "ERROR4", "ERROR4", "file not found", "vic20 kernal.src: error4"],
  [0xf78a, "ERROR5", "ERROR5", "device not present", "vic20 kernal.src: error5"],
  [0xf78d, "ERROR6", "ERROR6", "not input file", "vic20 kernal.src: error6"],
  [0xf790, "ERROR7", "ERROR7", "not output file", "vic20 kernal.src: error7"],
  [0xf793, "ERROR8", "ERROR8", "missing file name", "vic20 kernal.src: error8"],
  [0xf796, "ERROR9", "ERROR9", "bad device #", "vic20 kernal.src: error9"],
  [0xf7af, "FAH", "FAH", "save old verify", "vic20 kernal.src: fah"],
  [0xf7e7, "TAPEH", "TAPEH", null, "vic20 kernal.src: tapeh"],
  [0xf84d, "ZZZ", "ZZZ", "assume tape1", "vic20 kernal.src: zzz"],
  [0xf854, "LDAD1", "LDAD1", "get ptr to cassette", "vic20 kernal.src: ldad1"],
  [0xf867, "FAF", "FAF", "find any header", "vic20 kernal.src: faf"],
  [0xf88a, "JTP20", "JTP20", null, "vic20 kernal.src: jtp20"],
  [0xf894, "CSTE1", "CSTE1", null, "vic20 kernal.src: cste1"],
  [0xf8ab, "CS10", "CS10", "check port", "vic20 kernal.src: cs10"],
  [0xf8b7, "CSTE2", "CSTE2", null, "vic20 kernal.src: cste2"],
  [0xf8c0, "RBLK", "RBLK", null, "vic20 kernal.src: rblk"],
  [0xf8c9, "TRD", "TRD", "say 'press play'", "vic20 kernal.src: trd"],
  [0xf8e3, "WBLK", "WBLK", null, "vic20 kernal.src: wblk"],
  [0xf8e6, "TWRT", "TWRT", "between block shorts", "vic20 kernal.src: twrt"],
  [0xf8ea, "TWRT2", "TWRT2", "say 'press play & record'", "vic20 kernal.src: twrt2"],
  [0xf92f, "TP40", "TP40", "check for interrupt vector...", "vic20 kernal.src: tp40"],
  [0xf94b, "TSTOP", "TSTOP", "stop key down?", "vic20 kernal.src: tstop"],
  [0xf95d, "STT1", "STT1", ".x has constant for timeout", "vic20 kernal.src: stt1"],
  [0xf98e, "READ", "READ", "get time since last interrupt", "vic20 kernal.src: read"],
  [0xfa60, "RAD2", "RAD2", "have we gotten block sync...", "vic20 kernal.src: rad2"],
  [0xfaad, "RADJ", "RADJ", "finish byte, clr flags", "vic20 kernal.src: radj"],
  [0xfb87, "RD59", "RD59", "load or verify?...", "vic20 kernal.src: rd59"],
  [0xfb95, "RD160", "RD160", "set mode skip next data", "vic20 kernal.src: rd160"],
  [0xfb97, "RD161", "RD161", null, "vic20 kernal.src: rd161"],
  [0xfbd2, "RD300", "RD300", "restore starting address...", "vic20 kernal.src: rd300"],
  [0xfbdb, "NEWCH", "NEWCH", "set up for 8 bits+parity", "vic20 kernal.src: newch"],
  [0xfbea, "WRITE", "WRITE", "shift bit to write into carry", "vic20 kernal.src: write"],
  [0xfbf1, "WRTW", "WRTW", "...c set write long", "vic20 kernal.src: wrtw"],
  [0xfbf3, "WRT1", "WRT1", "set and store time", "vic20 kernal.src: wrt1"],
  [0xfbf5, "WRTX", "WRTX", null, "vic20 kernal.src: wrtx"],
  [0xfc0b, "WRTN", "WRTN", "check for one long", "vic20 kernal.src: wrtn"],
  [0xfc60, "WRTS1", "WRTS1", null, "vic20 kernal.src: wrts1"],
  [0xfc95, "WRNC", "WRNC", "check for end", "vic20 kernal.src: wrnc"],
  [0xfca8, "WRTZ", "WRTZ", "write leading zeros for sync", "vic20 kernal.src: wrtz"],
  [0xfccf, "TNIF", "TNIF", "clean up interrupts and restore pia's", "vic20 kernal.src: tnif"],
  [0xfcfb, "BSIV", "BSIV", "move irq vectors, table to indirect", "vic20 kernal.src: bsiv"],
  [0xfd08, "TNOF", "TNOF", "turn off cassette motor", "vic20 kernal.src: tnof"],
  [0xfd11, "CMPSTE", "CMPSTE", null, "vic20 kernal.src: cmpste"],
  [0xfd1b, "INCSAL", "INCSAL", null, "vic20 kernal.src: incsal"],
  [0xfd22, "START", "START", null, "vic20 kernal.src: start"],
  [0xfd3f, "A0INT", "A0INT", "check for $a000", "vic20 kernal.src: a0int"],
  [0xfd4d, "TBLA0R", "TBLA0R", "..A0CBM..", "vic20 kernal.src: tbla0r"],
  [0xfd52, "TBLA0E", "TBLA0E", "also: RESTOR", "vic20 kernal.src: tbla0e"],
  [0xfd57, "VECTOR", "VECTOR", null, "vic20 kernal.src: vector"],
  [0xfd6d, "VECTSS", "VECTSS", null, "vic20 kernal.src: vectss"],
  [0xfd8d, "VECTSE", "VECTSE", "also: RAMTAS", "vic20 kernal.src: vectse"],
  [0xfda3, "RAMTBT", "RAMTBT", "set low inital index", "vic20 kernal.src: ramtbt"],
  [0xfdeb, "BADRAM", "BADRAM", "initilize vic ram is bad", "vic20 kernal.src: badram"],
  [0xfdf1, "BSIT", "BSIT", "table of indirects for cassette irq's", "vic20 kernal.src: bsit"],
  [0xfdf9, "IOINIT", "IOINIT", "kill iers", "vic20 kernal.src: ioinit"],
  [0xfe39, "IOKEYS", "IOKEYS", "enable t1 interrupts", "vic20 kernal.src: iokeys"],
  [0xfe49, "SETNAM", "SETNAM", null, "vic20 kernal.src: setnam"],
  [0xfe50, "SETLFS", "SETLFS", null, "vic20 kernal.src: setlfs"],
  [0xfe57, "READSS", "READSS", "see which devices' to read", "vic20 kernal.src: readss"],
  [0xfe66, "SETMSG", "SETMSG", null, "vic20 kernal.src: setmsg"],
  [0xfe6a, "UDST", "UDST", null, "vic20 kernal.src: udst"],
  [0xfe6f, "SETTMO", "SETTMO", null, "vic20 kernal.src: settmo"],
  [0xfe73, "MEMTOP", "MEMTOP", null, "vic20 kernal.src: memtop"],
  [0xfe75, "GETTOP", "GETTOP", null, "vic20 kernal.src: gettop"],
  [0xfe7b, "SETTOP", "SETTOP", null, "vic20 kernal.src: settop"],
  [0xfe82, "MEMBOT", "MEMBOT", null, "vic20 kernal.src: membot"],
  [0xfe91, "CHKMEM", "CHKMEM", null, "vic20 kernal.src: chkmem"],
  [0xfea9, "NMI", "NMI", "no irq's allowed...", "vic20 kernal.src: nmi"],
  [0xfead, "NNMI", "NNMI", "save 6502 regs", "vic20 kernal.src: nnmi"],
  [0xfeb2, "NNMI10", "NNMI10", "check if real nmi...", "vic20 kernal.src: nnmi10"],
  [0xfebf, "NNMI18", "NNMI18", "check if $a0 in...", "vic20 kernal.src: nnmi18"],
  [0xfed2, "TIMB", "TIMB", "restore system indirects", "vic20 kernal.src: timb"],
  [0xff56, "NMIRTI", "NMIRTI", "restore 6502 regs; also: PREND", "vic20 kernal.src: nmirti"],
  [0xff5c, "BAUDO", "BAUDO", "50 baud", "vic20 kernal.src: baudo"],
  [0xff72, "PULS", "PULS", null, "vic20 kernal.src: puls"],
  [0xff8a, "RESTOR", "RESTOR", "restore vectors to initial system; jump-table slot: jmp restor", "vic20 kernal.src: jmp restor"],
  [0xff8d, "VECTOR", "VECTOR", "change vectors for user; jump-table slot: jmp vector", "vic20 kernal.src: jmp vector"],
  [0xff90, "SETMSG", "SETMSG", "control o.s. messages; jump-table slot: jmp setmsg", "vic20 kernal.src: jmp setmsg"],
  [0xff93, "SECND", "SECND", "send sa after listen; jump-table slot: jmp secnd", "vic20 kernal.src: jmp secnd"],
  [0xff96, "TKSA", "TKSA", "send sa after talk; jump-table slot: jmp tksa", "vic20 kernal.src: jmp tksa"],
  [0xff99, "MEMTOP", "MEMTOP", "set/read top of memory; jump-table slot: jmp memtop", "vic20 kernal.src: jmp memtop"],
  [0xff9c, "MEMBOT", "MEMBOT", "set/read bottom of memory; jump-table slot: jmp membot", "vic20 kernal.src: jmp membot"],
  [0xff9f, "SCNKEY", "SCNKEY", "scan keyboard; jump-table slot: jmp scnkey", "vic20 kernal.src: jmp scnkey"],
  [0xffa2, "SETTMO", "SETTMO", "set timeout in ieee; jump-table slot: jmp settmo", "vic20 kernal.src: jmp settmo"],
  [0xffa5, "ACPTR", "ACPTR", "handshake ieee byte in; jump-table slot: jmp acptr", "vic20 kernal.src: jmp acptr"],
  [0xffa8, "CIOUT", "CIOUT", "handshake ieee byte out; jump-table slot: jmp ciout", "vic20 kernal.src: jmp ciout"],
  [0xffab, "UNTLK", "UNTLK", "send untalk out ieee; jump-table slot: jmp untlk", "vic20 kernal.src: jmp untlk"],
  [0xffae, "UNLSN", "UNLSN", "send unlisten out ieee; jump-table slot: jmp unlsn", "vic20 kernal.src: jmp unlsn"],
  [0xffb1, "LISTN", "LISTN", "send listen out ieee; jump-table slot: jmp listn", "vic20 kernal.src: jmp listn"],
  [0xffb4, "TALK", "TALK", "send talk out ieee; jump-table slot: jmp talk", "vic20 kernal.src: jmp talk"],
  [0xffb7, "READSS", "READSS", "return i/o status byte; jump-table slot: jmp readss", "vic20 kernal.src: jmp readss"],
  [0xffba, "SETLFS", "SETLFS", "set la, fa, sa; jump-table slot: jmp setlfs", "vic20 kernal.src: jmp setlfs"],
  [0xffbd, "SETNAM", "SETNAM", "set length and fn adr; jump-table slot: jmp setnam", "vic20 kernal.src: jmp setnam"],
  [0xffc0, "OPEN", "OPEN", "open logical file", "vic20 kernal.src: open"],
  [0xffc3, "CLOSE", "CLOSE", "close logical file", "vic20 kernal.src: close"],
  [0xffc6, "CHKIN", "CHKIN", "open channel in", "vic20 kernal.src: chkin"],
  [0xffc9, "CKOUT", "CKOUT", "open channel out", "vic20 kernal.src: ckout"],
  [0xffcc, "CLRCH", "CLRCH", "close i/o channel", "vic20 kernal.src: clrch"],
  [0xffcf, "BASIN", "BASIN", "input from channel", "vic20 kernal.src: basin"],
  [0xffd2, "BSOUT", "BSOUT", "output to channel", "vic20 kernal.src: bsout"],
  [0xffd5, "LOADSP", "LOADSP", "load from file; jump-table slot: jmp loadsp", "vic20 kernal.src: jmp loadsp"],
  [0xffd8, "SAVESP", "SAVESP", "save to file; jump-table slot: jmp savesp", "vic20 kernal.src: jmp savesp"],
  [0xffdb, "SETTIM", "SETTIM", "set internal clock; jump-table slot: jmp settim", "vic20 kernal.src: jmp settim"],
  [0xffde, "RDTIM", "RDTIM", "read internal clock; jump-table slot: jmp rdtim", "vic20 kernal.src: jmp rdtim"],
  [0xffe1, "STOP", "STOP", "scan stop key", "vic20 kernal.src: stop"],
  [0xffe4, "GETIN", "GETIN", "get char from q", "vic20 kernal.src: getin"],
  [0xffe7, "CLALL", "CLALL", "close all files", "vic20 kernal.src: clall"],
  [0xffea, "UDTIM", "UDTIM", "increment clock; jump-table slot: jmp udtim", "vic20 kernal.src: jmp udtim"],
  [0xffed, "JSCROG", "JSCROG", "screen org", "vic20 kernal.src: jscrog"],
  [0xfff0, "JPLOT", "JPLOT", "read/set x,y coord", "vic20 kernal.src: jplot"],
  [0xfff3, "JIOBAS", "JIOBAS", "return i/o base", "vic20 kernal.src: jiobas"],
];

export const VIC20_REGIONS: SeedRegion[] = [
  [0x0000, 0x0002, "USRPOK", "vic20 basic.src: usrpok"],
  [0x0003, 0x0004, "ADRAY1", "vic20 basic.src: adray1"],
  [0x0005, 0x0006, "ADRAY2", "vic20 basic.src: adray2"],
  [0x0014, 0x0015, "LINNUM", "vic20 basic.src: linnum"],
  [0x0017, 0x0018, "LASTPT", "vic20 basic.src: lastpt"],
  [0x0019, 0x0021, "TEMPST", "vic20 basic.src: tempst"],
  [0x0022, 0x0023, "INDEX1", "vic20 basic.src: index1"],
  [0x0024, 0x0025, "INDEX2", "vic20 basic.src: index2"],
  [0x002b, 0x002c, "TXTTAB", "vic20 basic.src: txttab"],
  [0x002d, 0x002e, "VARTAB", "vic20 basic.src: vartab"],
  [0x002f, 0x0030, "ARYTAB", "vic20 basic.src: arytab"],
  [0x0031, 0x0032, "STREND", "vic20 basic.src: strend"],
  [0x0033, 0x0034, "FRETOP", "vic20 basic.src: fretop"],
  [0x0035, 0x0036, "FRESPC", "vic20 basic.src: frespc"],
  [0x0037, 0x0038, "MEMSIZ", "vic20 basic.src: memsiz"],
  [0x0039, 0x003a, "CURLIN", "vic20 basic.src: curlin"],
  [0x003b, 0x003c, "OLDLIN", "vic20 basic.src: oldlin"],
  [0x003d, 0x003e, "OLDTXT", "vic20 basic.src: oldtxt"],
  [0x003f, 0x0040, "DATLIN", "vic20 basic.src: datlin"],
  [0x0041, 0x0042, "DATPTR", "vic20 basic.src: datptr"],
  [0x0043, 0x0044, "INPPTR", "vic20 basic.src: inpptr"],
  [0x0045, 0x0046, "VARNAM", "vic20 basic.src: varnam"],
  [0x0047, 0x0048, "VARPNT", "vic20 basic.src: varpnt"],
  [0x0049, 0x004a, "FORPNT", "vic20 basic.src: forpnt"],
  [0x004b, 0x004c, "OPPTR", "vic20 basic.src: opptr"],
  [0x004e, 0x004f, "DEFPNT", "vic20 basic.src: defpnt"],
  [0x0050, 0x0051, "DSCPNT", "vic20 basic.src: dscpnt"],
  [0x0058, 0x0059, "HIGHDS", "vic20 basic.src: highds"],
  [0x005a, 0x005b, "HIGHTR", "vic20 basic.src: hightr"],
  [0x005d, 0x005e, "LOWDS", "vic20 basic.src: lowds"],
  [0x0071, 0x0072, "FBUFPT", "vic20 basic.src: fbufpt"],
  [0x0073, 0x0078, "CHRGET", "vic20 basic.src: chrget"],
  [0x007a, 0x007f, "TXTPTR", "vic20 basic.src: txtptr"],
  [0x0080, 0x0089, "QNUM", "vic20 basic.src: qnum"],
  [0x008b, 0x008f, "RNDX", "vic20 basic.src: rndx"],
  [0x00a0, 0x00a2, "TIME", "vic20 kernal.src: time"],
  [0x00b2, 0x00b3, "TAPE1", "vic20 kernal.src: tape1"],
  [0x00bb, 0x00bc, "FNADR", "vic20 kernal.src: fnadr"],
  [0x00c3, 0x00c4, "TMP2", "vic20 kernal.src: tmp2"],
  [0x00d1, 0x00d2, "PNT", "vic20 kernal.src: pnt"],
  [0x00d9, 0x00f1, "LDTB1", "vic20 kernal.src: ldtb1"],
  [0x00f3, 0x00f4, "USER", "vic20 kernal.src: user"],
  [0x00f5, 0x00f6, "KEYTAB", "vic20 kernal.src: keytab"],
  [0x00f7, 0x00f8, "RIBUF", "vic20 kernal.src: ribuf"],
  [0x00f9, 0x00fa, "ROBUF", "vic20 kernal.src: robuf"],
  [0x00fb, 0x00fe, "FREKZP", "vic20 kernal.src: frekzp"],
  [0x0200, 0x0258, "BUF", "vic20 kernal.src: buf"],
  [0x0259, 0x0262, "LAT", "vic20 kernal.src: lat"],
  [0x0263, 0x026c, "FAT", "vic20 kernal.src: fat"],
  [0x026d, 0x0276, "SAT", "vic20 kernal.src: sat"],
  [0x0277, 0x0280, "KEYD", "vic20 kernal.src: keyd"],
  [0x0281, 0x0282, "MEMSTR", "vic20 kernal.src: memstr"],
  [0x0283, 0x0284, "MEMSIZ", "vic20 kernal.src: memsiz"],
  [0x028f, 0x0290, "KEYLOG", "vic20 kernal.src: keylog"],
  [0x0295, 0x0296, "M51AJB", "vic20 kernal.src: m51ajb"],
  [0x0299, 0x029a, "BAUDOF", "vic20 kernal.src: baudof"],
  [0x029f, 0x02a0, "IRQTMP", "vic20 kernal.src: irqtmp"],
  [0x0300, 0x0301, "IERROR", "vic20 basic.src: ierror"],
  [0x0302, 0x0303, "IMAIN", "vic20 basic.src: imain"],
  [0x0304, 0x0305, "ICRNCH", "vic20 basic.src: icrnch"],
  [0x0306, 0x0307, "IQPLOP", "vic20 basic.src: iqplop"],
  [0x0308, 0x0309, "IGONE", "vic20 basic.src: igone"],
  [0x030a, 0x030b, "IEVAL", "vic20 basic.src: ieval"],
  [0x0314, 0x0315, "CINV", "vic20 kernal.src: cinv"],
  [0x0316, 0x0317, "CBINV", "vic20 kernal.src: cbinv"],
  [0x0318, 0x0319, "NMINV", "vic20 kernal.src: nminv"],
  [0x031a, 0x031b, "IOPEN", "vic20 kernal.src: iopen"],
  [0x031c, 0x031d, "ICLOSE", "vic20 kernal.src: iclose"],
  [0x031e, 0x031f, "ICHKIN", "vic20 kernal.src: ichkin"],
  [0x0320, 0x0321, "ICKOUT", "vic20 kernal.src: ickout"],
  [0x0322, 0x0323, "ICLRCH", "vic20 kernal.src: iclrch"],
  [0x0324, 0x0325, "IBASIN", "vic20 kernal.src: ibasin"],
  [0x0326, 0x0327, "IBSOUT", "vic20 kernal.src: ibsout"],
  [0x0328, 0x0329, "ISTOP", "vic20 kernal.src: istop"],
  [0x032a, 0x032b, "IGETIN", "vic20 kernal.src: igetin"],
  [0x032c, 0x032d, "ICLALL", "vic20 kernal.src: iclall"],
  [0x032e, 0x032f, "USRCMD", "vic20 kernal.src: usrcmd"],
  [0x0330, 0x0331, "ILOAD", "vic20 kernal.src: iload"],
  [0x0332, 0x0333, "ISAVE", "vic20 kernal.src: isave"],
  [0x033c, 0x03fb, "TBUFFR", "vic20 kernal.src: tbuffr"],
  [0x1000, 0x11ff, "VICSCN", "vic20 kernal.src: vicscn"],
  [0x9000, 0x900f, "VICREG", "vic20 kernal.src: vicreg"],
  [0x9400, 0x95ff, "VICCOL", "vic20 kernal.src: viccol"],
  [0xdf53, 0xdf70, "PATCHS", "vic20 basic.src: patchs"],
];
