// Spec 817 — pipeline-side reader for resources/platform-kb.sqlite.
//
// This replaces four hand-typed tables (EXACT_COMMENTS, C64_KERNAL, ZP_COMMON,
// and the pipeline copy of platform-knowledge/) that disagreed with each other
// because the CommonJS pipeline could not import the ESM half's module. It can
// read the ESM half's FILE. The store is generated by `npm run build:platform-kb`
// from the c64ref snapshot plus src/platform-kb/extensions.ts, and this module
// contains no knowledge of its own — only lookups.
//
// Missing store = loud failure with the recipe, never a silent nameless render
// (doctrine rule 1: tools say so, they do not quietly do something else).

import { existsSync } from "node:fs";
import { resolve } from "node:path";

export type PlatformTag = "c64" | "c1541" | "vic20" | "plus4";

/**
 * Kind is a function of the address on the platform's memory map — the CommonJS twin of
 * `platformKindForAddress` in src/platform-kb/schema.ts (this half cannot import that
 * ESM module; scripts/e2e-898-platforms.mjs holds the two equal over every address).
 */
export function platformKindForAddress(platform: PlatformTag, address: number): PlatformNodeHit["kind"] {
  const a = address & 0xffff;
  if (a < 0x0100) return "zp";
  if (platform === "c1541") {
    if (a >= 0x1800 && a <= 0x1c0f) return "io";
    if (a >= 0xc000) return "rom";
    return "ram";
  }
  if (platform === "vic20") {
    if (a >= 0x9000 && a <= 0x9fff) return "io";
    if ((a >= 0x8000 && a <= 0x8fff) || a >= 0xc000) return "rom";
    return "ram";
  }
  if (platform === "plus4") {
    if (a >= 0xfd00 && a <= 0xff3f) return "io";
    if ((a >= 0x8000 && a <= 0xfcff) || a >= 0xff40) return "rom";
    return "ram";
  }
  if (a >= 0xd000 && a <= 0xdfff) return "io";
  if ((a >= 0xa000 && a <= 0xbfff) || a >= 0xe000) return "rom";
  return "ram";
}

/**
 * Where the machine's BASIC program text starts: the address a tokenized program's first
 * line-link sits at. The VIC-20 moves it with the RAM expansion ($1001 bare, $0401 with
 * +3K, $1201 with +8K and up); the TED machines start at $1001; the C64 at $0801. The
 * 1541 runs no BASIC. The CommonJS twin of `defaultLoadAddresses` in
 * src/project-knowledge/platform-default.ts (this half cannot import it;
 * scripts/e2e-898-platforms.mjs holds the two equal).
 */
export function basicStartAddresses(platform: PlatformTag): number[] {
  switch (platform) {
    case "vic20": return [0x1001, 0x0401, 0x1201];
    case "plus4": return [0x1001];
    case "c1541": return [];
    default: return [0x0801];
  }
}

/** True when `address` lies in the platform's I/O window — the one question every analysis pass asks instead of its own `$D000` test. */
export function isIoAddress(platform: PlatformTag, address: number): boolean {
  return platformKindForAddress(platform, address) === "io";
}

export interface PlatformNodeHit {
  kind: "zp" | "ram" | "io" | "rom";
  symbol: string | null;
  name: string;
  /** `SYMBOL name` when a symbol exists, else `name`. What a comment prints. */
  label: string;
}

type Db = import("node:sqlite").DatabaseSync;
type Stmt = import("node:sqlite").StatementSync;

let db: Db | undefined;
let nodeStmt: Stmt | undefined;
let regionStmt: Stmt | undefined;
let warned = false;

function quietSqlite(): typeof import("node:sqlite") {
  if (!warned) {
    warned = true;
    process.removeAllListeners("warning");
    process.on("warning", (warning) => {
      if (warning.name === "ExperimentalWarning" && /SQLite/i.test(warning.message)) return;
      console.error(`${warning.name}: ${warning.message}`);
    });
  }
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  return require("node:sqlite") as typeof import("node:sqlite");
}

export function resolvePlatformKbPath(): string {
  const candidates = [
    process.env.C64RE_PLATFORM_KB,
    resolve(__dirname, "../../../resources/platform-kb.sqlite"), // dist/pipeline/lib → repo root
    resolve(__dirname, "../../resources/platform-kb.sqlite"),
    resolve(process.cwd(), "resources/platform-kb.sqlite"),
  ].filter((p): p is string => Boolean(p));
  for (const candidate of candidates) if (existsSync(candidate)) return candidate;
  throw new Error(
    `platform-kb.sqlite not found (looked in ${candidates.join(", ")}). Run \`npm run build:platform-kb\`.`,
  );
}

function open(): void {
  if (db) return;
  const { DatabaseSync } = quietSqlite();
  db = new DatabaseSync(resolvePlatformKbPath(), { readOnly: true });
  nodeStmt = db.prepare("SELECT kind, symbol, name FROM platform_node WHERE platform = ? AND address = ?");
  regionStmt = db.prepare(
    "SELECT name FROM platform_region WHERE platform = ? AND start_address <= ? AND end_address >= ? ORDER BY (end_address - start_address) ASC LIMIT 1",
  );
}

export function platformNode(platform: PlatformTag, address: number): PlatformNodeHit | undefined {
  open();
  const row = nodeStmt!.get(platform, address & 0xffff) as { kind: PlatformNodeHit["kind"]; symbol: string | null; name: string } | undefined;
  if (!row) return undefined;
  return { kind: row.kind, symbol: row.symbol, name: row.name, label: row.symbol ? `${row.symbol} ${row.name}` : row.name };
}

/** The innermost documented range containing `address` ("VIC-II Chip Registers"). */
export function platformRegionName(platform: PlatformTag, address: number): string | undefined {
  open();
  const a = address & 0xffff;
  const row = regionStmt!.get(platform, a, a) as { name: string } | undefined;
  return row?.name;
}

/** Comment text for an operand, or undefined when the store knows nothing. */
export function platformComment(platform: PlatformTag, address: number): string | undefined {
  return platformNode(platform, address)?.label ?? platformRegionName(platform, address);
}
