// Spec 042: 2nd-pass annotation-proposal classifier. Reads
// `*_analysis.json` + (optionally) `*_disasm.asm` and emits a
// draft `*_annotations.draft.json` with per-entry confidence +
// reason + autoGenerated:true.
//
// Pattern fingerprint modules layer on top of the analyzer
// outputs that the deterministic Phase-1 pipeline already
// generated. They never overwrite manual annotations; the draft
// file is a separate path that the agent reviews and merges.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

interface AnalysisSegment {
  kind: string;
  start: number;
  end: number;
  score?: { confidence?: number };
}

interface AnalysisCrossRef {
  source: number;
  target: number;
  kind: string;
}

interface AnalysisRelocationProposal {
  fileStart: number;
  fileEnd: number;
  runtimeAddr: number;
  length?: number;
  confidence?: number;
  followedByJump?: boolean;
  lengthCertain?: boolean;
  reasons?: string[];
}

interface AnalysisReport {
  segments?: AnalysisSegment[];
  crossReferences?: AnalysisCrossRef[];
  entryPoints?: number[];
  symbols?: Array<{ name: string; address: number }>;
  relocationProposals?: AnalysisRelocationProposal[];
}

// Spec 741: a relocation candidate in the draft — same {fileStart,fileEnd,
// runtimeAddr} shape as disasm_prg.relocations so an accepted entry can be
// copied straight into the disasm call.
interface RelocationCandidate {
  fileStart: string;
  fileEnd: string;
  runtimeAddr: string;
  label: string;
  confidence: number;
  reason: string;
  autoGenerated: true;
}

interface SegmentCandidate {
  start: string;
  end: string;
  kind: string;
  label?: string;
  comment?: string;
  confidence: number;
  reason: string;
  autoGenerated: true;
}

interface LabelCandidate {
  address: string;
  label: string;
  comment?: string;
  confidence: number;
  reason: string;
  autoGenerated: true;
}

interface RoutineCandidate {
  address: string;
  name: string;
  summary: string;
  confidence: number;
  reason: string;
  autoGenerated: true;
}

interface OpenQuestionCandidate {
  title: string;
  description: string;
  confidence: number;
  source: "static-analysis";
}

export interface DraftAnnotations {
  segments: SegmentCandidate[];
  labels: LabelCandidate[];
  routines: RoutineCandidate[];
  openQuestions: OpenQuestionCandidate[];
  relocations: RelocationCandidate[];
  generatedAt: string;
  source: { analysisPath: string; listingPath?: string };
  buckets: { high: number; medium: number; low: number };
}

// Spec 741 §3.2: turn detected relocation proposals into draft candidates +
// review questions, in disasm_prg.relocations-ready shape.
function proposeRelocations(report: AnalysisReport): { relocations: RelocationCandidate[]; openQuestions: OpenQuestionCandidate[] } {
  const relocations: RelocationCandidate[] = [];
  const openQuestions: OpenQuestionCandidate[] = [];
  for (const r of report.relocationProposals ?? []) {
    const confidence = r.confidence ?? 0.6;
    relocations.push({
      fileStart: `$${hex4(r.fileStart)}`,
      fileEnd: `$${hex4(r.fileEnd)}`,
      runtimeAddr: `$${hex4(r.runtimeAddr)}`,
      label: `reloc_${hex4(r.runtimeAddr)}`,
      confidence,
      reason: (r.reasons ?? []).join(" ") || `copy loop relocates $${hex4(r.fileStart)} → $${hex4(r.runtimeAddr)}`,
      autoGenerated: true,
    });
    openQuestions.push({
      title: `Relocation: $${hex4(r.fileStart)}-$${hex4(r.fileEnd)} runs at $${hex4(r.runtimeAddr)}?`,
      description:
        `A copy loop appears to move this region to $${hex4(r.runtimeAddr)}` +
        `${r.lengthCertain === false ? " (length is a page-wrap estimate — verify the loop bound)" : ""}. ` +
        `If correct, pass it to disasm_prg.relocations as ` +
        `{fileStart:"$${hex4(r.fileStart)}", fileEnd:"$${hex4(r.fileEnd)}", runtimeAddr:"$${hex4(r.runtimeAddr)}"} ` +
        `to render it as .pseudopc/.logical code.`,
      confidence,
      source: "static-analysis",
    });
  }
  return { relocations, openQuestions };
}

function hex4(value: number): string {
  return value.toString(16).toUpperCase().padStart(4, "0");
}

// ---------------------------------------------------------------------------
// Pattern fingerprint modules — small, deterministic, conservative.
// Each returns its own candidate slice; the orchestrator merges them.

function namePointerTables(report: AnalysisReport): { segments: SegmentCandidate[]; labels: LabelCandidate[] } {
  const segments: SegmentCandidate[] = [];
  const labels: LabelCandidate[] = [];
  for (const seg of report.segments ?? []) {
    if (seg.kind === "pointer_table") {
      const length = seg.end - seg.start + 1;
      segments.push({
        start: hex4(seg.start),
        end: hex4(seg.end),
        kind: "pointer_table",
        label: `pointer_table_${hex4(seg.start)}`,
        comment: `${length}-byte pointer table at $${hex4(seg.start)}`,
        confidence: Math.max(0.6, seg.score?.confidence ?? 0.6),
        reason: "analyzer classified as pointer_table",
        autoGenerated: true,
      });
      labels.push({
        address: hex4(seg.start),
        label: `pointer_table_${hex4(seg.start)}`,
        confidence: 0.7,
        reason: "pointer table start label",
        autoGenerated: true,
      });
    }
  }
  return { segments, labels };
}

function nameTextSegments(report: AnalysisReport): SegmentCandidate[] {
  const out: SegmentCandidate[] = [];
  for (const seg of report.segments ?? []) {
    if (seg.kind === "petscii_text" || seg.kind === "screen_code_text") {
      out.push({
        start: hex4(seg.start),
        end: hex4(seg.end),
        kind: "petscii_text",
        comment: "text run detected by analyzer; review and split into named strings if needed",
        confidence: Math.max(0.55, seg.score?.confidence ?? 0.55),
        reason: `analyzer kind ${seg.kind}`,
        autoGenerated: true,
      });
    }
  }
  return out;
}

function nameCrossRefTargets(report: AnalysisReport): { labels: LabelCandidate[]; routines: RoutineCandidate[] } {
  const labels: LabelCandidate[] = [];
  const routines: RoutineCandidate[] = [];
  const callTargets = new Map<number, number>();
  for (const ref of report.crossReferences ?? []) {
    if (ref.kind === "call") {
      callTargets.set(ref.target, (callTargets.get(ref.target) ?? 0) + 1);
    }
  }
  for (const [target, count] of callTargets.entries()) {
    if (count >= 2) {
      const name = `routine_${hex4(target)}`;
      routines.push({
        address: hex4(target),
        name,
        summary: `Called from ${count} sites; promote to documented routine.`,
        confidence: Math.min(0.85, 0.5 + count * 0.05),
        reason: `cross-ref count ${count}`,
        autoGenerated: true,
      });
      labels.push({
        address: hex4(target),
        label: name,
        confidence: 0.7,
        reason: "frequent call target",
        autoGenerated: true,
      });
    }
  }
  return { labels, routines };
}

function questionLargeUnknowns(report: AnalysisReport): OpenQuestionCandidate[] {
  const out: OpenQuestionCandidate[] = [];
  for (const seg of report.segments ?? []) {
    if (seg.kind !== "unknown") continue;
    const length = seg.end - seg.start + 1;
    if (length < 32) continue;
    out.push({
      title: `Unknown ${length}-byte block at $${hex4(seg.start)}-$${hex4(seg.end)}`,
      description: `Phase-1 analyzer left this region unclassified. Review by hand: aligned 16-bit pairs (pointer table)? printable ASCII (string)? sprite/charset? padding?`,
      confidence: 0.5,
      source: "static-analysis",
    });
  }
  return out;
}

function bucketCount<T extends { confidence: number }>(items: T[]): { high: number; medium: number; low: number } {
  let high = 0; let medium = 0; let low = 0;
  for (const item of items) {
    if (item.confidence >= 0.8) high += 1;
    else if (item.confidence >= 0.5) medium += 1;
    else low += 1;
  }
  return { high, medium, low };
}

export function proposeAnnotations(args: {
  analysisJsonPath: string;
  listingPath?: string;
  outputPath: string;
}): DraftAnnotations {
  if (!existsSync(args.analysisJsonPath)) {
    throw new Error(`analysis JSON not found at ${args.analysisJsonPath}`);
  }
  const report = JSON.parse(readFileSync(args.analysisJsonPath, "utf8")) as AnalysisReport;
  const pointerPass = namePointerTables(report);
  const textPass = nameTextSegments(report);
  const xrefPass = nameCrossRefTargets(report);
  const questionPass = questionLargeUnknowns(report);
  const relocationPass = proposeRelocations(report);

  const segments = [...pointerPass.segments, ...textPass];
  const labels = [...pointerPass.labels, ...xrefPass.labels];
  const routines = xrefPass.routines;
  const relocations = relocationPass.relocations;
  const openQuestions = [...questionPass, ...relocationPass.openQuestions];

  const allBuckets = bucketCount([...segments, ...labels, ...routines, ...relocations]);

  const draft: DraftAnnotations = {
    segments,
    labels,
    routines,
    openQuestions,
    relocations,
    generatedAt: new Date().toISOString(),
    source: { analysisPath: args.analysisJsonPath, listingPath: args.listingPath },
    buckets: allBuckets,
  };

  mkdirSync(dirname(args.outputPath), { recursive: true });
  writeFileSync(args.outputPath, `${JSON.stringify(draft, null, 2)}\n`, "utf8");
  return draft;
}
