// ════════════════════════════════════════════════════════════════════════════
//  DEPRECATED — TypeScript runtime.  THE PRODUCT RUNTIME IS TRX64.
//
//  This file is part of the in-process TS emulator. It is reachable ONLY with
//  C64RE_RUNTIME_TS=1 and is never on the default path: every runtime_* tool,
//  the workspace UI and the MCP surface route to the TRX64 daemon (Spec 771).
//
//  Do not extend it, do not fix forward in it, and do not cite it as current
//  behaviour — "how the runtime works" means TRX64, in ../TRX64.
//  Its remaining job is to be a parity oracle for the port; when that is no
//  longer needed it goes. See DOCTRINE.md.
// ════════════════════════════════════════════════════════════════════════════
// Spec 200 — MachineKernel internal contract.
//
// Per-session monolithic emulator owner. Public client surface is
// IntegratedSession; this interface is the internal contract between
// the session and its kernel implementation, and lets tests substitute
// a mock kernel.

import type { KernelTraceController } from "./kernel-trace.js";
import type { KernelStatus } from "./kernel-status.js";

export interface MountedMedia {
  imagePath: string;
  bytes: Uint8Array;
}

export interface MachineSnapshot {
  // Adapter to the existing SessionSnapshot — kept opaque here so the
  // kernel module does not depend on snapshot.ts implementation. Spec
  // 200 commit chain wires the real adapter.
  readonly schemaVersion: number;
  readonly payload: unknown;
}

export interface MachineKernel {
  c64Clock(): number;
  driveClock(device: number): number;
  runCycles(n: number): void;
  runInstructions(n: number): void;
  // Spec 765 — `shallow` returns LIVE big-buffer refs (RAM + VIC framebuffers)
  // instead of detached `.slice()` copies, for the checkpoint ring's zero-alloc
  // capture path (the ring copies them in immediately, before the loop runs
  // again). Default (detached) is required for any caller that retains the
  // snapshot beyond the capture call (e.g. an out-of-band dump).
  // `omitFramebuffer` drops the two VIC framebuffers (the always-on perma-anchor
  // uses it — the framebuffer is derivable, regenerated by re-running one frame
  // on restore; 746 §1). A dump/explicit capture keeps them for .c64re fidelity.
  snapshot(opts?: { shallow?: boolean; omitFramebuffer?: boolean; omitMedia?: boolean }): MachineSnapshot;
  restore(snap: MachineSnapshot): void;
  mountMedia(device: number, media: MountedMedia): void;
  trace(): KernelTraceController;
  status(): KernelStatus;
}
