import { existsSync, mkdirSync, readFileSync, renameSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { auditProject, auditProjectCached, type AuditCachedResult, type ProjectAuditResult } from "../project-knowledge/audit.js";
import { ProjectKnowledgeService } from "../project-knowledge/service.js";
import { countUnimportedAnalysisArtifacts, scanRegistrationDelta } from "../lib/registration-delta.js";
import type { ServerToolContext } from "./types.js";

const AGENT_STATE_SCHEMA_VERSION = 1;

export const AgentRoleSchema = z.enum(["analyst", "cartographer", "implementer", "archivist", "cracker", "unset"]);
export type AgentRole = z.infer<typeof AgentRoleSchema>;

const AgentHistoryEntrySchema = z.object({
  at: z.string().min(1),
  role: AgentRoleSchema,
  step: z.string().min(1),
  note: z.string().optional(),
});

export const AgentStateSchema = z.object({
  schemaVersion: z.literal(AGENT_STATE_SCHEMA_VERSION),
  updatedAt: z.string().min(1),
  role: AgentRoleSchema.default("unset"),
  currentFocus: z.string().optional(),
  lastCompletedStep: z.string().optional(),
  nextAction: z.string().optional(),
  constraints: z.array(z.string()).default([]),
  history: z.array(AgentHistoryEntrySchema).default([]),
});
export type AgentState = z.infer<typeof AgentStateSchema>;

const HISTORY_LIMIT = 25;
const HISTORY_RENDERED = 10;

function nowIso(): string {
  return new Date().toISOString();
}

function emptyState(): AgentState {
  return {
    schemaVersion: AGENT_STATE_SCHEMA_VERSION,
    updatedAt: nowIso(),
    role: "unset",
    constraints: [],
    history: [],
  };
}

function agentStatePath(projectRoot: string): string {
  return join(projectRoot, "knowledge", "agent-state.json");
}

function nextMdPath(projectRoot: string): string {
  return join(projectRoot, "knowledge", "NEXT.md");
}

function loadAgentState(projectRoot: string): AgentState {
  const path = agentStatePath(projectRoot);
  if (!existsSync(path)) return emptyState();
  try {
    const raw = JSON.parse(readFileSync(path, "utf8"));
    return AgentStateSchema.parse(raw);
  } catch {
    return emptyState();
  }
}

function writeAtomic(path: string, body: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, body, "utf8");
  renameSync(tmp, path);
}

function saveAgentState(projectRoot: string, state: AgentState): void {
  const path = agentStatePath(projectRoot);
  writeAtomic(path, `${JSON.stringify(state, null, 2)}\n`);
}

function renderNextMd(projectRoot: string, projectName: string, state: AgentState): string {
  const lines: string[] = [];
  lines.push(`# NEXT — ${projectName}`);
  lines.push(``);
  lines.push(`_Updated: ${state.updatedAt}_`);
  lines.push(``);
  lines.push(`## Role`);
  lines.push(state.role);
  lines.push(``);
  lines.push(`## Current Focus`);
  lines.push(state.currentFocus?.trim() ? state.currentFocus : "_(not set)_");
  lines.push(``);
  lines.push(`## Last Completed Step`);
  lines.push(state.lastCompletedStep?.trim() ? state.lastCompletedStep : "_(none yet)_");
  lines.push(``);
  lines.push(`## Next Action`);
  lines.push(state.nextAction?.trim() ? state.nextAction : "_(propose via agent_propose_next)_");
  lines.push(``);
  lines.push(`## Constraints`);
  if (state.constraints.length === 0) {
    lines.push("_(none)_");
  } else {
    for (const c of state.constraints) lines.push(`- ${c}`);
  }
  lines.push(``);
  lines.push(`## History (most recent ${HISTORY_RENDERED})`);
  if (state.history.length === 0) {
    lines.push("_(empty)_");
  } else {
    const recent = state.history.slice(-HISTORY_RENDERED).reverse();
    for (const h of recent) {
      const noteSuffix = h.note ? ` — ${h.note}` : "";
      lines.push(`- ${h.at} [${h.role}] ${h.step}${noteSuffix}`);
    }
  }
  lines.push(``);
  lines.push(`---`);
  lines.push(`_Auto-generated by agent-workflow tools. Re-run agent_record_step / agent_set_role to update._`);
  void projectRoot;
  return lines.join("\n") + "\n";
}

function persistState(projectRoot: string, projectName: string, state: AgentState): AgentState {
  const updated: AgentState = { ...state, updatedAt: nowIso() };
  saveAgentState(projectRoot, updated);
  writeAtomic(nextMdPath(projectRoot), renderNextMd(projectRoot, projectName, updated));
  return updated;
}

function textContent(text: string) {
  return { content: [{ type: "text" as const, text }] };
}

interface ProposalCandidate {
  rank: number;
  source: "audit" | "phase" | "task" | "question" | "next-action" | "fallback" | "stale-view" | "unregistered-files" | "unimported-analysis";
  reason: string;
  suggestion: string;
}

const KNOWLEDGE_FILES = [
  "knowledge/entities.json",
  "knowledge/findings.json",
  "knowledge/relations.json",
  "knowledge/flows.json",
  "knowledge/tasks.json",
  "knowledge/open-questions.json",
  "knowledge/artifacts.json",
];

const VIEW_FILES = [
  "views/project-dashboard.json",
  "views/memory-map.json",
  "views/cartridge-layout.json",
  "views/disk-layout.json",
  "views/load-sequence.json",
  "views/flow-graph.json",
  "views/annotated-listing.json",
];

function maxMtime(projectRoot: string, paths: string[]): number {
  let max = 0;
  for (const rel of paths) {
    const full = join(projectRoot, rel);
    if (!existsSync(full)) continue;
    const m = statSync(full).mtimeMs;
    if (m > max) max = m;
  }
  return max;
}

function detectStaleViews(projectRoot: string): string[] {
  const knowledgeMtime = maxMtime(projectRoot, KNOWLEDGE_FILES);
  if (knowledgeMtime === 0) return [];
  const stale: string[] = [];
  for (const rel of VIEW_FILES) {
    const full = join(projectRoot, rel);
    if (!existsSync(full)) {
      stale.push(rel);
      continue;
    }
    if (statSync(full).mtimeMs < knowledgeMtime) {
      stale.push(rel);
    }
  }
  return stale;
}

function summarizeAuditState(audit: ProjectAuditResult): { knowledge: string; views: string } {
  const knowledge = audit.counts.nestedKnowledgeStores > 0
    ? "fragmented"
    : audit.counts.unimportedAnalysisArtifacts > 0 || audit.counts.unimportedManifestArtifacts > 0 || audit.counts.unregisteredFiles > 0
      ? "incomplete"
      : audit.counts.brokenArtifactPaths > 0 || audit.counts.missingArtifacts > 0
        ? "broken"
        : "ok";
  const views = audit.counts.staleViews > 0 ? "stale" : "fresh";
  return { knowledge, views };
}

function proposeNextActions(service: ProjectKnowledgeService, state: AgentState, projectRoot: string, audit?: ProjectAuditResult): ProposalCandidate[] {
  const candidates: ProposalCandidate[] = [];
  const auditResult = audit ?? auditProject(projectRoot, { includeFileScan: true, registrationSampleLimit: 5 });

  for (const finding of auditResult.findings.filter((item) => item.severity === "high" || item.severity === "medium").slice(0, 5)) {
    candidates.push({
      rank: candidates.length,
      source: "audit",
      reason: `${finding.severity}: ${finding.whyItMatters}`,
      suggestion: finding.suggestedFix,
    });
  }

  if (state.nextAction?.trim()) {
    candidates.push({
      rank: 0,
      source: "next-action",
      reason: "agent-state already has a queued next action",
      suggestion: state.nextAction.trim(),
    });
  }

  const stale = auditResult.counts.staleViews > 0 ? detectStaleViews(projectRoot) : [];
  if (stale.length > 0) {
    candidates.push({
      rank: candidates.length,
      source: "stale-view",
      reason: `${stale.length} view file(s) older than knowledge: ${stale.map((p) => p.replace(/^views\//, "")).join(", ")}`,
      suggestion: stale.length >= 3
        ? `Run build_all_views — multiple views are out of sync with knowledge.`
        : `Rebuild stale view(s): ${stale.map((p) => p.replace(/^views\//, "").replace(/\.json$/, "")).join(", ")}`,
    });
  }

  // Failsafe: surface unregistered-file delta as a top candidate. When
  // bulk operations bypassed the MCP layer (direct CLI loops, Node lib
  // imports, hand-emitted files), the artifact store falls behind the
  // filesystem. The agent must run register_existing_files before the
  // next session can rely on agent_onboard.
  const reg = auditResult.counts.unregisteredFiles > 0 ? scanRegistrationDelta(projectRoot, 5) : { unregisteredCount: 0, unregisteredByExt: {} as Record<string, number> };
  if (reg.unregisteredCount > 0) {
    const sorted = Object.entries(reg.unregisteredByExt).sort((a, b) => b[1] - a[1]).slice(0, 3);
    const extSummary = sorted.map(([ext, n]) => `${ext}=${n}`).join(", ");
    candidates.push({
      rank: candidates.length,
      source: "unregistered-files",
      reason: `${reg.unregisteredCount} files match c64re extensions but are absent from artifacts.json (${extSummary})`,
      suggestion: `Run register_existing_files with appropriate glob patterns, or scan_registration_delta to inspect first.`,
    });
  }

  const unimportedAnalysis = auditResult.counts.unimportedAnalysisArtifacts;
  if (unimportedAnalysis > 0) {
    candidates.push({
      rank: candidates.length,
      source: "unimported-analysis",
      reason: `${unimportedAnalysis} analysis-run artifact(s) registered but never imported into entities/findings`,
      suggestion: `Run bulk_import_analysis_reports — closes the loadSequence/Memory-Map "Payload focus" gap so stages back-link to entities.`,
    });
  }

  const status = service.getProjectStatus();
  const phases = status.workflowState.phases;
  const inProgress = phases.find((p) => p.status === "in_progress");
  const ready = phases.find((p) => p.status === "ready");
  const blocked = phases.filter((p) => p.status === "blocked");

  if (inProgress) {
    candidates.push({
      rank: candidates.length,
      source: "phase",
      reason: `phase '${inProgress.phaseId}' is in_progress`,
      suggestion: `Continue phase ${inProgress.phaseId}${inProgress.summary ? ` — ${inProgress.summary}` : ""}`,
    });
  }
  if (ready) {
    candidates.push({
      rank: candidates.length,
      source: "phase",
      reason: `phase '${ready.phaseId}' is ready`,
      suggestion: `Start phase ${ready.phaseId}${ready.summary ? ` — ${ready.summary}` : ""}`,
    });
  }

  const tasks = service.listTasks({ status: "in_progress" }).slice(0, 3);
  for (const task of tasks) {
    candidates.push({
      rank: candidates.length,
      source: "task",
      reason: `task in_progress (priority=${task.priority})`,
      suggestion: `Resume task: ${task.title}`,
    });
  }
  const openTasks = service.listTasks({ status: "open" }).slice(0, 3);
  for (const task of openTasks) {
    candidates.push({
      rank: candidates.length,
      source: "task",
      reason: `task open (priority=${task.priority})`,
      suggestion: `Pick up task: ${task.title}`,
    });
  }

  const questions = service.listOpenQuestions({ status: "open" }).slice(0, 3);
  for (const q of questions) {
    candidates.push({
      rank: candidates.length,
      source: "question",
      reason: `open question (priority=${q.priority})`,
      suggestion: `Resolve open question: ${q.title}`,
    });
  }

  for (const b of blocked) {
    candidates.push({
      rank: candidates.length,
      source: "phase",
      reason: `phase '${b.phaseId}' blocked by ${b.blockingPhaseIds.join(", ") || "(unknown)"}`,
      suggestion: `Unblock phase ${b.phaseId} — missing roles: ${b.missingArtifactRoles.join(", ") || "(none recorded)"}`,
    });
  }

  if (candidates.length === 0) {
    candidates.push({
      rank: 0,
      source: "fallback",
      reason: "no phases, tasks, or questions surfaced",
      suggestion: "Decide focus manually and call agent_set_role + agent_record_step to anchor it.",
    });
  }

  return candidates;
}

function recentArtifactSummary(service: ProjectKnowledgeService, projectRoot: string, limit = 8): string[] {
  const artifacts = service.listArtifacts().slice(-limit).reverse();
  return artifacts.map((a) => `- ${a.scope}/${a.kind} | ${a.title} | ${relative(projectRoot, a.path) || a.relativePath}`);
}

export function registerAgentWorkflowTools(server: McpServer, ctx: ServerToolContext): void {
  server.tool(
    "agent_onboard",
    "Reload persistent project state at session start (or after context loss). Reads project metadata, workflow phases, agent-state, recent artifacts, open tasks, and open questions, then proposes the next action. Always run this first when a session begins or after compaction.",
    {
      project_dir: z.string().optional().describe("Project root. Defaults to C64RE_PROJECT_DIR or process.cwd()."),
    },
    async ({ project_dir }) => {
      const projectRoot = ctx.projectDir(project_dir);
      const service = new ProjectKnowledgeService(projectRoot);
      // Bug 16 / Spec 022: auto-import analysis runs whose entities are
      // not yet back-linked, so the audit no longer warns about them.
      const autoImport = service.autoImportUnimportedAnalysisRuns();
      const status = service.getProjectStatus();
      const state = loadAgentState(projectRoot);
      const cached: AuditCachedResult = auditProjectCached(projectRoot, { includeFileScan: true, registrationSampleLimit: 5 });
      const audit = cached.audit;
      const auditState = summarizeAuditState(audit);
      const proposals = proposeNextActions(service, state, projectRoot, audit);

      const lines: string[] = [];
      lines.push(`# Agent Onboarding`);
      if (autoImport.imported > 0) {
        lines.push(`Auto-imported ${autoImport.imported} analysis-run artifact(s): ${autoImport.entities} entities, ${autoImport.findings} findings, ${autoImport.relations} relations, ${autoImport.flows} flows, ${autoImport.questions} open questions.`);
        lines.push(``);
      }
      lines.push(``);
      lines.push(`Project: ${status.project.name}`);
      lines.push(`Root: ${status.project.rootPath}`);
      lines.push(`Status: ${status.project.status}`);
      lines.push(`Knowledge: ${auditState.knowledge}`);
      lines.push(`Views: ${auditState.views}`);
      lines.push(`Audit: ${cached.cacheStatus}${cached.cachedAt ? ` (since ${cached.cachedAt})` : ""}`);
      lines.push(`Recommended next action: ${proposals[0]?.suggestion ?? "(none)"}`);
      lines.push(``);
      lines.push(`## Agent State`);
      lines.push(`Role: ${state.role}`);
      lines.push(`Current focus: ${state.currentFocus ?? "(unset)"}`);
      lines.push(`Last completed step: ${state.lastCompletedStep ?? "(none)"}`);
      lines.push(`Queued next action: ${state.nextAction ?? "(none)"}`);
      lines.push(`Constraints: ${state.constraints.length === 0 ? "(none)" : state.constraints.join("; ")}`);
      lines.push(``);
      lines.push(`## Workflow`);
      lines.push(`Summary: ${status.workflowState.summary}`);
      lines.push(`Current phase: ${status.workflowState.currentPhaseId ?? "(none)"}`);
      lines.push(`Next recommended phase: ${status.workflowState.nextRecommendedPhaseId ?? "(none)"}`);
      lines.push(``);
      lines.push(`## Counts`);
      lines.push(`artifacts=${status.counts.artifacts} entities=${status.counts.entities} findings=${status.counts.findings} relations=${status.counts.relations} flows=${status.counts.flows} tasks=${status.counts.tasks} openQuestions=${status.counts.openQuestions} checkpoints=${status.counts.checkpoints}`);
      lines.push(``);
      lines.push(`## Audit`);
      lines.push(`severity=${audit.severity} nestedKnowledgeStores=${audit.counts.nestedKnowledgeStores} missingArtifacts=${audit.counts.missingArtifacts} brokenArtifactPaths=${audit.counts.brokenArtifactPaths} unregisteredFiles=${audit.counts.unregisteredFiles} unimportedAnalysisArtifacts=${audit.counts.unimportedAnalysisArtifacts} unimportedManifestArtifacts=${audit.counts.unimportedManifestArtifacts} staleViews=${audit.counts.staleViews}`);
      if (audit.findings.length === 0) {
        lines.push(`No audit findings.`);
      } else {
        for (const finding of audit.findings.slice(0, 6)) {
          lines.push(`- [${finding.severity}] ${finding.title}: ${finding.suggestedFix}`);
        }
      }
      lines.push(``);
      lines.push(`## Recent Artifacts`);
      const recent = recentArtifactSummary(service, projectRoot);
      lines.push(...(recent.length === 0 ? ["_(none registered)_"] : recent));
      lines.push(``);
      lines.push(`## Registration Delta`);
      const reg = scanRegistrationDelta(projectRoot, 0);
      if (reg.unregisteredCount === 0) {
        lines.push(`✓ Filesystem and artifact store are in sync.`);
      } else {
        const sorted = Object.entries(reg.unregisteredByExt).sort((a, b) => b[1] - a[1]).slice(0, 5);
        lines.push(`⚠ ${reg.unregisteredCount} files on disk are NOT registered in artifacts.json.`);
        lines.push(`  Top extensions: ${sorted.map(([e, n]) => `${e}=${n}`).join(", ")}`);
        lines.push(`  Run scan_registration_delta to inspect, then register_existing_files to fix.`);
      }
      const unimportedAnalysis = countUnimportedAnalysisArtifacts(service);
      if (unimportedAnalysis > 0) {
        lines.push(``);
        lines.push(`⚠ ${unimportedAnalysis} analysis-run artifact(s) are registered but never imported.`);
        lines.push(`  Their entities/findings/relations are missing from the knowledge layer.`);
        lines.push(`  Run bulk_import_analysis_reports to back-fill — closes the Memory-Map / loadSequence Payload-Focus gap.`);
      }
      lines.push(``);
      lines.push(`## History (last ${Math.min(HISTORY_RENDERED, state.history.length)} of ${state.history.length})`);
      if (state.history.length === 0) {
        lines.push("_(empty)_");
      } else {
        for (const h of state.history.slice(-HISTORY_RENDERED).reverse()) {
          lines.push(`- ${h.at} [${h.role}] ${h.step}${h.note ? ` — ${h.note}` : ""}`);
        }
      }
      lines.push(``);
      lines.push(`## Proposed Next Actions`);
      for (const c of proposals) {
        lines.push(`${c.rank + 1}. (${c.source}) ${c.suggestion}  _(${c.reason})_`);
      }
      lines.push(``);
      lines.push(`## Pointers`);
      lines.push(`NEXT.md: ${nextMdPath(projectRoot)}`);
      lines.push(`agent-state.json: ${agentStatePath(projectRoot)}`);
      lines.push(`Phase plan: ${status.paths.knowledgePhasePlan}`);
      lines.push(`Workflow state: ${status.paths.knowledgeWorkflowState}`);
      return textContent(lines.join("\n"));
    },
  );

  server.tool(
    "agent_set_role",
    "Set the cognitive role for the current agent session (analyst, cartographer, implementer). Persists to agent-state.json + NEXT.md.",
    {
      project_dir: z.string().optional(),
      role: AgentRoleSchema.describe("analyst (disasm/control flow), cartographer (memory/bank maps), implementer (MCP tooling/host code), archivist (continuity, tasks, checkpoints, artifact registration), cracker (modifying target C64 binaries: patches, trainers, bug fixes, ports), or unset"),
      focus: z.string().optional().describe("Optional one-line focus statement for this role assignment"),
      constraints: z.array(z.string()).optional().describe("Optional list of constraints active for this role/session"),
    },
    async ({ project_dir, role, focus, constraints }) => {
      const projectRoot = ctx.projectDir(project_dir);
      const service = new ProjectKnowledgeService(projectRoot);
      const project = service.getProjectStatus().project;
      const prev = loadAgentState(projectRoot);
      const next: AgentState = {
        ...prev,
        role,
        currentFocus: focus ?? prev.currentFocus,
        constraints: constraints ?? prev.constraints,
      };
      const saved = persistState(projectRoot, project.name, next);
      return textContent(
        [
          `Agent role set.`,
          `Role: ${saved.role}`,
          `Focus: ${saved.currentFocus ?? "(unset)"}`,
          `Constraints: ${saved.constraints.length === 0 ? "(none)" : saved.constraints.join("; ")}`,
          `NEXT.md: ${nextMdPath(projectRoot)}`,
        ].join("\n"),
      );
    },
  );

  server.tool(
    "agent_record_step",
    "Record a completed step and (optionally) queue the next action. Appends to agent-state history and rewrites NEXT.md. Call this after meaningful work units so future sessions can resume.",
    {
      project_dir: z.string().optional(),
      step: z.string().describe("Short description of what was just completed"),
      next_action: z.string().optional().describe("Optional next action to queue for the upcoming step"),
      note: z.string().optional().describe("Optional context note attached to the history entry"),
      role: AgentRoleSchema.optional().describe("Optional new role to switch into atomically with this step"),
      focus: z.string().optional().describe("Optional new current-focus statement"),
      constraints: z.array(z.string()).optional().describe("Optional replacement for the constraints list"),
    },
    async ({ project_dir, step, next_action, note, role, focus, constraints }) => {
      const projectRoot = ctx.projectDir(project_dir);
      const service = new ProjectKnowledgeService(projectRoot);
      const project = service.getProjectStatus().project;
      const prev = loadAgentState(projectRoot);
      const effectiveRole: AgentRole = role ?? prev.role;
      const history = [
        ...prev.history,
        { at: nowIso(), role: effectiveRole, step, ...(note ? { note } : {}) },
      ].slice(-HISTORY_LIMIT);
      const next: AgentState = {
        ...prev,
        role: effectiveRole,
        currentFocus: focus ?? prev.currentFocus,
        constraints: constraints ?? prev.constraints,
        lastCompletedStep: step,
        nextAction: next_action ?? prev.nextAction,
        history,
      };
      const saved = persistState(projectRoot, project.name, next);
      const reg = scanRegistrationDelta(projectRoot, 0);
      const unimportedAnalysis = countUnimportedAnalysisArtifacts(service);
      const out = [
        `Step recorded.`,
        `Role: ${saved.role}`,
        `Last completed: ${saved.lastCompletedStep}`,
        `Queued next action: ${saved.nextAction ?? "(none)"}`,
        `History size: ${saved.history.length}`,
        `NEXT.md: ${nextMdPath(projectRoot)}`,
      ];
      if (reg.unregisteredCount > 0) {
        const sorted = Object.entries(reg.unregisteredByExt).sort((a, b) => b[1] - a[1]).slice(0, 3);
        out.push(``);
        out.push(`⚠ ${reg.unregisteredCount} files on disk are NOT registered (top: ${sorted.map(([e, n]) => `${e}=${n}`).join(", ")}).`);
        out.push(`  A run is not finished until artifacts are registered. Call register_existing_files before sealing this step.`);
      }
      if (unimportedAnalysis > 0) {
        out.push(``);
        out.push(`⚠ ${unimportedAnalysis} analysis-run artifact(s) registered but not imported into entities.`);
        out.push(`  Run bulk_import_analysis_reports to back-fill the knowledge layer.`);
      }
      return textContent(out.join("\n"));
    },
  );

  server.tool(
    "agent_propose_next",
    "Read-only: examine workflow phases, open tasks, open questions, and current agent-state to propose ranked next actions. Does not mutate state.",
    {
      project_dir: z.string().optional(),
    },
    async ({ project_dir }) => {
      const projectRoot = ctx.projectDir(project_dir);
      const service = new ProjectKnowledgeService(projectRoot);
      const state = loadAgentState(projectRoot);
      const cached = auditProjectCached(projectRoot, { includeFileScan: true, registrationSampleLimit: 5 });
      const audit = cached.audit;
      const proposals = proposeNextActions(service, state, projectRoot, audit);
      const lines: string[] = [];
      lines.push(`# Proposed Next Actions`);
      lines.push(``);
      lines.push(`Current role: ${state.role}`);
      lines.push(`Current focus: ${state.currentFocus ?? "(unset)"}`);
      lines.push(`Audit severity: ${audit.severity} (${cached.cacheStatus})`);
      lines.push(``);
      for (const c of proposals) {
        lines.push(`${c.rank + 1}. (${c.source}) ${c.suggestion}`);
        lines.push(`   reason: ${c.reason}`);
      }
      return textContent(lines.join("\n"));
    },
  );

  void resolve;
}
