// UI launcher scaffold — generates the workspace launchers in the project root:
// `ui.sh` for macOS / Linux and `ui.ps1` + three double-click `.cmd` shims for
// Windows. Both start / stop / restart the C64RE workspace (HTTP UI :4310 +
// runtime daemon :4312) pointed at this project. Background + logfile so an
// agent can call it without holding a foreground process; `restart` is a single
// self-contained kill+start.
//
// `npm run workspace` runs `build:mcp` on every start, so start/restart always
// rebuild the BACKEND (picks up runtime/palette changes). The FRONTEND bundle
// (ui/dist) is rebuilt only by the explicit `build-ui` command.
//
// BOTH sets are written on every platform, on purpose: a project folder travels
// between a Mac and a Windows box (Mike's), and whoever opens it there must find
// something to click without asking. Idempotent + non-destructive: an existing
// file is NEVER overwritten, so hand-edits survive a re-init.

import { existsSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";

/** Single-quote a string for safe embedding in a POSIX shell script. */
function shq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** Single-quote a string for safe embedding in PowerShell (no expansion, '' escapes '). */
function psq(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** A Windows path: forward slashes are legal but a user pasting it expects backslashes. */
function win(value: string): string {
  return value.replace(/\//g, "\\");
}

function launcherScript(projectDir: string, repoDir: string): string {
  return `#!/usr/bin/env bash
# C64RE workspace launcher — generated by project_init.
# Edit freely: project_init will NOT overwrite an existing ui.sh.
# Windows: use ui.ps1 / ui-start.cmd / ui-stop.cmd / ui-restart.cmd (same folder).
#
# Usage: ./ui.sh {start|stop|restart|status|build-ui|logs}
#   start     start the workspace in the background (HTTP :4310 + WS :4312)
#   restart   kill + start again (rebuilds the backend; picks up code changes)
#   stop      kill whatever holds :4310 / :4312
#   status    show whether the two ports are up
#   build-ui  rebuild the frontend bundle (ui/dist) — separate from the backend
#   logs      tail the workspace log
set -uo pipefail

REPO=${shq(repoDir)}
PROJECT=${shq(projectDir)}
HTTP_PORT=4310
WS_PORT=4312
LOG="$PROJECT/ui.log"
PIDFILE="$PROJECT/.ui.pid"

is_up() { lsof -ti:"$1" >/dev/null 2>&1; }

kill_ports() {
  for p in "$HTTP_PORT" "$WS_PORT"; do
    pids=$(lsof -ti:"$p" 2>/dev/null || true)
    [ -n "$pids" ] && kill $pids 2>/dev/null || true
  done
  if [ -f "$PIDFILE" ]; then kill "$(cat "$PIDFILE")" 2>/dev/null || true; rm -f "$PIDFILE"; fi
}

start() {
  if is_up "$HTTP_PORT" || is_up "$WS_PORT"; then
    echo "[ui.sh] already running (:$HTTP_PORT / :$WS_PORT) — use './ui.sh restart'"; exit 0
  fi
  cd "$REPO" || { echo "[ui.sh] repo not found: $REPO"; exit 1; }
  echo "[ui.sh] starting workspace -> HTTP :$HTTP_PORT  WS :$WS_PORT   (log: $LOG)"
  nohup npm run workspace -- --project "$PROJECT" >"$LOG" 2>&1 &
  echo $! >"$PIDFILE"
  echo "[ui.sh] pid $(cat "$PIDFILE")  ->  http://localhost:$HTTP_PORT   (tail: ./ui.sh logs)"
}

case "\${1:-start}" in
  start)    start ;;
  stop)     kill_ports; echo "[ui.sh] stopped (:$HTTP_PORT / :$WS_PORT)" ;;
  restart)  kill_ports; sleep 1; start ;;
  status)   for p in "$HTTP_PORT" "$WS_PORT"; do is_up "$p" && echo ":$p UP" || echo ":$p down"; done ;;
  build-ui) cd "$REPO" && npm run ui:build && echo "[ui.sh] ui/dist rebuilt" ;;
  logs)     tail -f "$LOG" ;;
  *) echo "usage: $0 {start|stop|restart|status|build-ui|logs}"; exit 1 ;;
esac
`;
}

/**
 * The Windows twin of ui.sh. Deliberately Windows PowerShell 5.1 compatible —
 * the one that ships with Windows, so Mike installs nothing — and it passes its
 * command line as ONE pre-quoted string, the only form Start-Process hands
 * through verbatim on 5.1 (an array gets re-quoted around spaces).
 *
 * Differences from ui.sh, all forced by the platform and none of them silent:
 *   - the workspace is started through `cmd.exe /c … > log 2>&1`, not through
 *     Start-Process's own redirect: `-RedirectStandardOutput` and
 *     `-WindowStyle Hidden` live in different Start-Process parameter sets and
 *     cannot be combined, and `-NoNewWindow` would tie the workspace's life to
 *     the console window a double-click opens. cmd.exe is this platform's nohup.
 *   - a port owner is found via Get-NetTCPConnection, with netstat as fallback.
 *   - a process is killed as a TREE (`taskkill /T`): killing a parent does not
 *     kill its children on Windows, and node spawns the daemon.
 *   - `start` waits for the port and then opens the browser — the click user's
 *     only feedback that anything happened.
 */
function powershellLauncherScript(projectDir: string, repoDir: string): string {
  return `#Requires -Version 5.1
<#
  C64RE workspace launcher (Windows) — generated by project_init.
  Edit freely: project_init will NOT overwrite an existing ui.ps1.

  Double-click:  ui-start.cmd  ui-stop.cmd  ui-restart.cmd   (same folder)
  From a shell:  powershell -ExecutionPolicy Bypass -File .\\ui.ps1 <action>

    start     start the workspace in the background (HTTP :4310 + WS :4312),
              wait for the port, then open the browser
    stop      kill whatever holds :4310 / :4312 (process TREE)
    restart   stop + start (rebuilds the backend; picks up code changes)
    status    show whether the two ports are up, and who owns them
    build-ui  rebuild the frontend bundle (ui/dist) — separate from the backend
    logs      follow the workspace log

  Needs: Node.js 22+ on PATH (node:sqlite), the C64RE repo built at least once.
  The PROJECT is this folder. The REPO is $env:C64RE_REPO, else the baked
  $REPO_BAKED below, else a sibling / ..\\Tools\\C64ReverseEngineeringMCP.
  The runtime daemon is picked up automatically from
  ..\\TRX64\\target\\release\\trx64-daemon.exe, or set C64RE_RUNTIME_BIN.
#>
param(
  [ValidateSet('start', 'stop', 'restart', 'status', 'build-ui', 'logs')]
  [string] $Action = 'start',
  [switch] $NoBuild,
  [switch] $NoBrowser
)

$ErrorActionPreference = 'Stop'

# The project is the folder this script sits in — never a baked path. A project
# folder is carried from the machine that ran project_init to another one (a Mac
# to Mike's Windows box), and a path from the first machine is wrong on the
# second. $PSScriptRoot is right by construction, including after a rename.
$PROJECT   = $PSScriptRoot
$HTTP_PORT = 4310
$WS_PORT   = 4312
$LOG       = Join-Path $PROJECT 'ui.log'
$PIDFILE   = Join-Path $PROJECT '.ui.pid'

# The repo CANNOT be derived from the project, so it is baked — but as the
# second choice, after $env:C64RE_REPO, and with two conventional layouts probed
# after it. Whoever moved the folder sets one variable instead of editing code.
$REPO_BAKED = ${psq(win(repoDir))}

function Write-Ui([string] $Message) { Write-Host "[ui.ps1] $Message" }

$script:RepoCache = $null
function Get-Repo {
  if ($script:RepoCache) { return $script:RepoCache }
  $parent = Split-Path $PROJECT -Parent
  $grand  = if ($parent) { Split-Path $parent -Parent } else { $null }
  $candidates = @()
  if ($env:C64RE_REPO) { $candidates += $env:C64RE_REPO }
  $candidates += $REPO_BAKED
  if ($parent) { $candidates += (Join-Path $parent 'C64ReverseEngineeringMCP') }
  if ($grand)  { $candidates += (Join-Path $grand 'C64ReverseEngineeringMCP') }
  if ($grand)  { $candidates += (Join-Path $grand 'Tools\\C64ReverseEngineeringMCP') }
  foreach ($candidate in $candidates) {
    if ($candidate -and (Test-Path (Join-Path $candidate 'scripts\\workspace.mjs'))) {
      $script:RepoCache = $candidate
      return $candidate
    }
  }
  throw ('[ui.ps1] the C64RE repo was not found. Looked in: ' + ($candidates -join '; ') + '. Set it once with:  setx C64RE_REPO "C:\\path\\to\\C64ReverseEngineeringMCP"  (then open a new window), or edit $REPO_BAKED at the top of this file.')
}

# Owning PIDs of a listening port. Get-NetTCPConnection is the fast path
# (Windows 8 / Server 2012 and newer); netstat is the fallback so this also
# works on a stripped-down or older box.
function Get-PortOwner([int] $Port) {
  # Which path to take is decided by asking, not by catching: an exception
  # thrown INSIDE a catch block is not caught by the same try, and that is how
  # a "port down" answer turns into a red wall of text.
  if (Get-Command 'Get-NetTCPConnection' -ErrorAction SilentlyContinue) {
    try {
      $conns = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction Stop
      return @($conns | Select-Object -ExpandProperty OwningProcess -Unique)
    } catch {
      return @()   # no listener on that port is the normal case, not an error
    }
  }
  if (-not (Get-Command 'netstat' -ErrorAction SilentlyContinue)) { return @() }
  try {
    $pattern = ':' + $Port + '\\s'
    $lines = & netstat -ano 2>$null | Select-String -Pattern $pattern | Select-String -Pattern 'LISTENING'
    $found = @()
    foreach ($line in $lines) {
      $parts = ($line.ToString().Trim() -split '\\s+')
      $last = $parts[$parts.Length - 1]
      if ($last -match '^\\d+$') { $found += [int] $last }
    }
    return @($found | Sort-Object -Unique)
  } catch {
    return @()
  }
}

function Test-PortUp([int] $Port) { return ((Get-PortOwner $Port).Count -gt 0) }

# Kill the whole tree: node spawns the runtime daemon, and on Windows killing a
# parent leaves the children listening.
function Stop-Tree([int] $TargetPid) {
  if ($TargetPid -le 4) { return }   # 0 = idle, 4 = System — never
  & taskkill.exe /PID $TargetPid /T /F 2>&1 | Out-Null
}

function Stop-Workspace {
  $killed = 0
  foreach ($port in @($HTTP_PORT, $WS_PORT)) {
    foreach ($owner in (Get-PortOwner $port)) { Stop-Tree ([int] $owner); $killed++ }
  }
  if (Test-Path $PIDFILE) {
    $saved = Get-Content $PIDFILE -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($saved -match '^\\d+$') { Stop-Tree ([int] $saved); $killed++ }
    Remove-Item $PIDFILE -Force -ErrorAction SilentlyContinue
  }
  return $killed
}

function Get-Npm {
  $npm = Get-Command 'npm.cmd' -ErrorAction SilentlyContinue
  if (-not $npm) { $npm = Get-Command 'npm' -ErrorAction SilentlyContinue }
  return $npm
}

# The first half of "npm run workspace". Kept in the FOREGROUND so a TypeScript
# error lands on screen instead of hiding in the log.
function Build-Backend {
  $repo = Get-Repo
  $server = Join-Path $repo 'dist\\workspace-ui\\server.js'
  $npm = Get-Npm
  if (-not $npm) {
    if (Test-Path $server) { Write-Warning '[ui.ps1] npm not on PATH - starting the build already in dist\\'; return }
    throw '[ui.ps1] npm not on PATH and dist\\workspace-ui\\server.js is missing. Install Node.js 22+ and run "npm install; npm run build" in the repo once.'
  }
  Write-Ui 'building backend (npm run build:mcp) ...'
  Push-Location $repo
  try { & $npm.Source 'run' 'build:mcp' } finally { Pop-Location }
  if ($LASTEXITCODE -ne 0) { throw ('[ui.ps1] backend build failed (exit ' + $LASTEXITCODE + ')') }
}

function Start-Workspace {
  if ((Test-PortUp $HTTP_PORT) -or (Test-PortUp $WS_PORT)) {
    Write-Ui "already running (:$HTTP_PORT / :$WS_PORT) - use ui-restart.cmd"
    return
  }
  $repo = Get-Repo
  $node = Get-Command 'node.exe' -ErrorAction SilentlyContinue
  if (-not $node) {
    throw '[ui.ps1] node.exe is not on PATH. Install Node.js 22 or newer (node:sqlite is required).'
  }
  if (-not $NoBuild) { Build-Backend }

  $entry = Join-Path $repo 'scripts\\workspace.mjs'
  if (-not (Test-Path $entry)) { throw "[ui.ps1] workspace entry not found: $entry" }
  Write-Ui "starting workspace -> HTTP :$HTTP_PORT  WS :$WS_PORT"
  Write-Ui "log: $LOG"

  # cmd.exe is this platform's nohup. Start-Process cannot both hide the window
  # and redirect (-WindowStyle and -RedirectStandardOutput are different
  # parameter sets), and -NoNewWindow would kill the workspace when the console
  # a double-click opened closes. So cmd does the redirect, both streams into
  # ONE log like ui.sh, and cmd's own pid goes into the pid file — taskkill /T
  # takes the node child down with it.
  $inner   = '"' + $node.Source + '" "' + $entry + '" --project "' + $PROJECT + '" > "' + $LOG + '" 2>&1'
  $argLine = '/c "' + $inner + '"'
  $startArgs = @{
    FilePath         = 'cmd.exe'
    ArgumentList     = $argLine
    WorkingDirectory = $repo
    WindowStyle      = 'Hidden'
    PassThru         = $true
  }
  $proc = Start-Process @startArgs
  Set-Content -Path $PIDFILE -Value $proc.Id -Encoding ascii
  Write-Ui ('pid ' + $proc.Id + '  ->  http://localhost:' + $HTTP_PORT)

  # Wait for the port so the browser does not open on a dead socket.
  $deadline = (Get-Date).AddSeconds(90)
  while ((Get-Date) -lt $deadline) {
    if (Test-PortUp $HTTP_PORT) {
      Write-Ui 'up.'
      if (-not $NoBrowser) { Start-Process ('http://localhost:' + $HTTP_PORT) | Out-Null }
      return
    }
    if ($proc.HasExited) {
      Write-Warning ('[ui.ps1] the workspace exited (code ' + $proc.ExitCode + '). Last lines of ' + $LOG + ':')
      if (Test-Path $LOG) { Get-Content $LOG -Tail 30 }
      throw '[ui.ps1] workspace failed to start'
    }
    Start-Sleep -Milliseconds 500
  }
  Write-Warning ("[ui.ps1] :$HTTP_PORT did not come up within 90 s - see $LOG")
}

switch ($Action) {
  'start' { Start-Workspace }
  'stop' {
    $n = Stop-Workspace
    Write-Ui "stopped (:$HTTP_PORT / :$WS_PORT, $n process tree(s))"
  }
  'restart' {
    $n = Stop-Workspace
    Write-Ui "stopped ($n process tree(s)), restarting ..."
    Start-Sleep -Seconds 1
    Start-Workspace
  }
  'status' {
    foreach ($port in @($HTTP_PORT, $WS_PORT)) {
      $owners = Get-PortOwner $port
      if ($owners.Count -gt 0) { Write-Host (':' + $port + ' UP   pid ' + ($owners -join ', ')) }
      else { Write-Host (':' + $port + ' down') }
    }
    if (Test-Path $LOG) { Write-Host ('log: ' + $LOG) }
  }
  'build-ui' {
    $npm = Get-Npm
    if (-not $npm) { throw '[ui.ps1] npm not on PATH' }
    Push-Location (Get-Repo)
    try { & $npm.Source 'run' 'ui:build' } finally { Pop-Location }
    if ($LASTEXITCODE -ne 0) { throw ('[ui.ps1] ui:build failed (exit ' + $LASTEXITCODE + ')') }
    Write-Ui 'ui/dist rebuilt'
  }
  'logs' {
    if (-not (Test-Path $LOG)) { throw "[ui.ps1] no log yet: $LOG" }
    Write-Ui "following $LOG   (Ctrl+C to stop)"
    Get-Content -Path $LOG -Tail 40 -Wait
  }
}
`;
}

/**
 * A double-click shim. Two things it buys that a bare .ps1 cannot: a
 * double-clicked .ps1 opens in Notepad, and the default ExecutionPolicy refuses
 * to run a downloaded/copied script. `-ExecutionPolicy Bypass` is scoped to this
 * one process — it changes no machine setting.
 */
function cmdShim(action: "start" | "stop" | "restart"): string {
  return `@echo off
REM C64RE workspace — generated by project_init. Double-click me.
REM Runs ui.ps1 in this folder; -ExecutionPolicy Bypass applies to THIS process only.
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0ui.ps1" ${action}
if errorlevel 1 pause
`;
}

export interface UiLauncherFile {
  path: string;
  created: boolean;
}

export interface UiLauncherResult {
  /** whether `ui.sh` was created (kept for callers that predate the Windows set) */
  created: boolean;
  /** path of `ui.sh` */
  path: string;
  /** every launcher file, POSIX and Windows */
  files: UiLauncherFile[];
}

/**
 * Write the launchers into `projectDir` — `ui.sh`, `ui.ps1` and the three
 * double-click shims. Each file is written only when absent, so hand-edits and
 * a re-init never collide.
 */
export function ensureUiLauncher(projectDir: string, repoDir: string): UiLauncherResult {
  const files: UiLauncherFile[] = [];
  const write = (name: string, body: string, executable = false): UiLauncherFile => {
    const path = join(projectDir, name);
    if (existsSync(path)) return { path, created: false };
    writeFileSync(path, body);
    if (executable) {
      try {
        chmodSync(path, 0o755);
      } catch {
        /* chmod best-effort; the file is still runnable via `bash ui.sh` */
      }
    }
    return { path, created: true };
  };

  const sh = write("ui.sh", launcherScript(projectDir, repoDir), true);
  files.push(sh);
  // Windows: CRLF, because Notepad and older PowerShell hosts choke on lone LF.
  const crlf = (text: string) => text.replace(/\r?\n/g, "\r\n");
  files.push(write("ui.ps1", crlf(powershellLauncherScript(projectDir, repoDir))));
  for (const action of ["start", "stop", "restart"] as const) {
    files.push(write(`ui-${action}.cmd`, crlf(cmdShim(action))));
  }

  return { created: sh.created, path: sh.path, files };
}
