// UI launcher starters — generated on request (`project_launchers`, `npm run launchers`),
// never by `project_init`, and only for the platform that was asked for:
//   linux   ui.sh + ui-start|stop|restart.desktop
//   macos   ui.sh + ui-start|stop|restart.command
//   windows ui.ps1 + ui-start|stop|restart.cmd
// All of them start / stop / restart the C64RE workspace (HTTP UI :4310 + runtime
// daemon :4312) pointed at this project. Background + logfile so an agent can call
// ui.sh without holding a foreground process; `restart` is a single self-contained
// kill+start. `ui.sh start|restart --open` additionally opens the browser once the
// port answers; the double-click starters pass it, a plain `./ui.sh start` does not.
//
// `npm run workspace` rebuilds the BACKEND on start when src/ changed since the
// last build (scripts/build-if-stale.mjs, Spec 885 D6 - picks up runtime/palette
// changes without paying tsc on every start). The FRONTEND bundle
// (ui/dist) is rebuilt only by the explicit `build-ui` command.
//
// Without `refresh` an existing file is never overwritten, so hand-edits survive;
// with `refresh` the requested platform's files are rewritten (a .desktop file
// holds an absolute path and goes stale when the project moves).

import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";

/** Single-quote a string for safe embedding in a POSIX shell script. */
/**
 * Spec 716 — a checkout has `scripts/workspace.mjs`; an installed package does not.
 *
 * The distinction decides how the launchers START the workbench, and getting it wrong is
 * how 0.1.1 shipped a workbench nobody could run: the scripts said `npm run workspace`,
 * which is `tsc -p tsconfig.json && node scripts/workspace.mjs`, and an installed package
 * has no tsconfig, no scripts/ and no TypeScript. In a package the same orchestration is
 * reached as `c64re ui`, already built, from dist/.
 */
export function isPackagedInstall(repoDir: string): boolean {
  // Both halves are needed. "No scripts/workspace.mjs" alone calls an empty directory a
  // package, which is how this first broke smoke:ui-launcher — that smoke hands in a
  // synthetic repo path to exercise spaces and an apostrophe, and it contains neither
  // marker. A package is identified POSITIVELY, by the built orchestrator being there
  // while the source entry is not.
  return existsSync(join(repoDir, "dist", "workspace-ui", "launch.js"))
    && !existsSync(join(repoDir, "scripts", "workspace.mjs"));
}

/**
 * How a packaged launcher invokes the workbench. Nothing is baked: under `npx` the
 * package lives in a cache directory that changes with every version and can be evicted,
 * so a path written into a project's launcher goes stale without warning. The name is
 * stable; the path is not.
 */
const PACKAGE_INVOCATION = "npx -y @trex64/c64re";

function shq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** Single-quote a string for safe embedding in PowerShell (no expansion, '' escapes '). */
function psq(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** A Windows path: forward slashes are legal but a user pasting it expects backslashes. */
function win(value: string): string {
  return value.replace(/\//g, "\\");
}

function launcherScript(projectDir: string, repoDir: string, packaged: boolean): string {
  return `#!/usr/bin/env bash
# C64RE workspace launcher — generated by project_launchers.
# Edit freely: project_launchers rewrites an existing ui.sh only with refresh.
#
# Usage: ./ui.sh {start|stop|restart|status|build-ui|logs} [--open]
#   start     start the workspace in the background (HTTP :4310 + WS :4312)
#   restart   kill + start again (rebuilds the backend; picks up code changes)
#   --open    (start/restart) wait for :4310, then open it in the browser
#   stop      kill whatever holds :4310 / :4312
#   status    show whether the two ports are up
#   build-ui  rebuild the frontend bundle (ui/dist) — separate from the backend
#   logs      tail the workspace log
set -uo pipefail

${packaged
  ? `# Installed from npm: nothing is baked. A globally installed \`c64re\` is used when it is
# on PATH, otherwise npx fetches the package by name — the name is stable, the npx cache
# path is not.
C64RE=$(command -v c64re >/dev/null 2>&1 && echo c64re || echo ${shq(PACKAGE_INVOCATION)})`
  : `REPO=${shq(repoDir)}`}
PROJECT=${shq(projectDir)}
HTTP_PORT=4310
WS_PORT=4312
LOG="$PROJECT/ui.log"
PIDFILE="$PROJECT/.ui.pid"

is_up() { lsof -ti:"$1" >/dev/null 2>&1; }

kill_ports() {
  for p in "$HTTP_PORT" "$WS_PORT"; do
    pids=$(lsof -ti:"$p" 2>/dev/null || true)
    [ -n "$pids" ] && kill $pids 2>/dev/null || true
  done
  if [ -f "$PIDFILE" ]; then kill "$(cat "$PIDFILE")" 2>/dev/null || true; rm -f "$PIDFILE"; fi
}

start() {
  # WS_PORT (the runtime daemon) is shared/external by design and can be up on
  # its own (e.g. an MCP session started it) without the workspace itself
  # running — so only HTTP_PORT (this workspace's own server) is evidence of
  # "already running". OR-ing in WS_PORT here caused start to silently no-op
  # whenever the daemon was already up, never launching the HTTP backend.
  if is_up "$HTTP_PORT"; then
    echo "[ui.sh] already running (:$HTTP_PORT) — use './ui.sh restart'"; return 0
  fi
  ${packaged ? "" : `cd "$REPO" || { echo "[ui.sh] repo not found: $REPO"; exit 1; }
  `}echo "[ui.sh] starting workspace -> HTTP :$HTTP_PORT  WS :$WS_PORT   (log: $LOG)"
  nohup ${packaged ? "$C64RE ui" : "npm run workspace --"} --project "$PROJECT" >"$LOG" 2>&1 &
  echo $! >"$PIDFILE"
  echo "[ui.sh] pid $(cat "$PIDFILE")  ->  http://localhost:$HTTP_PORT   (tail: ./ui.sh logs)"
}

# Wait for the port so the browser does not open on a dead socket.
open_browser() {
  local opener=xdg-open
  [ "$(uname -s)" = Darwin ] && opener=open
  for _ in $(seq 180); do
    if is_up "$HTTP_PORT"; then
      echo "[ui.sh] up."
      "$opener" "http://localhost:$HTTP_PORT" >/dev/null 2>&1 &
      return 0
    fi
    if [ -f "$PIDFILE" ] && ! kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
      echo "[ui.sh] the workspace exited. Last lines of $LOG:"; tail -n 30 "$LOG"; return 1
    fi
    sleep 0.5
  done
  echo "[ui.sh] :$HTTP_PORT did not come up within 90 s - see $LOG"; return 1
}

OPEN=0; [ "\${2:-}" = "--open" ] && OPEN=1

case "\${1:-start}" in
  start)    start; [ "$OPEN" = 1 ] && { open_browser || exit 1; }; true ;;
  stop)     kill_ports; echo "[ui.sh] stopped (:$HTTP_PORT / :$WS_PORT)" ;;
  restart)  kill_ports; sleep 1; start; [ "$OPEN" = 1 ] && { open_browser || exit 1; }; true ;;
  status)   for p in "$HTTP_PORT" "$WS_PORT"; do is_up "$p" && echo ":$p UP" || echo ":$p down"; done ;;
  build-ui) ${packaged
    ? `echo "[ui.sh] the bundle ships with the package — nothing to rebuild." ;;`
    : `cd "$REPO" && npm run ui:build && echo "[ui.sh] ui/dist rebuilt" ;;`}
  logs)     tail -f "$LOG" ;;
  *) echo "usage: $0 {start|stop|restart|status|build-ui|logs} [--open]"; exit 1 ;;
esac
`;
}

/**
 * The Windows twin of ui.sh. Deliberately Windows PowerShell 5.1 compatible —
 * the one that ships with Windows, so Mike installs nothing — and it passes its
 * command line as ONE pre-quoted string, the only form Start-Process hands
 * through verbatim on 5.1 (an array gets re-quoted around spaces).
 *
 * Differences from ui.sh, all forced by the platform and none of them silent:
 *   - the workspace is started through `cmd.exe /c … > log 2>&1`, not through
 *     Start-Process's own redirect: `-RedirectStandardOutput` and
 *     `-WindowStyle Hidden` live in different Start-Process parameter sets and
 *     cannot be combined, and `-NoNewWindow` would tie the workspace's life to
 *     the console window a double-click opens. cmd.exe is this platform's nohup.
 *   - a port owner is found via Get-NetTCPConnection, with netstat as fallback.
 *   - a process is killed as a TREE (`taskkill /T`): killing a parent does not
 *     kill its children on Windows, and node spawns the daemon.
 *   - `start` waits for the port and then opens the browser — the click user's
 *     only feedback that anything happened.
 */
function powershellLauncherScript(projectDir: string, repoDir: string, packaged: boolean): string {
  return `#Requires -Version 5.1
<#
  C64RE workspace launcher (Windows) — generated by project_launchers.
  Edit freely: project_launchers rewrites an existing ui.ps1 only with refresh.

  Double-click:  ui-start.cmd  ui-stop.cmd  ui-restart.cmd   (same folder)
  From a shell:  powershell -ExecutionPolicy Bypass -File .\\ui.ps1 <action>

    start     start the workspace in the background (HTTP :4310 + WS :4312),
              wait for the port, then open the browser
    stop      kill whatever holds :4310 / :4312 (process TREE)
    restart   stop + start (rebuilds the backend; picks up code changes)
    status    show whether the two ports are up, and who owns them
    build-ui  rebuild the frontend bundle (ui/dist) — separate from the backend
    logs      follow the workspace log

  Needs: Node.js 22+ on PATH (node:sqlite), the C64RE repo built at least once.
  The PROJECT is this folder. The REPO is $env:C64RE_REPO, else the baked
  $REPO_BAKED below, else a sibling / ..\\Tools\\C64ReverseEngineeringMCP.
  The runtime daemon is picked up automatically from
  ..\\TRX64\\target\\release\\trx64-daemon.exe, or set C64RE_RUNTIME_BIN.
#>
param(
  [ValidateSet('start', 'stop', 'restart', 'status', 'build-ui', 'logs')]
  [string] $Action = 'start',
  [switch] $NoBuild,
  [switch] $NoBrowser
)

$ErrorActionPreference = 'Stop'

# The project is the folder this script sits in — never a baked path. A project
# folder is carried from the machine that generated it to another one (a Mac
# to Mike's Windows box), and a path from the first machine is wrong on the
# second. $PSScriptRoot is right by construction, including after a rename.
$PROJECT   = $PSScriptRoot
$HTTP_PORT = 4310
$WS_PORT   = 4312
$LOG       = Join-Path $PROJECT 'ui.log'
$PIDFILE   = Join-Path $PROJECT '.ui.pid'

${packaged
  ? `# Installed from npm: nothing is baked. Under npx the package sits in a cache directory
# that changes with every version and can be evicted, so a path written in here would go
# stale without warning. The NAME is stable, so the name is what gets invoked.
$C64RE_PKG = '@trex64/c64re'`
  : `# The repo CANNOT be derived from the project, so it is baked — but as the
# second choice, after $env:C64RE_REPO, and with two conventional layouts probed
# after it. Whoever moved the folder sets one variable instead of editing code.
$REPO_BAKED = ${psq(win(repoDir))}`}

function Write-Ui([string] $Message) { Write-Host "[ui.ps1] $Message" }

$script:RepoCache = $null
function Get-Repo {
  if ($script:RepoCache) { return $script:RepoCache }
  $parent = Split-Path $PROJECT -Parent
  $grand  = if ($parent) { Split-Path $parent -Parent } else { $null }
  $candidates = @()
  if ($env:C64RE_REPO) { $candidates += $env:C64RE_REPO }
  $candidates += $REPO_BAKED
  if ($parent) { $candidates += (Join-Path $parent 'C64ReverseEngineeringMCP') }
  if ($grand)  { $candidates += (Join-Path $grand 'C64ReverseEngineeringMCP') }
  if ($grand)  { $candidates += (Join-Path $grand 'Tools\\C64ReverseEngineeringMCP') }
  foreach ($candidate in $candidates) {
    if ($candidate -and (Test-Path (Join-Path $candidate 'scripts\\workspace.mjs'))) {
      $script:RepoCache = $candidate
      return $candidate
    }
  }
  throw ('[ui.ps1] the C64RE repo was not found. Looked in: ' + ($candidates -join '; ') + '. Set it once with:  setx C64RE_REPO "C:\\path\\to\\C64ReverseEngineeringMCP"  (then open a new window), or edit $REPO_BAKED at the top of this file.')
}

# Owning PIDs of a listening port. Get-NetTCPConnection is the fast path
# (Windows 8 / Server 2012 and newer); netstat is the fallback so this also
# works on a stripped-down or older box.
function Get-PortOwner([int] $Port) {
  # Which path to take is decided by asking, not by catching: an exception
  # thrown INSIDE a catch block is not caught by the same try, and that is how
  # a "port down" answer turns into a red wall of text.
  if (Get-Command 'Get-NetTCPConnection' -ErrorAction SilentlyContinue) {
    try {
      $conns = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction Stop
      return @($conns | Select-Object -ExpandProperty OwningProcess -Unique)
    } catch {
      return @()   # no listener on that port is the normal case, not an error
    }
  }
  if (-not (Get-Command 'netstat' -ErrorAction SilentlyContinue)) { return @() }
  try {
    $pattern = ':' + $Port + '\\s'
    $lines = & netstat -ano 2>$null | Select-String -Pattern $pattern | Select-String -Pattern 'LISTENING'
    $found = @()
    foreach ($line in $lines) {
      $parts = ($line.ToString().Trim() -split '\\s+')
      $last = $parts[$parts.Length - 1]
      if ($last -match '^\\d+$') { $found += [int] $last }
    }
    return @($found | Sort-Object -Unique)
  } catch {
    return @()
  }
}

function Test-PortUp([int] $Port) { return ((Get-PortOwner $Port).Count -gt 0) }

# Kill the whole tree: node spawns the runtime daemon, and on Windows killing a
# parent leaves the children listening.
function Stop-Tree([int] $TargetPid) {
  if ($TargetPid -le 4) { return }   # 0 = idle, 4 = System — never
  # No stderr redirection at all (not even 2>$null): under
  # $ErrorActionPreference='Stop', PowerShell 5.1 wraps ANY redirected error
  # stream from a native exe in a terminating ErrorRecord — even redirected to
  # null — so a PID that already crashed/exited ("process not found") aborts
  # the whole script. Leaving stream 2 unredirected lets it print to the host
  # (harmless noise) without going through PowerShell's error stream.
  & taskkill.exe /PID $TargetPid /T /F | Out-Null
}

function Stop-Workspace {
  $killed = 0
  foreach ($port in @($HTTP_PORT, $WS_PORT)) {
    foreach ($owner in (Get-PortOwner $port)) { Stop-Tree ([int] $owner); $killed++ }
  }
  if (Test-Path $PIDFILE) {
    $saved = Get-Content $PIDFILE -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($saved -match '^\\d+$') { Stop-Tree ([int] $saved); $killed++ }
    Remove-Item $PIDFILE -Force -ErrorAction SilentlyContinue
  }
  return $killed
}

function Get-Npm {
  $npm = Get-Command 'npm.cmd' -ErrorAction SilentlyContinue
  if (-not $npm) { $npm = Get-Command 'npm' -ErrorAction SilentlyContinue }
  return $npm
}

${packaged ? `# Nothing to build: the package ships compiled.` : `# The first half of the checkout's workspace script. Kept in the FOREGROUND so a
# TypeScript error lands on screen instead of hiding in the log.`}
function Build-Backend {
${packaged ? `  # The package ships built. There is nothing to compile and no repo to compile it in.
  return
}
function Build-Backend-Unused {` : ``}  $repo = Get-Repo
  $server = Join-Path $repo 'dist\\workspace-ui\\server.js'
  $npm = Get-Npm
  if (-not $npm) {
    if (Test-Path $server) { Write-Warning '[ui.ps1] npm not on PATH - starting the build already in dist\\'; return }
    throw '[ui.ps1] npm not on PATH and dist\\workspace-ui\\server.js is missing. Install Node.js 22+ and run "npm install; npm run build" in the repo once.'
  }
  # Spec 885 D6 - compile only when src\\ changed since the last build (~11 s saved
  # on every start of an unchanged checkout). -NoBuild skips even the check.
  $node = Get-Command 'node.exe' -ErrorAction SilentlyContinue
  $stale = Join-Path $repo 'scripts\\build-if-stale.mjs'
  Push-Location $repo
  try {
    if ($node -and (Test-Path $stale)) { & $node.Source $stale }
    else { Write-Ui 'building backend (npm run build:mcp) ...'; & $npm.Source 'run' 'build:mcp' }
  } finally { Pop-Location }
  if ($LASTEXITCODE -ne 0) { throw ('[ui.ps1] backend build failed (exit ' + $LASTEXITCODE + ')') }
}

function Start-Workspace {
  # WS_PORT (the runtime daemon) is shared/external by design and can be up on
  # its own (e.g. an MCP session started it) without the workspace itself
  # running — so only HTTP_PORT (this workspace's own server) is evidence of
  # "already running". OR-ing in WS_PORT here caused start to silently no-op
  # whenever the daemon was already up, never launching the HTTP backend.
  if (Test-PortUp $HTTP_PORT) {
    Write-Ui "already running (:$HTTP_PORT) - use ui-restart.cmd"
    return
  }
${packaged
  ? `  # A global install puts \`c64re\` on PATH; otherwise npx fetches it by name.
  $cli = Get-Command 'c64re' -ErrorAction SilentlyContinue
  if ($cli) { $launcher = $cli.Source; $launchArgs = @('ui') }
  else {
    $npx = Get-Command 'npx' -ErrorAction SilentlyContinue
    if (-not $npx) { throw '[ui.ps1] neither c64re nor npx is on PATH. Install Node.js 22 or newer.' }
    $launcher = $npx.Source; $launchArgs = @('-y', $C64RE_PKG, 'ui')
  }
  $repo = $PROJECT`
  : `  $repo = Get-Repo
  $node = Get-Command 'node.exe' -ErrorAction SilentlyContinue
  if (-not $node) {
    throw '[ui.ps1] node.exe is not on PATH. Install Node.js 22 or newer (node:sqlite is required).'
  }
  if (-not $NoBuild) { Build-Backend }

  $entry = Join-Path $repo 'scripts\\workspace.mjs'
  if (-not (Test-Path $entry)) { throw "[ui.ps1] workspace entry not found: $entry" }`}
  Write-Ui "starting workspace -> HTTP :$HTTP_PORT  WS :$WS_PORT"
  Write-Ui "log: $LOG"

  # cmd.exe is this platform's nohup. Start-Process cannot both hide the window
  # and redirect (-WindowStyle and -RedirectStandardOutput are different
  # parameter sets), and -NoNewWindow would kill the workspace when the console
  # a double-click opened closes. So cmd does the redirect, both streams into
  # ONE log like ui.sh, and cmd's own pid goes into the pid file — taskkill /T
  # takes the node child down with it.
  $inner   = ${packaged
    ? `'"' + $launcher + '" ' + ($launchArgs -join ' ') + ' --project "' + $PROJECT + '" > "' + $LOG + '" 2>&1'`
    : `'"' + $node.Source + '" "' + $entry + '" --project "' + $PROJECT + '" > "' + $LOG + '" 2>&1'`}
  $argLine = '/c "' + $inner + '"'
  $startArgs = @{
    FilePath         = 'cmd.exe'
    ArgumentList     = $argLine
    WorkingDirectory = $repo
    WindowStyle      = 'Hidden'
    PassThru         = $true
  }
  $proc = Start-Process @startArgs
  Set-Content -Path $PIDFILE -Value $proc.Id -Encoding ascii
  Write-Ui ('pid ' + $proc.Id + '  ->  http://localhost:' + $HTTP_PORT)

  # Wait for the port so the browser does not open on a dead socket.
  $deadline = (Get-Date).AddSeconds(90)
  while ((Get-Date) -lt $deadline) {
    if (Test-PortUp $HTTP_PORT) {
      Write-Ui 'up.'
      if (-not $NoBrowser) { Start-Process ('http://localhost:' + $HTTP_PORT) | Out-Null }
      return
    }
    if ($proc.HasExited) {
      Write-Warning ('[ui.ps1] the workspace exited (code ' + $proc.ExitCode + '). Last lines of ' + $LOG + ':')
      if (Test-Path $LOG) { Get-Content $LOG -Tail 30 }
      throw '[ui.ps1] workspace failed to start'
    }
    Start-Sleep -Milliseconds 500
  }
  Write-Warning ("[ui.ps1] :$HTTP_PORT did not come up within 90 s - see $LOG")
}

switch ($Action) {
  'start' { Start-Workspace }
  'stop' {
    $n = Stop-Workspace
    Write-Ui "stopped (:$HTTP_PORT / :$WS_PORT, $n process tree(s))"
  }
  'restart' {
    $n = Stop-Workspace
    Write-Ui "stopped ($n process tree(s)), restarting ..."
    Start-Sleep -Seconds 1
    Start-Workspace
  }
  'status' {
    foreach ($port in @($HTTP_PORT, $WS_PORT)) {
      $owners = Get-PortOwner $port
      if ($owners.Count -gt 0) { Write-Host (':' + $port + ' UP   pid ' + ($owners -join ', ')) }
      else { Write-Host (':' + $port + ' down') }
    }
    if (Test-Path $LOG) { Write-Host ('log: ' + $LOG) }
  }
  'build-ui' {
${packaged
  ? `    Write-Ui 'the bundle ships with the package - nothing to rebuild.'`
  : `    $npm = Get-Npm
    if (-not $npm) { throw '[ui.ps1] npm not on PATH' }
    Push-Location (Get-Repo)
    try { & $npm.Source 'run' 'ui:build' } finally { Pop-Location }
    if ($LASTEXITCODE -ne 0) { throw ('[ui.ps1] ui:build failed (exit ' + $LASTEXITCODE + ')') }
    Write-Ui 'ui/dist rebuilt'`}
  }
  'logs' {
    if (-not (Test-Path $LOG)) { throw "[ui.ps1] no log yet: $LOG" }
    Write-Ui "following $LOG   (Ctrl+C to stop)"
    Get-Content -Path $LOG -Tail 40 -Wait
  }
}
`;
}

/**
 * A double-click shim. Two things it buys that a bare .ps1 cannot: a
 * double-clicked .ps1 opens in Notepad, and the default ExecutionPolicy refuses
 * to run a downloaded/copied script. `-ExecutionPolicy Bypass` is scoped to this
 * one process — it changes no machine setting.
 */
function cmdShim(action: "start" | "stop" | "restart"): string {
  // ASCII only: a .cmd file is read in the console's OEM codepage, where a
  // typographic dash is not what was written.
  return `@echo off
REM C64RE workspace - generated by project_launchers. Double-click me.
REM Runs ui.ps1 in this folder; -ExecutionPolicy Bypass applies to THIS process only.
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0ui.ps1" ${action}
if errorlevel 1 pause
`;
}

export type UiPlatform = "linux" | "macos" | "windows";

export interface UiLauncherFile {
  path: string;
  /** written by this call (new, or rewritten with refresh) */
  created: boolean;
}

export interface UiLauncherResult {
  platform: UiPlatform;
  /** whether the platform's main script (`ui.sh` / `ui.ps1`) was written by this call */
  created: boolean;
  /** path of the main script */
  path: string;
  /** every launcher file of this platform */
  files: UiLauncherFile[];
}

export interface UiLauncherOptions {
  /** default: the system this process runs on */
  platform?: UiPlatform;
  /** rewrite this platform's files even when they exist */
  refresh?: boolean;
}

export function hostUiPlatform(): UiPlatform {
  return process.platform === "darwin" ? "macos" : process.platform === "win32" ? "windows" : "linux";
}

const ACTIONS = ["start", "stop", "restart"] as const;
type Action = (typeof ACTIONS)[number];

function desktopEntry(action: Action, projectDir: string): string {
  const open = action === "stop" ? "" : " --open";
  const name = `${action[0].toUpperCase()}${action.slice(1)}`;
  const label = projectDir.split("/").filter(Boolean).pop() ?? projectDir;
  return `[Desktop Entry]
Type=Application
Name=C64RE UI ${name}
Comment=Run ui.sh ${action} for ${label}
Exec=bash -c "./ui.sh ${action}${open}; read -rp 'Press Enter to close'"
Path=${projectDir}
Terminal=true
Icon=utilities-terminal
`;
}

function commandFile(action: Action): string {
  const open = action === "stop" ? "" : " --open";
  return `#!/bin/bash
cd "$(dirname "$0")" || exit 1
./ui.sh ${action}${open}
`;
}

/**
 * Write the starters for ONE platform into `projectDir`. Without `refresh` only missing
 * files are written, so hand-edits survive; with it the platform's files are rewritten.
 * Files of other platforms are never touched, created or deleted.
 */
export function ensureUiLaunchers(projectDir: string, repoDir: string, options: UiLauncherOptions = {}): UiLauncherResult {
  const platform = options.platform ?? hostUiPlatform();
  const refresh = options.refresh === true;
  const packaged = isPackagedInstall(repoDir);
  const files: UiLauncherFile[] = [];
  const write = (name: string, body: string, executable = false): UiLauncherFile => {
    const path = join(projectDir, name);
    if (existsSync(path) && !refresh) return { path, created: false };
    writeFileSync(path, body);
    if (executable) {
      try {
        chmodSync(path, 0o755);
      } catch {
        /* chmod best-effort; ui.sh is still runnable via `bash ui.sh` */
      }
    }
    return { path, created: true };
  };

  if (platform === "windows") {
    // CRLF, because Notepad and older PowerShell hosts choke on lone LF.
    const crlf = (text: string) => text.replace(/\r?\n/g, "\r\n");
    // …and a UTF-8 BOM on the .ps1: Windows PowerShell 5.1 reads a BOM-less file in the
    // ANSI codepage, so every em dash in a comment arrives as mojibake and a non-ASCII
    // character in a string would change what the script does.
    files.push(write("ui.ps1", `\uFEFF${crlf(powershellLauncherScript(projectDir, repoDir, packaged))}`));
    for (const action of ACTIONS) files.push(write(`ui-${action}.cmd`, crlf(cmdShim(action))));
  } else {
    files.push(write("ui.sh", launcherScript(projectDir, repoDir, packaged), true));
    for (const action of ACTIONS) {
      if (platform === "linux") {
        const f = write(`ui-${action}.desktop`, desktopEntry(action, projectDir), true);
        files.push(f);
        // Mark it trusted so GNOME/Cinnamon launch it without "Allow Launching".
        // Only meaningful on a Linux host; a failure (no gio, no session bus) is ignored.
        if (f.created && process.platform === "linux") {
          try {
            spawnSync("gio", ["set", f.path, "metadata::trusted", "true"], { stdio: "ignore", timeout: 5000 });
          } catch {
            /* best effort */
          }
        }
      } else {
        files.push(write(`ui-${action}.command`, commandFile(action), true));
      }
    }
  }

  const main = files[0];
  return { platform, created: main.created, path: main.path, files };
}
