// UI launcher scaffold — generates a `ui.sh` in the project root that starts /
// restarts the C64RE workspace (HTTP UI :4310 + runtime daemon :4312) pointed at
// this project. Background + logfile so an agent can call it without holding a
// foreground process; `restart` is a single self-contained kill+start.
//
// `npm run workspace` runs `build:mcp` on every start, so start/restart always
// rebuild the BACKEND (picks up runtime/palette changes). The FRONTEND bundle
// (ui/dist) is rebuilt only by the explicit `ui.sh build-ui` command.
//
// Idempotent + non-destructive: an existing ui.sh is NEVER overwritten, so a
// user's hand-edits survive a re-init.

import { existsSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";

/** Single-quote a string for safe embedding in a POSIX shell script. */
function shq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function launcherScript(projectDir: string, repoDir: string): string {
  return `#!/usr/bin/env bash
# C64RE workspace launcher — generated by project_init.
# Edit freely: project_init will NOT overwrite an existing ui.sh.
#
# Usage: ./ui.sh {start|stop|restart|status|build-ui|logs}
#   start     start the workspace in the background (HTTP :4310 + WS :4312)
#   restart   kill + start again (rebuilds the backend; picks up code changes)
#   stop      kill whatever holds :4310 / :4312
#   status    show whether the two ports are up
#   build-ui  rebuild the frontend bundle (ui/dist) — separate from the backend
#   logs      tail the workspace log
set -uo pipefail

REPO=${shq(repoDir)}
PROJECT=${shq(projectDir)}
HTTP_PORT=4310
WS_PORT=4312
LOG="$PROJECT/ui.log"
PIDFILE="$PROJECT/.ui.pid"

is_up() { lsof -ti:"$1" >/dev/null 2>&1; }

kill_ports() {
  for p in "$HTTP_PORT" "$WS_PORT"; do
    pids=$(lsof -ti:"$p" 2>/dev/null || true)
    [ -n "$pids" ] && kill $pids 2>/dev/null || true
  done
  if [ -f "$PIDFILE" ]; then kill "$(cat "$PIDFILE")" 2>/dev/null || true; rm -f "$PIDFILE"; fi
}

start() {
  if is_up "$HTTP_PORT" || is_up "$WS_PORT"; then
    echo "[ui.sh] already running (:$HTTP_PORT / :$WS_PORT) — use './ui.sh restart'"; exit 0
  fi
  cd "$REPO" || { echo "[ui.sh] repo not found: $REPO"; exit 1; }
  echo "[ui.sh] starting workspace -> HTTP :$HTTP_PORT  WS :$WS_PORT   (log: $LOG)"
  nohup npm run workspace -- --project "$PROJECT" >"$LOG" 2>&1 &
  echo $! >"$PIDFILE"
  echo "[ui.sh] pid $(cat "$PIDFILE")  ->  http://localhost:$HTTP_PORT   (tail: ./ui.sh logs)"
}

case "\${1:-start}" in
  start)    start ;;
  stop)     kill_ports; echo "[ui.sh] stopped (:$HTTP_PORT / :$WS_PORT)" ;;
  restart)  kill_ports; sleep 1; start ;;
  status)   for p in "$HTTP_PORT" "$WS_PORT"; do is_up "$p" && echo ":$p UP" || echo ":$p down"; done ;;
  build-ui) cd "$REPO" && npm run ui:build && echo "[ui.sh] ui/dist rebuilt" ;;
  logs)     tail -f "$LOG" ;;
  *) echo "usage: $0 {start|stop|restart|status|build-ui|logs}"; exit 1 ;;
esac
`;
}

/**
 * Write `<projectDir>/ui.sh` if absent. Never clobbers an existing file.
 * Returns whether it created the launcher and its path.
 */
export function ensureUiLauncher(
  projectDir: string,
  repoDir: string,
): { created: boolean; path: string } {
  const path = join(projectDir, "ui.sh");
  if (existsSync(path)) return { created: false, path };
  writeFileSync(path, launcherScript(projectDir, repoDir));
  try {
    chmodSync(path, 0o755);
  } catch {
    /* chmod best-effort; the file is still runnable via `bash ui.sh` */
  }
  return { created: true, path };
}
