// Generated by scripts/extract-vice-opcode-cycles.mjs — do not edit.
// Spec 092.1 microcode table.

export type AddressModePattern =
  | "imp"
  | "acc"
  | "imm"
  | "zp_read"
  | "zp_write"
  | "zp_rmw"
  | "zpx_read"
  | "zpx_write"
  | "zpx_rmw"
  | "zpy_read"
  | "zpy_write"
  | "abs_read"
  | "abs_write"
  | "abs_rmw"
  | "absx_read"
  | "absx_write"
  | "absx_rmw"
  | "absy_read"
  | "absy_write"
  | "ind_jmp"
  | "indx_read"
  | "indx_write"
  | "indx_rmw"
  | "indy_read"
  | "indy_write"
  | "indy_rmw"
  | "rel"
  | "push"
  | "pop"
  | "brk"
  | "rti"
  | "rts"
  | "jsr"
  | "jmp_abs"
;

export type MicroOp = string;

export const ADDR_MODE_PATTERNS: Record<AddressModePattern, MicroOp[]> = {
  "imp": [
    "fetch_opcode",
    "internal"
  ],
  "acc": [
    "fetch_opcode",
    "internal"
  ],
  "imm": [
    "fetch_opcode",
    "fetch_imm"
  ],
  "zp_read": [
    "fetch_opcode",
    "fetch_zp_lo",
    "read_ea"
  ],
  "zp_write": [
    "fetch_opcode",
    "fetch_zp_lo",
    "write_ea"
  ],
  "zp_rmw": [
    "fetch_opcode",
    "fetch_zp_lo",
    "read_ea",
    "dummy_write_ea_old",
    "write_ea_new"
  ],
  "zpx_read": [
    "fetch_opcode",
    "fetch_zp_lo",
    "dummy_zp",
    "read_ea"
  ],
  "zpx_write": [
    "fetch_opcode",
    "fetch_zp_lo",
    "dummy_zp",
    "write_ea"
  ],
  "zpx_rmw": [
    "fetch_opcode",
    "fetch_zp_lo",
    "dummy_zp",
    "read_ea",
    "dummy_write_ea_old",
    "write_ea_new"
  ],
  "zpy_read": [
    "fetch_opcode",
    "fetch_zp_lo",
    "dummy_zp",
    "read_ea"
  ],
  "zpy_write": [
    "fetch_opcode",
    "fetch_zp_lo",
    "dummy_zp",
    "write_ea"
  ],
  "abs_read": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi",
    "read_ea"
  ],
  "abs_write": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi",
    "write_ea"
  ],
  "abs_rmw": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi",
    "read_ea",
    "dummy_write_ea_old",
    "write_ea_new"
  ],
  "absx_read": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi",
    "read_ea_pgx"
  ],
  "absx_write": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi",
    "dummy_addr",
    "write_ea"
  ],
  "absx_rmw": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi",
    "dummy_addr",
    "read_ea",
    "dummy_write_ea_old",
    "write_ea_new"
  ],
  "absy_read": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi",
    "read_ea_pgy"
  ],
  "absy_write": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi",
    "dummy_addr",
    "write_ea"
  ],
  "ind_jmp": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi",
    "read_ea_lo",
    "read_ea_hi"
  ],
  "indx_read": [
    "fetch_opcode",
    "fetch_zp_lo",
    "dummy_zp",
    "fetch_ind_lo",
    "fetch_ind_hi",
    "read_ea"
  ],
  "indx_write": [
    "fetch_opcode",
    "fetch_zp_lo",
    "dummy_zp",
    "fetch_ind_lo",
    "fetch_ind_hi",
    "write_ea"
  ],
  "indx_rmw": [
    "fetch_opcode",
    "fetch_zp_lo",
    "dummy_zp",
    "fetch_ind_lo",
    "fetch_ind_hi",
    "read_ea",
    "dummy_write_ea_old",
    "write_ea_new"
  ],
  "indy_read": [
    "fetch_opcode",
    "fetch_zp_lo",
    "fetch_ind_lo",
    "fetch_ind_hi",
    "read_ea_pgy"
  ],
  "indy_write": [
    "fetch_opcode",
    "fetch_zp_lo",
    "fetch_ind_lo",
    "fetch_ind_hi",
    "dummy_addr",
    "write_ea"
  ],
  "indy_rmw": [
    "fetch_opcode",
    "fetch_zp_lo",
    "fetch_ind_lo",
    "fetch_ind_hi",
    "dummy_addr",
    "read_ea",
    "dummy_write_ea_old",
    "write_ea_new"
  ],
  "rel": [
    "fetch_opcode",
    "fetch_imm"
  ],
  "push": [
    "fetch_opcode",
    "internal",
    "push"
  ],
  "pop": [
    "fetch_opcode",
    "internal",
    "dummy_sp",
    "pop"
  ],
  "brk": [
    "fetch_opcode",
    "fetch_dummy_pc",
    "push_pch",
    "push_pcl",
    "push_p_brk",
    "read_brk_vec_lo",
    "read_brk_vec_hi"
  ],
  "rti": [
    "fetch_opcode",
    "internal",
    "dummy_sp",
    "pop_p",
    "pop_pcl",
    "pop_pch"
  ],
  "rts": [
    "fetch_opcode",
    "internal",
    "dummy_sp",
    "pop_pcl",
    "pop_pch",
    "fetch_pc_dummy"
  ],
  "jsr": [
    "fetch_opcode",
    "fetch_lo",
    "dummy_sp",
    "push_pch",
    "push_pcl",
    "fetch_hi"
  ],
  "jmp_abs": [
    "fetch_opcode",
    "fetch_lo",
    "fetch_hi"
  ]
} as const;

export interface MicrocodeEntry {
  op: string;
  mode: string;
  cycles: number;
  pattern: AddressModePattern;
}

export const MICROCODE_TABLE: Array<MicrocodeEntry | null> = [
  {
    "op": "brk",
    "mode": "imp",
    "cycles": 7,
    "pattern": "brk"
  },
  {
    "op": "ora",
    "mode": "indx",
    "cycles": 6,
    "pattern": "indx_read"
  },
  null,
  null,
  null,
  {
    "op": "ora",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "asl",
    "mode": "zp",
    "cycles": 5,
    "pattern": "zp_rmw"
  },
  null,
  {
    "op": "php",
    "mode": "imp",
    "cycles": 3,
    "pattern": "push"
  },
  {
    "op": "ora",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "asl",
    "mode": "acc",
    "cycles": 2,
    "pattern": "acc"
  },
  null,
  null,
  {
    "op": "ora",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "asl",
    "mode": "abs",
    "cycles": 6,
    "pattern": "abs_rmw"
  },
  null,
  {
    "op": "bpl",
    "mode": "rel",
    "cycles": 2,
    "pattern": "rel"
  },
  {
    "op": "ora",
    "mode": "indy",
    "cycles": 5,
    "pattern": "indy_read"
  },
  null,
  null,
  null,
  {
    "op": "ora",
    "mode": "zpx",
    "cycles": 4,
    "pattern": "zpx_read"
  },
  {
    "op": "asl",
    "mode": "zpx",
    "cycles": 6,
    "pattern": "zpx_rmw"
  },
  null,
  {
    "op": "clc",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "ora",
    "mode": "absy",
    "cycles": 4,
    "pattern": "absy_read"
  },
  null,
  null,
  null,
  {
    "op": "ora",
    "mode": "absx",
    "cycles": 4,
    "pattern": "absx_read"
  },
  {
    "op": "asl",
    "mode": "absx",
    "cycles": 7,
    "pattern": "absx_rmw"
  },
  null,
  {
    "op": "jsr",
    "mode": "abs",
    "cycles": 6,
    "pattern": "jsr"
  },
  {
    "op": "and",
    "mode": "indx",
    "cycles": 6,
    "pattern": "indx_read"
  },
  null,
  null,
  {
    "op": "bit",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "and",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "rol",
    "mode": "zp",
    "cycles": 5,
    "pattern": "zp_rmw"
  },
  null,
  {
    "op": "plp",
    "mode": "imp",
    "cycles": 4,
    "pattern": "pop"
  },
  {
    "op": "and",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "rol",
    "mode": "acc",
    "cycles": 2,
    "pattern": "acc"
  },
  null,
  {
    "op": "bit",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "and",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "rol",
    "mode": "abs",
    "cycles": 6,
    "pattern": "abs_rmw"
  },
  null,
  {
    "op": "bmi",
    "mode": "rel",
    "cycles": 2,
    "pattern": "rel"
  },
  {
    "op": "and",
    "mode": "indy",
    "cycles": 5,
    "pattern": "indy_read"
  },
  null,
  null,
  null,
  {
    "op": "and",
    "mode": "zpx",
    "cycles": 4,
    "pattern": "zpx_read"
  },
  {
    "op": "rol",
    "mode": "zpx",
    "cycles": 6,
    "pattern": "zpx_rmw"
  },
  null,
  {
    "op": "sec",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "and",
    "mode": "absy",
    "cycles": 4,
    "pattern": "absy_read"
  },
  null,
  null,
  null,
  {
    "op": "and",
    "mode": "absx",
    "cycles": 4,
    "pattern": "absx_read"
  },
  {
    "op": "rol",
    "mode": "absx",
    "cycles": 7,
    "pattern": "absx_rmw"
  },
  null,
  {
    "op": "rti",
    "mode": "imp",
    "cycles": 6,
    "pattern": "rti"
  },
  {
    "op": "eor",
    "mode": "indx",
    "cycles": 6,
    "pattern": "indx_read"
  },
  null,
  null,
  null,
  {
    "op": "eor",
    "mode": "zp",
    "cycles": 4,
    "pattern": "zp_read"
  },
  {
    "op": "lsr",
    "mode": "zp",
    "cycles": 5,
    "pattern": "zp_rmw"
  },
  null,
  {
    "op": "pha",
    "mode": "imp",
    "cycles": 3,
    "pattern": "push"
  },
  {
    "op": "eor",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "lsr",
    "mode": "acc",
    "cycles": 2,
    "pattern": "acc"
  },
  null,
  {
    "op": "jmp",
    "mode": "abs",
    "cycles": 3,
    "pattern": "jmp_abs"
  },
  {
    "op": "eor",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "lsr",
    "mode": "abs",
    "cycles": 6,
    "pattern": "abs_rmw"
  },
  null,
  {
    "op": "bvc",
    "mode": "rel",
    "cycles": 2,
    "pattern": "rel"
  },
  {
    "op": "eor",
    "mode": "indy",
    "cycles": 5,
    "pattern": "indy_read"
  },
  null,
  null,
  null,
  {
    "op": "eor",
    "mode": "zpx",
    "cycles": 3,
    "pattern": "zpx_read"
  },
  {
    "op": "lsr",
    "mode": "zpx",
    "cycles": 6,
    "pattern": "zpx_rmw"
  },
  null,
  {
    "op": "cli",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "eor",
    "mode": "absy",
    "cycles": 4,
    "pattern": "absy_read"
  },
  null,
  null,
  null,
  {
    "op": "eor",
    "mode": "absx",
    "cycles": 4,
    "pattern": "absx_read"
  },
  {
    "op": "lsr",
    "mode": "absx",
    "cycles": 7,
    "pattern": "absx_rmw"
  },
  null,
  {
    "op": "rts",
    "mode": "imp",
    "cycles": 6,
    "pattern": "rts"
  },
  {
    "op": "adc",
    "mode": "indx",
    "cycles": 6,
    "pattern": "indx_read"
  },
  null,
  null,
  null,
  {
    "op": "adc",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "ror",
    "mode": "zp",
    "cycles": 5,
    "pattern": "zp_rmw"
  },
  null,
  {
    "op": "pla",
    "mode": "imp",
    "cycles": 4,
    "pattern": "pop"
  },
  {
    "op": "adc",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "ror",
    "mode": "acc",
    "cycles": 2,
    "pattern": "acc"
  },
  null,
  {
    "op": "jmp",
    "mode": "ind",
    "cycles": 5,
    "pattern": "ind_jmp"
  },
  {
    "op": "adc",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "ror",
    "mode": "abs",
    "cycles": 6,
    "pattern": "abs_rmw"
  },
  null,
  {
    "op": "bvs",
    "mode": "rel",
    "cycles": 2,
    "pattern": "rel"
  },
  {
    "op": "adc",
    "mode": "indy",
    "cycles": 5,
    "pattern": "indy_read"
  },
  null,
  null,
  null,
  {
    "op": "adc",
    "mode": "zpx",
    "cycles": 4,
    "pattern": "zpx_read"
  },
  {
    "op": "ror",
    "mode": "zpx",
    "cycles": 6,
    "pattern": "zpx_rmw"
  },
  null,
  {
    "op": "sei",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "adc",
    "mode": "absy",
    "cycles": 4,
    "pattern": "absy_read"
  },
  null,
  null,
  null,
  {
    "op": "adc",
    "mode": "absx",
    "cycles": 4,
    "pattern": "absx_read"
  },
  {
    "op": "ror",
    "mode": "absx",
    "cycles": 7,
    "pattern": "absx_rmw"
  },
  null,
  null,
  {
    "op": "sta",
    "mode": "indx",
    "cycles": 6,
    "pattern": "indx_write"
  },
  null,
  null,
  {
    "op": "sty",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_write"
  },
  {
    "op": "sta",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_write"
  },
  {
    "op": "stx",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_write"
  },
  null,
  {
    "op": "dey",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  null,
  {
    "op": "txa",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  null,
  {
    "op": "sty",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_write"
  },
  {
    "op": "sta",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_write"
  },
  {
    "op": "stx",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_write"
  },
  null,
  {
    "op": "bcc",
    "mode": "rel",
    "cycles": 2,
    "pattern": "rel"
  },
  {
    "op": "sta",
    "mode": "indy",
    "cycles": 6,
    "pattern": "indy_write"
  },
  null,
  null,
  {
    "op": "sty",
    "mode": "zpx",
    "cycles": 4,
    "pattern": "zpx_write"
  },
  {
    "op": "sta",
    "mode": "zpx",
    "cycles": 4,
    "pattern": "zpx_write"
  },
  {
    "op": "stx",
    "mode": "zpy",
    "cycles": 4,
    "pattern": "zpy_write"
  },
  null,
  {
    "op": "tya",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "sta",
    "mode": "absy",
    "cycles": 5,
    "pattern": "absy_write"
  },
  {
    "op": "txs",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  null,
  null,
  {
    "op": "sta",
    "mode": "absx",
    "cycles": 5,
    "pattern": "absx_write"
  },
  null,
  null,
  {
    "op": "ldy",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "lda",
    "mode": "indx",
    "cycles": 6,
    "pattern": "indx_read"
  },
  {
    "op": "ldx",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  null,
  {
    "op": "ldy",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "lda",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "ldx",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  null,
  {
    "op": "tay",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "lda",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "tax",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  null,
  {
    "op": "ldy",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "lda",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "ldx",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  null,
  {
    "op": "bcs",
    "mode": "rel",
    "cycles": 2,
    "pattern": "rel"
  },
  {
    "op": "lda",
    "mode": "indy",
    "cycles": 5,
    "pattern": "indy_read"
  },
  null,
  null,
  {
    "op": "ldy",
    "mode": "zpx",
    "cycles": 4,
    "pattern": "zpx_read"
  },
  {
    "op": "lda",
    "mode": "zpx",
    "cycles": 4,
    "pattern": "zpx_read"
  },
  {
    "op": "ldx",
    "mode": "zpy",
    "cycles": 4,
    "pattern": "zpy_read"
  },
  null,
  {
    "op": "clv",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "lda",
    "mode": "absy",
    "cycles": 4,
    "pattern": "absy_read"
  },
  {
    "op": "tsx",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  null,
  {
    "op": "ldy",
    "mode": "absx",
    "cycles": 4,
    "pattern": "absx_read"
  },
  {
    "op": "lda",
    "mode": "absx",
    "cycles": 4,
    "pattern": "absx_read"
  },
  {
    "op": "ldx",
    "mode": "absy",
    "cycles": 4,
    "pattern": "absy_read"
  },
  null,
  {
    "op": "cpy",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "cmp",
    "mode": "indx",
    "cycles": 6,
    "pattern": "indx_read"
  },
  null,
  null,
  {
    "op": "cpy",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "cmp",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "dec",
    "mode": "zp",
    "cycles": 5,
    "pattern": "zp_rmw"
  },
  null,
  {
    "op": "iny",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "cmp",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "dex",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  null,
  {
    "op": "cpy",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "cmp",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "dec",
    "mode": "abs",
    "cycles": 6,
    "pattern": "abs_rmw"
  },
  null,
  {
    "op": "bne",
    "mode": "rel",
    "cycles": 2,
    "pattern": "rel"
  },
  {
    "op": "cmp",
    "mode": "indy",
    "cycles": 5,
    "pattern": "indy_read"
  },
  null,
  null,
  null,
  {
    "op": "cmp",
    "mode": "zpx",
    "cycles": 4,
    "pattern": "zpx_read"
  },
  {
    "op": "dec",
    "mode": "zpx",
    "cycles": 6,
    "pattern": "zpx_rmw"
  },
  null,
  {
    "op": "cld",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "cmp",
    "mode": "absy",
    "cycles": 4,
    "pattern": "absy_read"
  },
  null,
  null,
  null,
  {
    "op": "cmp",
    "mode": "absx",
    "cycles": 4,
    "pattern": "absx_read"
  },
  {
    "op": "dec",
    "mode": "absx",
    "cycles": 7,
    "pattern": "absx_rmw"
  },
  null,
  {
    "op": "cpx",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "sbc",
    "mode": "indx",
    "cycles": 6,
    "pattern": "indx_read"
  },
  null,
  null,
  {
    "op": "cpx",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "sbc",
    "mode": "zp",
    "cycles": 3,
    "pattern": "zp_read"
  },
  {
    "op": "inc",
    "mode": "zp",
    "cycles": 5,
    "pattern": "zp_rmw"
  },
  null,
  {
    "op": "inx",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "sbc",
    "mode": "imm",
    "cycles": 2,
    "pattern": "imm"
  },
  {
    "op": "nop",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  null,
  {
    "op": "cpx",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "sbc",
    "mode": "abs",
    "cycles": 4,
    "pattern": "abs_read"
  },
  {
    "op": "inc",
    "mode": "abs",
    "cycles": 6,
    "pattern": "abs_rmw"
  },
  null,
  {
    "op": "beq",
    "mode": "rel",
    "cycles": 2,
    "pattern": "rel"
  },
  {
    "op": "sbc",
    "mode": "indy",
    "cycles": 5,
    "pattern": "indy_read"
  },
  null,
  null,
  null,
  {
    "op": "sbc",
    "mode": "zpx",
    "cycles": 4,
    "pattern": "zpx_read"
  },
  {
    "op": "inc",
    "mode": "zpx",
    "cycles": 6,
    "pattern": "zpx_rmw"
  },
  null,
  {
    "op": "sed",
    "mode": "imp",
    "cycles": 2,
    "pattern": "imp"
  },
  {
    "op": "sbc",
    "mode": "absy",
    "cycles": 4,
    "pattern": "absy_read"
  },
  null,
  null,
  null,
  {
    "op": "sbc",
    "mode": "absx",
    "cycles": 4,
    "pattern": "absx_read"
  },
  {
    "op": "inc",
    "mode": "absx",
    "cycles": 7,
    "pattern": "absx_rmw"
  },
  null
];
